---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
  # installCRDs: true
  # replicaCount: 5
  # extraArgs:
    # - --autogenInternals=false
    # - --clientRateLimitQPS=30
    # - --clientRateLimitBurst=60
  # serviceMonitor:
    # enabled: true
  # topologySpreadConstraints:
    # - maxSkew: 1
      # topologyKey: kubernetes.io/hostname
      # whenUnsatisfiable: DoNotSchedule
      # labelSelector:
        # matchLabels:
          # app.kubernetes.io/instance: kyverno
    replicaCount: 6
    crds:
      install: true
    grafana:
      enabled: true
    serviceMonitor:
      enabled: true
    backgroundController:
      serviceMonitor:
        enabled: true
    cleanupController:
      serviceMonitor:
        enabled: true
    reportsController:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 92m
        memory: 1039M
      limits:
        memory: 1332M
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kyverno
