apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ykL7XIPYNy5NzZy3LXloBg==,iv:sMLEEImQvlvliNFjB5b1hE4IXCtuLbp5uVjo424VI6M=,tag:ocFBOd/IGNhxm5w6K0u4TA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:/2BKHaoLmoDBZPWSrucixTAEZ7VrSs7j6MB7XP/u+mDPN0/bGA==,iv:7DrHAfDdfcZ8vqZlfDfkAHwGhOwk933444Bf4S4XMu8=,tag:6YJ5wQ9AOBljUXEDkp6qaw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xu/DERqg3B7eXm7U5iKFyg==,iv:Ja0q2s2+S0kgGHPIC5UOfH7TrDQVvu4eqzJFb/g9wgo=,tag:JJJyxUg5gQlP56bofZi6JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQlJueXd6Z0JjZ2YydGFz
            V01ZT3RXVnlIbHEydWVBWTJSSFlZT0VrMFNFCmRydk9YTzNOQ2VNamlWdWRtTUt5
            Wm9PS0grbFp3ZlJYenhubFpkam51U0UKLS0tIHlaMU43UzhCRVNId1hOL0FYdjIw
            MjlSNVJBQ2ZoSU1KUUdqczA3dHdETW8KKpvOkH8QjC9T7MhOFqCEBRR942lKFgji
            qTmPCs6/DNcCQqhfsBJWP7xeDGuH2blpJpAsyaMyvvOYrbUuKcj5hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T06:50:47Z"
    mac: ENC[AES256_GCM,data:NU3kHGT95nk0pGPH0oy4YHtHQ8aYBd6D6qTsc87nEv13OMDMMyth964szKVZLtxxSOW5UXN7k1EGgvddezHMerimdkp+sEeQpo9d3mSfHl98qRbKAKL+m7eb4qgK6Xa6PomxJykJ66YNiD0gztDOIvIhQy9WTp5qb9fEfFBMK78=,iv:Q/SFY5gZBFqjrIXVJEGfb+4qdiFARQTVq4mcOFyHo9k=,tag:UO9w6aJwG/YRWhv81LlDIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
