apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aRyZpntDDIZ77nI6d1Ck1w==,iv:k4p3kn/ri192Nf1Al4WWnHTTp4tD3Lm1Q1CTGcXK45Q=,tag:jcW2hhiZBNEezdIQr3DGdw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:8inB/Q8AjFB6gOFS8v9niDMthE4c4YAjbcrYtiyS8UC53am13Q==,iv:uenYixGaQ5O2XLkVHSgO2G+qUqCZwNrgCShdXe44xgs=,tag:wvLsm3Sj1BqxGfRuDHF2ag==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:q4d1Z8P+QfIWmaFPS1mJOw==,iv:Tk6LoaoJRqe6W75yI0svo6wkuaiy0w0Rn2l3rKlWyPk=,tag:wEmWxQQGYbesTyqBkaqAzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bW1FS2JYdUpSVVRzemt1
            ZXNzcWxqWVd6cTJOLzBOK0VkeU9aWFQ3WDI0CjRKcmNlZjZrU01lN2lxYm9HUnp1
            d1pneUJBWC9QSFh3U2xocXNmWHhnRDQKLS0tIHpESnZQbnd2aEVpcFQwNys1aUZ6
            QTB1ZllmaEdYSVBnZ2VoZERuTWllK1UKnkozmUTrDco9JSHX6YL29kIVI4IEQNJe
            baMuIpnUt55GohowMPKvdMjCndtXTIwKDKuYbJeAcfYFqHBVAMsxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:p3sO1n6NvNo96LGneKPzKYGg0kwyTlzXQvo/3roGRfdFi6O2bO4z7ChSqQ3OM4uDsRYi26ufZ/y+PJkK2i3WpkLUKJZH7Kawol+7mnB6XJ5qDeCWgMTWZUjgeAdzQF7Fiy/pN3W8FAnOtpnO9NAYRrKBbTU+GUmZ09GAAaPlKhQ=,iv:pvbDxAhGrWx6Q5iODlyQcW1/57VtPcSMgvgtIwdXBas=,tag:CppGD9roxBQzYXxjFJhKGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
