apiVersion: v1
kind: Secret
metadata:
    name: docker
    namespace: default
data:
    .dockerconfigjson:
        auths:
            https://index.docker.io/v1/:
                auth: ENC[AES256_GCM,data:sQ911X0nBQMCp5Be/RflSEXykp7MGZ7wZ6Zy27Ra7kL0Za3u,iv:/cWu36bJAHhL8wA5YFedqPjzKDErL5kp1xXeZhUffPw=,tag:yqZr+mdTNRf5sIV3Pb4bfw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWdSUTl1WkdQSlZSSEZU
            cmhKMURYeWdISWw1NDllRGx1MVJ3VHdYbEZVCkw1MGs1YlY0ZUNnaEhNTUovOVIx
            WW40L1ZweGlJREZ2c0ZPTmtldm9HdDQKLS0tIGo4QUhNZ0tnQ0RPY00ydHppSnZj
            MWZ5Qy9pVkh5Y01EWjFmTkt6YUsvTUkKVUKXTIcyBGYJNpDURmBDyx00zvauwt2p
            mRG810hhu7GPYhu352E9OqKfjMVDKVPyrl6FBE5N1j/DgAbRSydU7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-12T05:13:25Z"
    mac: ENC[AES256_GCM,data:sKfLf6330NfuM42nH1VUjAA0oTh3xG0n0mDQi/T+Xcuj4S+hGrJfHeyvDM+gYPLT1MQnQae52Akq7DdLvAxZ6B5pXybrpKMXJLTy/8b1psDVeY8cNCTDueBC5pU15s6BhSXjr0CEpq+nOrXjt/P2W3NW8X7tfi55Q4nv3ivwXvo=,iv:0Wvuuhi1jwMnwkm+2gM1oDBNKNG40im2mwRlhvJ0aSk=,tag:9+SbPXkZdV2l/26jw4xZTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
