apiVersion: v1
kind: Secret
metadata:
    name: docker
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7j+KwRqrDVyNv2GGyfBckk8Xp+voUCuuhYAy8YRcXnCzNOrv5eYn7Vu/9iQAkHz4eafmUEC9w654jG/K4Lb/yy+AuaQNp2MIQA9Aj4RztELKXxHFGiAFKJTvOS4i4hCf7ZsZ/1Pe4qAKAtnNz3Yq8swxH5CkbpAlfWC9rsHMZDRNexOIbfAttjhcr2p5p92e,iv:hwJnJDFlc7yfo1PpCswh+77lu0Wiq+kKxyKphLz4SbM=,tag:+BW2OTpAOICX7iZxZbbsBg==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QlRRcmFKR2hOUkw4YklY
            UTViVHlpM08wRVJLWmJiR1EvOTVRTXF2UTFJCmluRm5DUGZHekFDWk03YXNONHJ6
            RFluS1J0ZkYzbHpaRStaVmsyVW5nRGMKLS0tIHdZU0RmUTRFdkJVMzBLOFJmWDdx
            dEw4dmtUWkdBVzNEaXdvN2tvY2JmWW8KEi5ZKIGAtudl3FHoNvGLismIyo54bu5y
            Ro9oYWtXf90FAxsb9LiAhhnMnrxrPBFvyU0FMe8OZZY6qDpsKwCmPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T15:51:59Z"
    mac: ENC[AES256_GCM,data:khDDM66/P61qV0siO4U23EhFdM4CshBzsxc+9KzjXucChXYeRrb18mjrafyoXHGDg7ChqvS8xupoi3hbY5UHN8isI3pJBKesx6EHj+svShsN1ZhXMUQeqyQfEwZMQrTXr5KP1Q936bKwPyyMGRw1lcsnjAfYXHEkFMAr+6V+TDs=,iv:ACwkWFD5FT7jKbDQc2expfmfx1yIMH0j6MIVolmYDQg=,tag:xgQybLplA8BxwtZN+v+orQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
