---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vpnconfig
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        VPN_SERVICE_PROVIDER: custom
        VPN_TYPE: wireguard
        VPN_ENDPOINT_IP: "{{ .VPN_ENDPOINT_IP }}"
        VPN_ENDPOINT_PORT: "51820"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_ADDRESSES: 10.0.5.2/32
  dataFrom:
    - extract:
        key: vpn
