apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:XVuJCNv0,iv:nkoMfqfi9N92jVy8kEOjIY4HhpNT4rD3aQ64Okr9lF8=,tag:uG4iCPW7KhIic2ZWnjkjtA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:YiC4bH+chDle,iv:JrwUgXU2wDRAh6f0borE4TrWqjpZyohg0f7AtUYzvD0=,tag:7wv1OP3MC95hAfiDs8v1UQ==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:xSmVluihMEEv0FEVrA==,iv:FcycOCCrxEOO/h+/0RiuC7dTS3ki0Sw3CBTZZ+mbQho=,tag:xdd4yrGh4trlr+9ojv+imw==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:FGnZmT0=,iv:vfSR/itwLpBGs07TUrDUhV9YVRR2Jeyq7sQBg0EewcA=,tag:iwJsRkOMvnDoRSu8sPBY8Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:6R0APHRThXeft1X5b2tnq1xlskYIjKuraeDOgH83VjssM90j0kCBmZbOw1A=,iv:QLLNFzUCRJUkGtuYkVBnLfEvBuKGPQlb+lzkO+hyaxk=,tag:2IStVygIY6k7J1/LRWPbDg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:w65WBaslukvQYSq38mV/FkI/KUJ2nhOVdPY+ZPnr3tBYi7qQl80jR/BpAfc=,iv:IhununeF9Gy4qdM3JBGV/RRSGgLy/ovU8P9jMEYj9io=,tag:Kyv/IDKgqNFh6LPvAG67Gw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:eCay5Nj46tJG9u0=,iv:BtMw3yts/WSAypEjo65GwNmCFp1Jk6PQ60vw7f87JGE=,tag:X4OiE7W2z2F5+/0f/RmB8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTVVCVjJkeUFrb2g2VGVj
            QTRNNmhJSHR3MmNHUmNLVTBhOE1NTkVaYUV3CmFZVVdrVExMZ1lzbUZFT00rQmZJ
            SGNHUEtUVXp2YmN0bmt2YkhIcGlJbncKLS0tIDZzK2NjaU1mbkc4UGlYMERGUVdk
            T2JBc3Z3dXZydk5nU1E2cVl1WklRU2MKDwb8fW8v88w4tVGkinRrCKdzUdmZVrgD
            5+XAD6SfqHO7gdYoobsQru3gz9gy1v2dR+uJ4Xu4H4zeuD0BV9ENoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T02:09:51Z"
    mac: ENC[AES256_GCM,data:nk/mnwq077ID9qpELyF/VRSsWgyJ+OjQaGyEiUzUBugIgFRaLSq4lXApSkoFXzG7oBJ0wvK8+uXkjCPrRZGTtJ0KYWeGe+HguxRaRob0azrOFHtmx1HpHf9NXVHQo6bZ2XY6TyO94JlC6JS94Zxekq3je+FZlDdptS+9FSHCGL4=,iv:1CKvfQYKJVOYRs8MRolk4wq939sCkGg6M63q0spTdIc=,tag:8SpVjVm81X8a4U3D5OwYQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
