apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: custom
    VPN_TYPE: wireguard
    VPN_ENDPOINT_IP: 89.187.183.146
    VPN_ENDPOINT_PORT: "51820"
    WIREGUARD_PRIVATE_KEY: AH44DYHJfXERRqxtd5816Y8J9zjjh05swtffxPLgWUk=
    WIREGUARD_PUBLIC_KEY: VHEKsP+aWtvlhaR1AN8mo1TNOSNJ8knV3kS1vQjN8Rk=
    WIREGUARD_ADDRESSES: 10.5.0.2/32
