apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Hf+E7S2H,iv:XSZRouFyWP7vV3Rb15VrjJCRE27Uh8jlP230cttb618=,tag:2wCQRK9Atcn/eeec/C1iHA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:hIzjPyGzSH7R,iv:gyABKPFUfi3hpF2KnOZoBDoO1EM4gAB7tP9mkf2/i+E=,tag:C1mFZyIAXwmA2+vDEK0eog==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:VPc+FCUtxy0RkEBJPg==,iv:T4iCm7tjHC6VcwyiBZFsFuFLVSz7bMhUMfA16k8HRLQ=,tag:lY9RMfns8zpwB02Fs2VUTw==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:x9R27rM=,iv:SxQfwEcbfCFYax5dKIS19Znb7TynwMpbK4syi1u+k8E=,tag:LLom/S9zoZMec345pjAgiQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:14cMfe/FznCyB044hOUHpgoMa7JuO4p0jrJzMEl8wvhJ6t40cYH5GGqV//I=,iv:6XFk1h51xd3JadeYzSxCP+IEZcPczHSjMQx08stwrSU=,tag:8ZljuUu3ZEReSQ2ZC7V/nw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:+9VwuPXL5IfqWe0+iUSkaP0HYLPNtbTVObJeEUrhiCv+7l7WEcoRH0LJe4Q=,iv:X3ihEflPFVWBtC2gziarvHUL5srBjzWqTKiHiBDXwKw=,tag:c+vhLLR8ZSz8RP33Imc04g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:H/V/3bPccfIBWxk=,iv:QdIqjiZzCM8colBFynaOMu1plYCrqxjEAxCbLt9p9P8=,tag:SDsXoZj6G3ZKBz+cRbpEgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUowNkg5R2NLOTJJem5t
            c2xTaW40L01Fb21iRzU2aGdBdTJDdjI2Y3hjCnAyQTNHY0RRSGFHTENabWx3Tk1W
            cmJNQ3ZmOCtuZ3ZQOU5CVDFjWm1UTGMKLS0tIHdsQ2twUThGZ2tBTE1GdGx3VGNv
            S3BoR21jazN4MlplSi9lSitVQjNXcTgKxCPuaoG61XQKjox4AGGvWBG6GQIaVqdV
            cKn0UCgK7Z6Wf6DTNeLF0VlU3fkJQL422t+Tq0L83cIxYAvIp/bH5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T05:33:22Z"
    mac: ENC[AES256_GCM,data:7YvLifHGWBMy0e7S4RsazkR63IwW/F08SUxlD3OXIriTtktHcLqvw9kd0olJSdeP2rN3q4E9CQ/mSQ3a5jN8e9b0dRg/Qb3H1nVXqQSUFMqmF2Fa4VYUlaltKJeDWLPUCVGNaGs3JNrJETo5/nH7NpE5hd8TGjLUtpNkGKlAfMQ=,iv:TkahImacgfGC4339G3zmbRDJ5/BYu6Law1Im5+l9bHY=,tag:JcFTn0jLMfa3+SaMrGtEiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
