# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    namespace: organizers
type: Opaque
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:EXcu9CynqMsrCp1qohDzq8cBlqUo+JzPS8U4I5Bz3+c=,iv:BQkVXc52wkM+hiCVRBCCMK0kS/1+IArBYxY2faJjqwM=,tag:OR9xZdcOYYOcbXZ/g6jNKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZG9VaG1uM2xjZ0Y4ZVd2
            cCtLZ0srTTBZVTVqcVNHSDk5cVBxYVE1MzJFCjRHRDdxcjVUTk8wcTNXV1FMeTBR
            L3k3L0xZeFdqdlF6UDhyZEJXNDNhVjAKLS0tIE96SUFGSFBSUTdHTWtmdWtHaGlo
            dVBmb2ZQNGxuSk1Ka0RUOGNvQ3VvWjQKj7lTdlyj/GHEkuVCptCZiO5JfHFx6fCG
            vcE+w1edUqWcZGnkfTMRF3/RIAXET3IjHfithkTOQW87C8m27zaovQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T07:06:01Z"
    mac: ENC[AES256_GCM,data:frGtBzluFvlRes0oJzMFIC42GP8jbi9IZfw4p+5xyreye/tjpOdq3cKLNb+vA02OHjHUb5YcU+owy91Hm1iEdYr8r5c49E7PxngAuiABI3Hhq6pML08NT52PlL8Kgct+Ln1dbNAKlo5OpAWyz7sNpJdeNurhb/w3vxDfEUqxGZo=,iv:a10btRRltNxss1PNsnItfvI6utayI8LKECmPWex3xJI=,tag:I2aM/+FNxp0+/2OzFteinw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
