# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: bfbf7c78-0f53-4707-b058-de8c45807c34
  credentials.json: |
    {
      "AccountTag":"712001e692a3a0d43be3f0825e18bd78",
      "TunnelSecret":"8TINW/a+eib9tFQj+75of1canQ562Osk5B8m2lkmwkc=",
      "TunnelID":"bfbf7c78-0f53-4707-b058-de8c45807c34"
    }
