# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:22dyvs4sXdbjGZ6QZz7FGvA5neNO+Cc7Sk3mjDF+dqqNhVKV,iv:kRkLRORoCeEjzAJYDPxu8areAVd2n7yezOHLKHCpDM8=,tag:mbnDN96KA8kLn3DgqvvBMQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:lNEYgxb/3od7KKuk6Alx2PMbxIfgs+N/10vOhhqxcX/zoBvNCxWl2teDJFcc1v4/lAQy2u+oXWaPGptfDYSMirh/RERvLbEIn2V/vOmSDFHCE24iaoOUOwGl5y7mwGpd1B+pOOorNcXlU2dEXkhSrtSELpcc/Gs2U1tf2aMnlimA6KQbEu4dHovepm5kQoTfJjxN2KcVe+NwLccxkC4meuX5BLndxp8jlmqr+gTsOQ==,iv:b5R2eyx0A16pLIAs64TsafofZZPNQlxNAFzW5Q6QQ4o=,tag:ooWzOjTqHtGzlc7QGr+YdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeCtlMVlLQUd0R0k1SDdx
        UDVZOTFBRUh1OGlja0tBV0kwRlFGalAxVWxBCmVacHdyakZCWmJxTWZ0Z3N5RWpw
        YUZKNEtGN3FkWnlBazRGZndOc1o1alkKLS0tIGcwclFUYjNvdHpESnJEQXk3dkVZ
        T0ltZ0xhemNvb1I5TmcrbU1BMklXeXcKJY0dP3yXgOk7/4wvzljJuvUF7Vd/B0k/
        hUM+8Hor9x1x6KRE0Rx07X35CnOsUdv9RIO/HqdYfEb1eaa8Y92iaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:54:27Z"
  mac: ENC[AES256_GCM,data:OVMV0rEvPzDtWDlVcmK7HMe9uvNe9Ulzj6BPCzYYsU16UkQRX+x0CI1Y13nWXpk5immbs9UKzYiytDzwWInDQeAvvEu8DGCEZ6NvGaJMaFjuJsK3O6wAsCk8fECwMplX3X+L44+w4YC5ZRSGK2b5DIreFrxvVK64EjVWiD+rkQQ=,iv:h+ZReNJcLmUMw4AtM5L9eOR5WWyQ632NPbpgLtmgfs0=,tag:LHnodwXAB9eU4GhUOC7gtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
