apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:7XeymC3fjOB3jS4=,iv:0KPwIiq3moZd3K/5jiVhRuZ6xTXXSLDKxJibWGa8nUI=,tag:uGxsA7xFiLaS/oIg1ebFqg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:TEExNeHzRx/IOA==,iv:hIUQI/KRCEh1CvZflKq/BEHoL3YUs4YS5xnw0fj3LGQ=,tag:o7Rz9box3YpMD7zOqn3eJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZHdDV3dmS0l5MUhZcEZq
            ejBPMnllbSs1TFIxRCtBeDkxVnp5ck5mNmpJCkpGbkhxSlhOUEJPbEpPalFBVlBL
            WWpicEJxeGFMTDhkUks3N3pqcG43Zm8KLS0tIFFKY3lTQytkN1lqTkNPZ2lhQWdz
            TndQa0t2Rnc0dzZIYjZuTGI4MHRlVE0KUEFvsr+BD3rqSsLs8VEfqILaXtGwef37
            BNZkWR6ZTRFFM0RoeDs5RMbMVWvopTt/x5dipDYZR2R+FQdRk9J+dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T06:34:09Z"
    mac: ENC[AES256_GCM,data:b7/WI79A/vYudYVfa1Fmz1plkmw8BwKQtDavLHURsvW542NTgNnVxmcB6heL37m54tkjDWxEkTurLZQhIuUI8zKukEBlX3zVllJyaeT3wXJMw0fshlFC+PeRPyUg7YWp0XX6+LPC+D3mJmG/gL5lzJRZ4mA2PI1rig3rvNn0oio=,iv:7P2nNdJfExmV6GCZp6FYyajncgdbLJconEvSp1KuaQs=,tag:3guFxDbCos9G9YlMTRokuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
