apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: storage
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:/PJXD3oP3VVvt0k=,iv:tVdD3ekWdfmDFdw9FCkVDjl7AFlybLy+LSG7o9cVTe4=,tag:1EqXZWGcyW9MSbyfreTZHg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:CrPOXtPL0eu/JQ==,iv:Ng57Ny0sbCJHOw49WfcNJRegxHieTGvXsQ4+F8mNIjI=,tag:F4Vw24dLgX61jMEPY+doTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUThNaXAzT0ZvblZKMUZC
            WTlnVkFzTUppV2NwZWdiWmpQTkt6RXVMWFZvCk1lWjAyUDFUZGtvOXlFL3IxTTZE
            YjEvRVVWUS9OUjU2cjhNMzhRSXdpVE0KLS0tIEFFbXlHb3dCS096NGs0NzZ6T2lo
            NnZ2em5teWJ6VGNxSVo2K3F1QW56OUkKc2ZyTt3lOdm9nT1MYDOlmRhEFx/qJ9Qh
            K4rVwQtzX1n6ly049wEk4LwZmLBzrmtL1Omuqa2Q7HIfSkvgDf4OZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T17:43:52Z"
    mac: ENC[AES256_GCM,data:aXeXa3ptehAHBucEbA6ScxbfRPB5ubHwY05IX/d3QibqyeGla1ONIuLpizf4iz9txwfYBXs2w3iV4WVxRDBhYVZmrQWApliJP5XteShGcaZEni0xJRh8F9+VCLZJ6M6jFpS++jxL7DzVKxPM1+KiHGaQ+VQC4hGhpYustHJXgBg=,iv:HI8+POA4xqY+lmWsE64YI3VSlAr/L5/hVJ3q6zxwd5M=,tag:V4WTfo/ENKNl6zuAmZVNXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
