apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:L8YM/TKhtPwtsGQ=,iv:39ibrzfM2mkSmzKmEzJerPJsp0jQgVpzPBu0o5y0dNE=,tag:q+q/6m67/mKWIja7SrVW3w==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Qo3eHNFwKc7bLQ==,iv:Y80jHaYRGWu4/sqDeJKG4P3f2r4aZglc3jg4/tusAT4=,tag:kdJD/7U1wwICa2/EyBjRqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaWVjZmNSUitadWFKQjNo
            Uk53aW5mcjZ5MFNhVDJZTC90RlAyS0JLY0hBCmFpaXZoblF6c0dtOUNGNnlRdDc4
            NmdVeHNnZlR4cDdrV2pzOVhjakhOTUEKLS0tIFB1blZsSTRXc1loZUtyQytNWmxh
            L3N1a2IreURpaGZYb0VXTjJubC9lWG8K1XHVwPUS7+JaP9QERNuD7YZ4l73gDzg3
            9HMee0SzDxJJEiSdAPLiQxxWgcVZt5SYGa48QIfpxyLX86d4uPY7rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T16:48:20Z"
    mac: ENC[AES256_GCM,data:uqrq8KF8F9f5pxOiLHlgJarRBzs6jIOhff+dJrjh9xj84jGl0hskt0ZRTNbC9s45ZncA3oYq6EQv15+BDE4HRZtLCOA+kDrVwH/H6G9aeiiX/e+6R92zdlWOSiwEm3zRXU+3ZTz+8h7+Q9C16KeO7JiC9XcyCpllxb8oEX2gY+E=,iv:5L7P082jyYNnoo2yQTqs9Kqj+Eo71XLaAOoGLklRAxs=,tag:SeZxLvYYU+pBtsOdC73IOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
