# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:bOqIBulQGA/H2BKaAtlC8goEzmiBDTKwgnY6aQTqMQo=,iv:eJ/tEwVEbw5qCD4vjfTqf/N2k2wVLsIBwxHUEPnQuVM=,tag:0uj2aDF8eI4caoXxaYZ9sg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcUlXOVBJT0RlMFdqUGVZ
        bGxTNVZESndML0dpdU1QT1J4cU5CQy9Cb0g0CktJUnhFankxWThCaE01S0NRTHNr
        ZXczVmpIVCs1UjhXbGx2RmFIdVdXc3MKLS0tIE55TjMzcG1JdENjdVJkSVQrVEdn
        UjFzd0pXa3ZqaFhVbHd5bTVsQzBUTlEKUUTdyAKZtt6C/M9Iu4+ZEF3g1YoC4SI5
        069wa/Pi383p7omG11k8t6ZUHWlBK+nD4xWTlugrc5BSbFtYsb0DWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:54:27Z"
  mac: ENC[AES256_GCM,data:tHY6O6+Dk+yMBvrr3xZljYvFhT07zzi7Ap99No2gU00pPnLM72SCSIUE/9LsWrFX4/sCbCQPaMyDRO0GGzXFkQVzaMhzU+mIRvUCyNv9B1MJaazr5jP9xoJYQOVFCPGPvVgXXkQwRNCQhUdac+dv9cEBjZV+rYX6B0Jz3tApWXA=,iv:vfEkuelvmfMSv/KwlS2jUaFx944b7xKV23Wc6XDSMlc=,tag:3zqebnJlGrzXPAX7hhb2Ow==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
