# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:4MXUE2SkNsLdV69VcsMyZea5wrQ1fLpodTbOJueNN90=,iv:cBkdXBMHFrI39ukwHH1AGZpVQrbHivDRAlug4ERUp8A=,tag:RpD0LfXRRIKClUTRZEs8sQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaTlvb3ZHS2h4elVvek9t
        d2VXdktiekZmQnZaR1FrclExSWw0OG9KWlRFCnhla1E4RmNNa21IdWptcWF2Z1Bq
        RHprWVdKWk9YTUgvMkd4SWRKeHZQVDgKLS0tIGtQMFpQY0ljR0pyaUxQb0FCOUtN
        dXJid09RK0tTbTIrc3lQSTVXZWVLeE0KoRnVxw8JtJS6FbNaByAfMPgm4AeVvZxB
        r2Jt6kzberrKED3M1uXpWAFMaO8IZa21zgeUF1AxidG1H1CD/wQHZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:25:29Z"
  mac: ENC[AES256_GCM,data:EzXqTgk7TjU+rnFSDhSgjC74ntYelbOzqhVtbt1ZmKA+C34zWoAiOQRHb2jeANygKMX1aZWBogsYoxLlHtet15gw5e56MOPadIWfp+Jt5PGgQjyi+Zv67w0tNBphbIyZ01XzSiR9K7piIfsCfLi8BYjGHsGZ7+nH/5B7NKWOUVY=,iv:trtmt5obMIBBOPALGLzhXa7XXNcZ064K6brar3PSjis=,tag:j/96025s8wFP3sda2YzM0w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
