# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OcyucAyYEkU1Z6RjeCJREpK9fzkbzqTnh+7YsplUl0s=,iv:G+AkkMNtUJhXLRGRzvD3Qa0FmlqR0EShIp54Jtv4G8U=,tag:9pkGHomB49aCLI6Sv9ZSfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSWZ4aUdsZkpFdlFiWkcz
        aUE0ZTZtSzM3bmdURm82bzA2a1hnZFBNMkdrCkxLbEJyRGtUZWZlcUtFNDdRdVEv
        QXN3R3JqL21FMDkrS3BnTUZqdG5wVE0KLS0tIDV2bjFJYUpUbHI3eFlPanJjQzg0
        bDZaNGtXZGljK2RkaXAvUnp2VEFxamMKY2dcgyVzi1PHeLUrdGvTLkQUJ6HSKTzk
        58ah8iH7Wgk7UUf8kmWMv2A4sNS0YJnT9qSc4EMqXuvPQZavhn0iRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T03:36:45Z"
  mac: ENC[AES256_GCM,data:cF5CNQSf+fQF3394nFsetkGeRByjqDI/8u0Cn1Aw5s7TC3pYzX20w91Lxd9ByAIcpyjJQgNfmg/QqTbaN+XdEslPG+1LaPSmoxWGmPoomtgKgWFTDOnDLk33LONoRGB0FQEuvarj+WvkBSoJZhfal8vcGo2NN/emlN1wxoND7jk=,iv:BCLCCFNrLatF6UdplW7Hjbv6UcaWPS3R0i5O4o3wgzQ=,tag:AI9HFr62XsVVsZIYxzyi7g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
