# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:A1cQBFIBWOur97uujX9eVNqRNYxzLagjZYVPuM2cHA0=,iv:32ob8dKA8L1dJAhDZSiKPkISkduGuT3/7YbBwE2KU3s=,tag:G63vGzSj/CoFJdqtwwNEuQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNDV5VU11bmVuQWdiUm5G
        d01xTUthYTRIcnAyZjlYY0EzbmdJYU5CNG40CjRaZkFKZEtLdEpZeWpFbk80TjJR
        VERoU3V4SWlCNlk4MFVCajVhUkJTbEkKLS0tIGl5eHF0SjNIUTlhaEk0T1kvNERG
        akZubDFXZlF4MUx1VStuSmgvV3Q1ZFUKyHs1YQTIT5k32csdR4GmCI209Mvba7/6
        XypI/+l6a05uJ2/YMR3wH4TgkttOYCfXYOzqpJ+N9LTWMn3AxGJ3Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T03:09:17Z"
  mac: ENC[AES256_GCM,data:D0VkLNy54ftIDaqbqx1T8484B1SeaZ5RJruad0TRaBpU9bgiF7r1/6IGmUj9dq/aTlQHpHrwRhlIjRpF4VIctnRHrjoUqVmSGMW8JitxDLOcMyIZO+RUuAgZ0ti0elbbppt8YjHUGS88woZx5FJq1Lm8GQ2f6WrKZET+MIJ+liw=,iv:h+b55aKOwqELWRbtkbSHjXibCotqx8ohwVwI/d0cbdo=,tag:3GXsdKpBpqgacLdUHOHzNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
