---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-nfs
spec:
  storageClassName: tubearchivist-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER}
    path: /volume1/kubernetes/App/TubeArchivist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-nfs
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: tubearchivist-nfs
  resources:
    requests:
      storage: 1Mi
