---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-dockercred-secrets
  annotations:
    policies.kyverno.io/title: Sync Docker regcred Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will copy a Secret called `regcred` which
      exists in the `default` Namespace to new Namespaces when they are
      created. It will also push updates to the copied Secrets should the
      source Secret be changed.
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: sync-dockercred-secret
      match:
        resources:
          kinds:
            - Namespace
      exclude:
        resources:
          namespaces:
            - default
      generate:
        apiVersion: v1
        kind: Secret
        name: regcred
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: default
          name: regcred
