# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QPoV0k90WkdDNYOYw3wQGjUJyh9muA1S+efrtOdHwLb8KmQ6xMe3qg==,iv:rb+3RP9hgg7maCay8IW2FosVxoU1lIF+VD9uEYw5vdI=,tag:QrGckQV00JG0ZQq/LAvZXw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbENBbm9ScjcvRTBqMHcx
        WWxDZTh0VmxpZUx6bzFWbTMwQXZ0Qm9ZOUNBCjhXQ2lWejdxa0w1NmtzR0lkL1R6
        UEpuT3BiQVhoQ1BQUFVzOWZBamJOZ3cKLS0tIDBYRWpPUm0wbkJ0L1VEK1N5dUU5
        ZDhPZFdueVVOKzdQdGQwSDNCWjc0N3MKE7wkKQOM8nDBUVbL0Vy7cc3NPamRhW/l
        PpHcAOQSSZY9vxW0GBdaMpqcDbn5mpLVs26v6To6G/Mqoi3R95bUIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:54:27Z"
  mac: ENC[AES256_GCM,data:Kury0yCT5lvnEnxSWFA960G//slndvPs/IQ6CMrhwQ3plB88q47+e6z1WXmwpES2sJ63uLy4C5Gl2juy0OjP32MrJHLwVUkZBCJ250MbGjGi06n2ypvmxP1ZnU0Gg3fEV1RkMoLOmP8qWD35S/M+uSHzb2qbshmcD4DfVbib2rY=,iv:oT9oAyYTV7E7iaD/9alijBB6bx9BnbzXDUnZ0ycYw/E=,tag:f/ba5bwX/ZxUxXl2cmmyaw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
