# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sT2Md6sns91jeLSzre7sgcC6H3JpvRl/c6PMngBlJfy399tDtvhvgQ==,iv:HbSxeul6KdYPf+sEKh5eF3xDJwPzgV4Wcby63RROQIg=,tag:gY2h5yeGs8WXq1EkzyUWSg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZncrczhxckpSbHpxcFg2
        by84K0g3Q0tqNnJyUmQxbnJZTWZiR1hPa0h3CnYreXQ3ZVcyWG1haURzekdQUWlU
        dit5RG11SUNQK3RvdERIWHl0RWdzbEUKLS0tIDBCdjVmRDhrNWRZbFlNMXlBSjlK
        RiszWlRaRWpzMUlySmorYXFzSy9oeE0K4Z2wmVXGFt/5GFFvi8q3mT1/7TvUXbDs
        kt2dT7hfKqVujj8xCDo7p+qi6xDvQkcDkadYklC4jarSlofYriGi0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:25:29Z"
  mac: ENC[AES256_GCM,data:1lzFv1TzsnnZHvaiQo24vlZQqS7N5bY5pfhECtEv4akO2yXwNq49sGv544+2lxULTWvteD7HJ80L/hAxAnxPnJUwzvTEjr2b9UDZwcW6/CM5GIL9UJ8xC6rG5jd7T7Z3itXacAFp7YXxR+jXuGO3m3mvRZaxKKNuBioRbHk1I5M=,iv:nueA9Ludls7Dv03fWwsLpqHZGjzWY/cc9fCrbGcMaGI=,tag:ukMWVMWmR60yLwe2dAZLcg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
