# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pSxj3WNtjTpqAXT9EiNQARJ/RiKX+3fLN5fkcz8nf2TuJ72fTbypZQ==,iv:A0PPioPKB5yt1WzfZm4zK4nUZFreT1qcxumVFBf6rjI=,tag:RCG7ajDngksUfeR2zx+uKg==,type:str]
sops:
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OHVhZ3o4eEdUZXY2RHJv
        VlBNZWlYRTBSZEZ5OG50VDRTTTRrUGhwNjJVCmFjUmxOa3Y0VmtPVkQ3K1lJNnJQ
        Yk9tS3B2aDF3dlpHTlJPemxHNFZBYXcKLS0tIFk1SXcrMUJ5VGE0SGZGOE5BOEZR
        b2d3cnBiMXE2NjZocU5PYlI3T0xpb0EKjRqlNnDFG12mTPlepE4wWMn96RO6kgwo
        E12LakWbiYv6IOpuU72qPPa9gcM7R0KcT9WIEkmXGY/qX3/SrEAhzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T16:57:19Z"
  mac: ENC[AES256_GCM,data:wr25A2/hSlFuWj3evmgAfZU4SnT8rTtdRr1hHwLyLrCINqPbtbgcPbYXKBBpOln9LLsIax4ujLED4gZs0VTj2Ob29HNVauS+fdjD7oZRbXJBdoRfBlnWI3Rx2foCTX4Oi+5i5ZdEvYobW2AXdigzDsi6tgAkw8Mc+0rZiOn2vDg=,iv:G7QSrkDpYKRnmBwGQ7tjsiZHxexA+IaDkVQpGzGk9Lk=,tag:iaIBk7BKA4jvFtvuiybC3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
