apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:jlaFXAxDW9g=,iv:kPZzGfnekT1OQ4z2TQx72yas9M1vZ1ETRF0Fsv8VGig=,tag:bNes+x0i3MlMPEjojOZMwA==,type:str]
    password: ENC[AES256_GCM,data:xKdsito5NhA=,iv:cwv5UaTD+WJIBPNy2gGmbFXTwXh+YQYA/L9rFe6xyMA=,tag:JDpu60OSxd2KEqY9owm6lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaWVRNS91QXpLMjFQQzB6
            N295ZWtZK0Y0clZIYjdwRFY2dnpxa1dET25rCjdBMmdoZFlTR3BWQm1FeS9WYkcr
            UGNYL1MxR1p6anV4WmsyVjAvR1BtSFEKLS0tIEhEYmVWMGd0QVp5ZmpCRFdFWDI4
            NE5tUitFMUd2QmFrb2VFSFB4SWRBZFkKtO9is0SYOpZ0xEQzdoNZe/l2uBLiFLBW
            GXwcPa1sx+aP7GcovQjN/LiGabwowoDy7vD8qR0EIzyp8R+LN5nbBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T05:19:42Z"
    mac: ENC[AES256_GCM,data:x71C0dM+DdJn6C75cYJxlu2++XqKF6Hi/i7zQ8f9z+00Ajkb8tq9YOAfO10g7IMJnrFQzJC/0kCfUEhpNx5+WAvLIpi9u+wk//thUjSjYfy0DKsomYpKD8Ri2zUH+zE740Vfkw6Id2No0YXsNTH0vcQQ8/HImhRqI57wjZJhkDk=,iv:/t8M4/37to2KaFhdcLp7x2nMXLI349ww9jX+SXTZheg=,tag:VxCoazorH49qIxCFnVoR8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:7XqkvjqrXSTb9NoXiIiuxw==,iv:3/aeDO6cQLd1xMrNcHkn04UwXTcRJwDe2X0Bdmc/Sj0=,tag:qXNQ2JNXdIp7Gt3PxNIPqQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Om3nHA9f5rVsaAN6ijwUCL/WGGdLhXd98vFN5uFEm1Y=,iv:TknURr1GiUVZGSEjNWTrslC+Bkxb2IXEDpKn9t5F0yo=,tag:htl+jLVWpSlK0+pqmJ7cSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaWVRNS91QXpLMjFQQzB6
            N295ZWtZK0Y0clZIYjdwRFY2dnpxa1dET25rCjdBMmdoZFlTR3BWQm1FeS9WYkcr
            UGNYL1MxR1p6anV4WmsyVjAvR1BtSFEKLS0tIEhEYmVWMGd0QVp5ZmpCRFdFWDI4
            NE5tUitFMUd2QmFrb2VFSFB4SWRBZFkKtO9is0SYOpZ0xEQzdoNZe/l2uBLiFLBW
            GXwcPa1sx+aP7GcovQjN/LiGabwowoDy7vD8qR0EIzyp8R+LN5nbBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T05:19:42Z"
    mac: ENC[AES256_GCM,data:x71C0dM+DdJn6C75cYJxlu2++XqKF6Hi/i7zQ8f9z+00Ajkb8tq9YOAfO10g7IMJnrFQzJC/0kCfUEhpNx5+WAvLIpi9u+wk//thUjSjYfy0DKsomYpKD8Ri2zUH+zE740Vfkw6Id2No0YXsNTH0vcQQ8/HImhRqI57wjZJhkDk=,iv:/t8M4/37to2KaFhdcLp7x2nMXLI349ww9jX+SXTZheg=,tag:VxCoazorH49qIxCFnVoR8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
