kind: ENC[AES256_GCM,data:hEYklBWc,iv:KtokqpurNV12jrtrkVfp85YhzZn9oW2a/BJS5y/XRvg=,tag:34oSKZFdsbshPZCPHzo5KA==,type:str]
ansible_user: ENC[AES256_GCM,data:f0JmcQ0=,iv:H1GpvHcr3Ryxxo0DHoc2MN6Ga+75WctM+KFO4hHInBI=,tag:TiSRfc5CU5gNa+QSe2yoYg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Z0cSoQjiBCw=,iv:nsJPa0OU6xoUflI3/sUKvQR3cFW2eh8kScPQV68dduQ=,tag:F2gqite5sIWTYQ+LPyhBeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYk9mdDVSdXpXZFZUdUVD
            WGdkT3dIZjd6KzR2YzBzWGhiZ2d2YzdXTGswCmpRZFlKcHphNGRSc1h1QkVPN1NR
            eStyVTV5SzdqQmxEMndEc0VBTWpUVlEKLS0tIE9aczZVT0JQcnkyN083ZkVaWWdL
            SEVjbk85ZFUzVlZwYUV1VG0vRjdKbFEKwD+YQzsOtKJPQjkV2qAx7AhTUw7uczPI
            AM1NPkjW0JEFmC5uBSFgGPMa8ZWKnwtoVcIF+562oBs0Iw4Sh08egQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:sVe70RHnS0E6DvR5j43/v9twpauZR8+m6HvvfxdAyQbUQD9CSssMMlWwBOdvHZAksxv5h/z5ky0vIrXqiPejRAvTBuA4sQUPlc0Sgfg3qNCSomu3Ftk1xIX33xTIK9tRfJzW+M1LZwzPMvjuePOfsUILpWRjwZPAgJ6yM75PLlc=,iv:l/8+8lctrjR+bDHArNQB4RNcNj/8s75p2tLCAofweCs=,tag:B+CRqV/MQSYWBfHu/fVGmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
