kind: ENC[AES256_GCM,data:vszh8zZA,iv:7tIzwomsQozySC50wWvdQ88ZNO2W3O4MtNsq9AtFAFs=,tag:kbJxxzwsR2VuYnQeyKwxQQ==,type:str]
ansible_user: ENC[AES256_GCM,data:qCovV5s=,iv:rIDgi/AltNQL4Y/Jm3iUhY6gzDMJy58BrOQSbsyouUg=,tag:EfsDn144zSXEbJeweln5yQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NFa3KFDtO34=,iv:Q1OS2HQPAJSN4bSi9g4EqXwzhRUZhcWxZ3ExqLgY6KM=,tag:el/T3zEzjNotuenAbCbbzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc1UxaHhoamhYbjRhSjlz
            Ny9BdTdDWlVsQVV1TnUzZW9wZWlueHZVMFE4CmdGZWcyZEFlT25RTjhFM08rNnlS
            VUZBWHFuT3ROY1Q2bzFUdno4VDZuUVUKLS0tIERaUlRTajZ0VWJXQlZWK3JHVlRa
            TFZxYUVaeW9hdldDWlkxVUdXVXo1RGsK3T1jVx74wBQBe3zWB/+YeuYPxsoXyk6c
            hoti7Z2MZgG2e4am0/CxMDi+cBRGMBSlUTFxTA50v9TJ/i1LvYGi2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:saCfrluKlet2/EK/El9HMKnBuM4ElN0oTSC0fMAKMZhd9dzhIS/ZpSTCSck6M+NvkvVIRTYSSJWwnl0InTv3m70GJo6v5Xi9/EiipBew3ssJSuScfi/D1vx14Y8EeN3QSF8oK4cW5L2Mjvhtf2P2wDO1SKWtJeVlCrfOLPpkdeM=,iv:JQwKmWTRqmSY5aNT4L/d3V0agYDf+e4mE2/wXmrrYIo=,tag:B8ItYGAzSmjdO271EEVqkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
