kind: ENC[AES256_GCM,data:Po7LnA8Q,iv:ws3Ucx00uf4sHtdM6MCwkXsDSeKnNC0ZeIrLjZyOq2s=,tag:JBD1H1TwVPoyotmA6Y8dRw==,type:str]
ansible_user: ENC[AES256_GCM,data:narvcZI=,iv:lmN9Q3yLcYM859+pOzATjczDyYMNatHsiPwf9/dWhrk=,tag:RMMqOOfkIc/kp9S8kSry1w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Yu9J47816q4=,iv:aJ//9qmBz7FuAZKwRnBEPhrZJ15pMvgz2fSM7Z2kI3c=,tag:t9dYMa0iZ9pgUkZu7y4Irw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzalhjUnIrMU8rVFliUVla
            WHdsR3JQWE1xUmVwM29WYVpBZkpNVVdTTUh3ClFZSmVDWnJZSjR2bnhjUUxQTmpD
            bi9KL21xakRpc3QvVDZiZXhZRE1sMlEKLS0tIHhEYmZJcmo1aVhPaUk3V204Q0hG
            MVBBbm1qR01tV04zRUpXRWVxNjZUY2sKQFZbqicwYjc/cZBvRmfef5bvXt71Ubhe
            85/IPYsJgNImfJSqq+C0xpq+MkRVSSJNn2nBI7j70GSbhL9sZdLQgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:G7UC9QsbAAhuUb9aPDIcemm3jIyDY0ZPQF9kJkn7x1gG/JPAOfoGhXauk4N9i381mnE+z7PcoG+qnUrVZWQl0rIPGG1J3aVhM7cPAx9k86jvEEAEcn5DVCC8iWGSSB4qTcL702jZHonbE4AZy1Qj/Te9Z05fCY3JerQ12omj9Zw=,iv:gCPXhKCqYVFfSDcHPiP+E5B37LvvFA5sjS3AgYIldyc=,tag:iTWkMtHEn6Q7XazhrRNn3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
