kind: ENC[AES256_GCM,data:f1S4oT7S,iv:PsEhG5slH20nswskgL9rAOrsTg+nmB5cIWy3eWAVbX0=,tag:VWsac1dAn6Yp1o4syN++mQ==,type:str]
ansible_user: ENC[AES256_GCM,data:nxTdziA=,iv:vhknA1DL6nlz063fOoSt4HGIquxo73bCmsIPN424KFY=,tag:de90FkcVV5wxdRc4Dcy8Xg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:H5cpGlrZkjQ=,iv:IUKs91WXjSx9jBzgU8JWjieiLgNqcANWpCUrTXtzskI=,tag:UodmSbt0zQJGsBXuj2NPaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdFYySjU5VWk3SlJXWCtK
            VDFodU5oT25FbEhlREZiaGxjZlVaeHJrL25rCjBKd1hvSFIzK1BFSHllYlRJOWJ0
            RW5xdWl4ZkE3MVpBa2pMaHE4YzNDeU0KLS0tIHpueTdkVDl6TXJnM3Z6ZStGL3Vp
            SWQ2TnBEOTBlcUFaeHNwTlBuRFpUd28KucRJDeunwj9UhdG8cqeBr23LAYv9UevT
            ASow4rYKcPCI3RfDhuJ4OGle4b8liOg2IZUvZcrSQDOwu78kJrU2qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:qZ118C35sKkdUkrh6qkW8hxInb/SfJzY79q14QaozfEL/kTzDTVM9XVQmXf2X/RcB/Zdnv0vOXSx0QO+gtqod0u+gSgd/0Tv2GeyPNGI1sFjE0kZoYoKoIoozJpFlXRvkdQn/+iWsH2Rhhg4lP3hHhKDiOjxzgyaHZ/nixryQhU=,iv:w8kTyj5Fs+ADwzYMUJCdEK13z5+ya0E++slbd5NSb7c=,tag:Zq7YoHtgAeCsmRZ1uZZJRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
