kind: ENC[AES256_GCM,data:wxhUfR5v,iv:yyay0yUqVsau/IB85sGhlIcy76I+IRtbvE8AawJF9LI=,tag:eCU0Ub0pWZZUp2Q5CUd68g==,type:str]
ansible_user: ENC[AES256_GCM,data:Y4aCTNE=,iv:k3GucH13W63ZJwIl8cnTObRtZyvFufwhxfrWjSUzcL0=,tag:JvuM5etuTgpqWKHizQJsXg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:izRd2kULLEQ=,iv:LdI+dTWJmwawGbUMjypMC8bSJnZwmZuSoREk55+0ftM=,tag:nXlm1/LKQBnYAhl+NSgFKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQzNNbzN2YkVZZ0Z2MlQw
            ajVaaEtCR0pJallwc3gyKzcvNlBzUHpWVURNCmw2eENKekY1QXRENE9RODlhMERl
            OXdGZkU4eE8wZkwySDRmbW1kNGI3Nm8KLS0tIDRLVjhNZU1acGY2ZzFFbDJyakR3
            QTlaVk1teTErNmZ1TEROaEo0Vm83Y2sKo3GLiu/2XJDTrYTaLvbEpegz8q4dzAOl
            gvUTKFX6jR6OYxMlxDPY9tTW2panASZLjLxaMeuED+4m/2AuQ/4egg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:+Zhr3JqozVJ6VUUuGNub5q8Getmod1XPPam9uenwsUYD8g18tHbl01kgFG8IiFSkrZMvKTXYhya5uMpGD1UVRLUB6WCE/+wQx77Z2Tq8+U+c8eiaaoMxHS9E4IPUfwLq9QJqBJI3RFFUgPZAVnnh+NssJIuKgxOoqJALpPORljQ=,iv:hH+6gQd4w+stwpoLTkIRZ2MbpbmyKo3cSaWQCeOFtFY=,tag:woD2sZ+Oznnt4xTFotCSLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
