kind: ENC[AES256_GCM,data:n1gvsiNe,iv:ovXPmNW56BXikCEt3vJmSCOHhM3mXpHPqOGXfmCg8js=,tag:+Rp3p0qXvL/DtNqnys5bSQ==,type:str]
ansible_user: ENC[AES256_GCM,data:JitPCsU=,iv:r8ezznn0xuKBciw0e2YcQ1TZi7vGumU+0lP2Lh1ZARU=,tag:LVs31X+gAkF44jkMynRJ2g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ru1ywLD3bDg=,iv:M6rHRr61ebqJ2cvaieaZk5XvPW72sw2gVZggV8WF3fw=,tag:SQAXARi90apu/qiT2gnCCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TERWd1h5Zk1NQ2g5M2NE
            RlNCVFYwUU56aE9ISEkzRk1OdUVUT0hGVzJVCkJUc1JBL3ZTYXZadkVWRDhoZlly
            eHltUm9hQmY4SVAvVVdDcmM4SEt6V00KLS0tIFJOT0hnT2Q1VndOL2lYY1N1V1VE
            RVczMGdHMXpRUWI3bFA2TnYzSVd0S2MKORFY1ZwH0x7MPyB42tU8GgOerSe/QR2K
            zcAqMRVGiyZMrd/v+PsaHXx4O8aMS/gr72+wxzygJOsEvzE/UY6lBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:dTVbbY5CTEvo61NEWX+VsLR6RjAzMtnST6+sHiQK9+wZKKd0k8gEWGtQDCRiXkqtBJX0Sy/3J6NONqjZEbyjUfItCDzA9X1qr1fDt0TVZyCmvtEhYg3Wdvfj1xuhP6d1HGCCXyrwuqE0wgoQDS+hZXrmPKzQ1OlXDtPdLdObttI=,iv:NNTpwCPPP78+SxPpbMSub18b9HmDlQHba79lPgzRH10=,tag:4aYBVBwJBnBP/8MrTEWiHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
