kind: ENC[AES256_GCM,data:jJrwEtTi,iv:3vGwKp4AcQjV/kcUfv4JHwjcXkhYZv8NrV6nCtodBhg=,tag:/9gRv9FTrJAs51laVMcbzw==,type:str]
ansible_user: ENC[AES256_GCM,data:b2XQEK0=,iv:j0zoGZA4bUio9sz1xIFwAY53QLHH2P58sm72ptXifj0=,tag:MAokDcSpmghUEp8zFX625w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ktut5VSBEKE=,iv:IxKJsDbjiAMqooHqovUG9NypqsdLOBUW/2raoS3o4I8=,tag:xCH4S22B754EyE5Op0Shiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SElaQlUvMSt4N0t6WDBD
            VlhTZnhPWURhWER5NlU1anRZaTYvWEo4blJNCndSR0RjQkdDZGZxRFZSQXptbEwz
            NHZxVVgxQlh2dngwdHl0NlVoQWQ0Z2MKLS0tIGh6WjRxRmRkUTBRNytYdncrRFhp
            Z1JSRmFKY1hsQ1JJNDVNek1rKzJUTVEKT8BTIeFNi1vzUHDTgrCWqZhGUqHlYTMr
            XB2CAy0r9BGjhtatIYGi5SaOwZ63Kl+fwmGaf1zIGWb9md8rG3VchA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:XVO2fSm5r55YJV8Abwk6AbOjsqiBRLsmQQ+UcJc1Z8O/ds7y6Ujz9WWSI9kNtSlxG60B+eIoLcAIx1bdURCwMRH73uTdBFuMprysU50pV2VWlCVwGFgOthEipMFilSgaQu8eYytGtiI87asQZFL+OS1oJcCFQdWwfaEhQJve+e0=,iv:ceEDTjhvMbbMC22YOJDDVpR1kIwVFgpL7DGPYSFR7sg=,tag:N6evxzhDHO+6+yEp/MfQWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
