kind: ENC[AES256_GCM,data:6yUEQ0CL,iv:LLKqsRzCmrM7kuGpjf2v7fTPMJZ3jVKfu25M1p3Tbqc=,tag:80jcC62rsCNasf+XY2OACg==,type:str]
ansible_user: ENC[AES256_GCM,data:eEMJAeo=,iv:zCJ4H4hl5TGkChSf2lFfqALKuhs/yyUE14k9Beg62xU=,tag:HFprJ061hJx/JyeZr2TxlA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5BtA7s3e33w=,iv:OxyOOhcCxLU3G7EvnKqCZCn5EIDQa/ZtFLS9KWdE3VI=,tag:HAJmSGhWVi9P5wbOir0DIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2NRNWRHQW9DRS81M1lR
            bmJIRi9sbGplVFRTTG1PTElySU54VTNXNDNRCkVWWXJiMWttb29sNXNhRndmYzVX
            ZFdLbUVUWVJBbnJLNkhBQVhFd1VndzAKLS0tIHJ3NmN6WTRFOS9pNVhsMkt1UzFk
            NlBlSm5mNnFocUpVWmQ3dnByam1iM1UK3B9bikYBSjN+r72aIZTkv/faiIOXrGFz
            OuBauYgaV9rwiEiJQSf4Qh3tyDw89Rx6LXLOBUeBlMU9jlzpoVtY5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:Xh9AR8eV7TzEtExqLdI5AYXBfl8JYIGpUU6ahZDKkmnog7Xj5eA+q+xgQ27uOkfzc0WvMrwTEb+nByaGqNDuG8EGfdzZyhQcA/GHk/D7xyiAbIxM5ZsIMu329uVpW5M4YTGtsIPdocvqQaB7IfoS8N3+w2mEzFk6CuTX9qFnvgU=,iv:MlJTr2NfHSf4WdU2XyO4mpNdozmuHglo68FE8IkslJM=,tag:L8gRkt4NUfM8L2uEaV52JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
