---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./dandydeveloper-charts.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./influxdata.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-at-home-charts.yaml
  - ./k8s-gateway.yaml
  - ./kured.yaml
  - ./kyverno.yaml
  - ./longhorn.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./nfs.yaml
  - ./nfs-csi.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./synology-csi.yaml
  - ./weave-gitops.yaml
