---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ../../../../templates/gatus/guarded
commonLabels:
  app.kubernetes.io/name: mylar
  app.kubernetes.io/instance: mylar
