# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mylar
    namespace: organizers
type: Opaque
stringData:
    MYLAR__API_KEY: ENC[AES256_GCM,data:3ib3MjFDxNhNURply0ozXudcyp1WHPq7cvtdX0pkFnM=,iv:e/uX6a6PEIyAj8KYTfTpeigcn0GDVns1fBKvogaG0Gw=,tag:RiL0Go9sSHBZeYZRbwafuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT0JoVXA2VXQ4T1ZNZXht
            UHd2Z1poMWM0Z3cxbytsdWtveS9jeWVEeGtvCmdBWXYveUxRNWw4dmFLdVd0clpN
            THI3aENlQnpBclE5N2gwOE8rUTQ5T0UKLS0tIC9DNTdzbHBLNzhqS0Q2bnFNYnhX
            Wmw3ck9wNFNDUEdhV05oSE5oYWZreHcKX9JnvAK8Y7pTuEDCqydV24ihbhyChKE2
            3IdIMUvZP4oSpySBhabMflXmLZ6a3/eeBFlNs2/Nq2XXfssGehxKCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T07:02:20Z"
    mac: ENC[AES256_GCM,data:NYFouZVuwhMUON7/PWmwF7vBBni2ohwFMh79F0U/0E+ZxmkN8eR+30WaI2yEqZRyC0WVHLhJmLFD/TjdziVDWnizEt4TMR0KJTe4DxNWrl+Kd4cbauT/Qfqa1zbSQIm5otLTDIvCSQ0n72rL/ieBtTBwy772srQmMJaRmDUYLwc=,iv:Z28Ne6RGiLBfu8zG2gEqf2dz9sqzr/JpvMdh+Hxxkks=,tag:rvXGjKUR9nQE9RIGxSUZtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
