apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MzToT5NJw961LqUe/rzhrwMW7FqmAJec7Mmerzqh+O0AZxowiE/jYQ==,iv:qTo550pI1AeyMmrGpcUj4ybWnBqjgv6W2hGxFrNWmcc=,tag:vVIjjdjRz6G2tlDFEdNuEQ==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWhkMlowSzNBQjcxcUFo
        M2ZCTzdhYldoTFFNYWVubEJGL0dUby9HajE0ClVid3J6NjNYSDFocWJTYXVtS3JV
        c2hZdVRDRVN2NngrS3BqcnB6QmVWREEKLS0tIE5NeXMvYW1GcVN6V2x5NFRMUHlH
        NzUwMXJ1TTlSKzZLaXZxbXpNdU1DZGsKhNRzXmsn3FtiXNc7BpUTr6Sa1keYSqfa
        HbNOX5RJtuSWk7L7RW/kspHowzWSZ9MhYOgRZ8ViH41dXh/LQ7ooAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:18:06Z"
  mac: ENC[AES256_GCM,data:Rl17dBlQajD35MQ1sjbDY/wdd5ft4UUiCTCXY7uUdElEyCgFejA2oJLKqbpwoK3XAY4iV8rEcxKmGbSq9lYLfwXTfVtmUTQQoJs5PiIzROUboDmLjiHU5WC2UEK4Ip1yRsF+NgVqlzNF9nCeptTBYXzr3A5JFXSjFlW4azOseIs=,iv:bFiYMXjzPL1QOfIcLVRN0kjwwCbJ4zYCKHZak86xzJ8=,tag:5xUWQVqO6JVNTvhcFFLCTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
