apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:2ftokE76krU=,iv:VBxn8CgyDkuoHqFepmvuE/e99v6C2BbwPkYXPxiM9uY=,tag:s8667MToL2d1eZtFJjaEpQ==,type:str]
    password: ENC[AES256_GCM,data:/Lk30WnfA4o=,iv:iAqzmqYufNXxIPj87NRpirxkiNRx5vMW+PI7lKOY0Cs=,tag:1ORR6PnNj9MiPl24YZzCpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUpLRVdxQ1BUaHZleW9F
            ZkxWRHI4akhiY3RnMHN5OTFaajBTeDVoSlE4ClRaQ09vTFA1TTdSMFhIdVVZUW44
            ek9GZUxNY1UrZVN6ekVLV05KbU5ZNXMKLS0tIEMzYzdsNUtzT2NPeFdON1l0QWVD
            WGQ0cWJaQUZEbnRkNnU5YjhQcGxudVkK7Fkgz7y7eqyffNSpMyw2nsLdLXJdUv2g
            Y79T1iW0WlhgESA+mt/U0Sxm4hPfrUJ6MYTY09BCXDKhD18q3mcZwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:04:07Z"
    mac: ENC[AES256_GCM,data:GEMGoukii94wUu9bunyHJVeruMiyTJdVbu+nE0AG0PRLbh6SLMA0wTZBRLsgRVZ+LK+Ojq3nJwHxjoYDIZPxnUn77OIan3pGzENngrV39tCXVz+9CNa4mNXvwxmH87i/lfyRPBlj9XUmG9gv9ZuEB28TX9ensO8BekxF/s7AYfw=,iv:CmYTKkKA9gUgD5IhoDuDkxv6oT9nRwM+MWXfflIR7v8=,tag:lacE1XIcB9Ayk4ZaMRaRTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:PzS0oQlboni8NOCzWaBTZg==,iv:tBNNKPenf0BChX/uh5tPoCEIYYl4yemjX7h2Vx4tzkc=,tag:1M5xAuNbAptCPX+11YQsaA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:zTMfD2ZCG4Z+uTTeqavr/8+u3wxE66kK7s8SqYFX9Dc=,iv:fWbTlvWIN/32ZRaJKnp/65qhpkxqVlQOUe7j2cPuDLo=,tag:GGCPpJJWfCve6d4G4DqQIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUpLRVdxQ1BUaHZleW9F
            ZkxWRHI4akhiY3RnMHN5OTFaajBTeDVoSlE4ClRaQ09vTFA1TTdSMFhIdVVZUW44
            ek9GZUxNY1UrZVN6ekVLV05KbU5ZNXMKLS0tIEMzYzdsNUtzT2NPeFdON1l0QWVD
            WGQ0cWJaQUZEbnRkNnU5YjhQcGxudVkK7Fkgz7y7eqyffNSpMyw2nsLdLXJdUv2g
            Y79T1iW0WlhgESA+mt/U0Sxm4hPfrUJ6MYTY09BCXDKhD18q3mcZwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:04:07Z"
    mac: ENC[AES256_GCM,data:GEMGoukii94wUu9bunyHJVeruMiyTJdVbu+nE0AG0PRLbh6SLMA0wTZBRLsgRVZ+LK+Ojq3nJwHxjoYDIZPxnUn77OIan3pGzENngrV39tCXVz+9CNa4mNXvwxmH87i/lfyRPBlj9XUmG9gv9ZuEB28TX9ensO8BekxF/s7AYfw=,iv:CmYTKkKA9gUgD5IhoDuDkxv6oT9nRwM+MWXfflIR7v8=,tag:lacE1XIcB9Ayk4ZaMRaRTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
