apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:Ta9SArrjqzE=,iv:5SIjGrqog2l1QHXinsfsfwOOX2ANbpdz7p7cpalIveY=,tag:0h18EBnCCXiRIu9FE0Vc9Q==,type:str]
    password: ENC[AES256_GCM,data:du/K/HcFJvs=,iv:lOlBSBZr5RQNqcTNqdjNmLb2B44ptnHvgZpUXxZqXTY=,tag:zBQ1XYC9e5FgDgiZbkbmfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbmxPS2MraGJzTFNIWkpo
            RVVldGcrK1BlMStIS20yOWJIcmhGeHFlRHpvCiswUk1JNFV5Q2FuY0UwYkp1aVBl
            YlJRU0t6VXNpTkRoUkZiTTVzR3BBbXMKLS0tIGUvZEYxNGNHRFIwUkJBcG5rUnIz
            YWVncjB3R3JqRjhPbGpVUDlvQi9aWEEKggpPXAUCZBj3HabwTzdErxflU5kv7iAN
            bevIJaQSs+abfGJ5IQf5RwBTLdzldJerRhQ3p8xLn6OFeaYzfhnfKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T17:59:36Z"
    mac: ENC[AES256_GCM,data:KQ3l2tUG9pjL1VzoMucHn4BHHmwpxySRzvhlI9grqSs+nAaFd4FqD6Ep4MnRtJ7erxsgr/dfW0QBdlJc/s+LZ4xH1UT+H6OtNTmS953KLnNcXyR4KHyj3bxaY2SHAfWkhq0VNaTsCN5sMePETemdcWAzx9siYOmg5nw1JeGeZqo=,iv:yZu0ov6x3EtWwnFwGvyQ71FFMbDF+xeQvRfcAMEcoO4=,tag:uhh8kMgz20+QGd4uZ+vmEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:yVyC8qyufCbRKS+uspXqtQ==,iv:MEYPPhG+pYXc/e/0R2t1/v/Wow9ICdVFHSm6tKCFf3A=,tag:RrQfPblJAtel1YzUqogcEA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:ixDy8cWEGdv4M+5ZmdNWYKR2qeBNpJqebQti4pWUouM=,iv:9EIn0kCnURSaCaZ7Si7r+ONQjvOj0v/YOk4EzSvtk8o=,tag:V8IKaNjldd+SY/U69u/ZoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbmxPS2MraGJzTFNIWkpo
            RVVldGcrK1BlMStIS20yOWJIcmhGeHFlRHpvCiswUk1JNFV5Q2FuY0UwYkp1aVBl
            YlJRU0t6VXNpTkRoUkZiTTVzR3BBbXMKLS0tIGUvZEYxNGNHRFIwUkJBcG5rUnIz
            YWVncjB3R3JqRjhPbGpVUDlvQi9aWEEKggpPXAUCZBj3HabwTzdErxflU5kv7iAN
            bevIJaQSs+abfGJ5IQf5RwBTLdzldJerRhQ3p8xLn6OFeaYzfhnfKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T17:59:36Z"
    mac: ENC[AES256_GCM,data:KQ3l2tUG9pjL1VzoMucHn4BHHmwpxySRzvhlI9grqSs+nAaFd4FqD6Ep4MnRtJ7erxsgr/dfW0QBdlJc/s+LZ4xH1UT+H6OtNTmS953KLnNcXyR4KHyj3bxaY2SHAfWkhq0VNaTsCN5sMePETemdcWAzx9siYOmg5nw1JeGeZqo=,iv:yZu0ov6x3EtWwnFwGvyQ71FFMbDF+xeQvRfcAMEcoO4=,tag:uhh8kMgz20+QGd4uZ+vmEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
