---
apiVersion: kyverno.io/v2beta1
kind: DeletingPolicy
metadata:
  name: cleanup-evicted-pods
spec:
  match:
    any:
    - resources:
        kinds:
        - Pod
    conditions:
      all:
      - key: "{{ @.status.reason }}"
        operator: Equals
        value: "Evicted"
  schedule: "*/5 * * * *"
