apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:njXM6VhpwDA=,iv:G942aPIDMvjwUkmssqgTY3pcH1xiqTnor6B9CCzahYc=,tag:qSgQhtmKQDN6vwECZ+jQjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhKyt2L0Q5S2RyVEFjdHAv
            aXJ1aVQ4bFdzL2RNc2lHVHViL0Q2dGY3VDBFCjNQbXFaV3FadVNBUHJLeTdxZHBU
            dXVqRWtTbzhkUlhmQm1EdXIwMEd5SzQKLS0tIFltTWIxdEhJcW5HMWF0dTN5Mnpq
            MEs4RGJoMTFpWlhIcDJhUXZORWtiUncKVmtVYn//z9T5mMxgHsxOZoqUW1wJRtbH
            W3mph1ZiOrKbCylgvfkfn/IQHaQdX1mCO1aB4f4S2wNBr1sG3SNIFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:ahXL+/rxq6kYwQAQJ6uKXw/rdtisjUtfrz04i1UiYmtLlSG0WQQgfpnuT6KVXPoZV8jXYajOnAIUYZFNg/SZ9T4Lj54IC12yVqN8hCQFCO3+TxAMheWmP6NUElNHd7qaRwYoFfCG4Ight7whPU1fjfeCbQEu+guaoMOp1lZugGY=,iv:hXsywF9kvPbT2x7D4k5a8Doq/en2pJvTlxx0EpRkNFs=,tag:jE5obP7sEwp2SJ2o9uoGsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
