apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ELVctwXXMFg=,iv:gvBpVMcSzSeNBPkm4ab0+4TWGL2ztfPVlzB572q/QLQ=,tag:KQHeKfjQ7f08aHUMFKIBzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNURKRlB1eU8reEF6QzRV
            NThCUXBJN1h3L0ZSRHVDMTB6TnU3REFRV2lBCll0U1dDVDQvU3FQVFh0M1FWREpF
            aGkzSE5CdzEzbGp2YUpzN3BJbnF0SkEKLS0tIEYraHlmanpZb0d5cEVVbHduOWZj
            WkxTS08xK2JGM0Zqd1VVb1pTaVAzSkEKq6crkEEbvziuqfV40fL4iQYH9as96kFz
            zJ33A61xeiS5VLydXctM3YHU/Jf+pOayQ5ZtYGUcfdtklIt6GjLL6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:aaYy9Jfv0n3ZcI0cwriYb6uBSQAHcv6Rql0uYtcN/S3wTYnbnhfhQhx8H8X1j+avhbMUUjcFdGQCFMI03lIWZaV21obtqLVmFaSIN/VPaPih4CCre8Rn/Glysd85NCguRyyD+Qeynd6NB/471pD8dr5BvUZaumrwR+f10p2J1rw=,iv:DI6zVyGjfXhRvBddq+gUb6OW6IJkJbAXrG9JWhg7hcY=,tag:MFAtYmfBcLQ3AXAGPpmHbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
