---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarr-config-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: ceph-block
