apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:w8QjNyqW0hz4dlw=,iv:Z827GVXI0LbsPlh0AFDI1E/Kw+Hbf4WkstUhu7hnETk=,tag:GKJ2HOy64XFkwyBPeHbalg==,type:str]
  KUBERNETES_VERSION: ENC[AES256_GCM,data:o0bThrOa1w==,iv:la5CVSrREF1gFBWP+DKkFtHHu8JcN+vi3CtNgea6jfw=,tag:lniteHlijLmpMLPUHgyd+w==,type:str]
  TALOS_VERSION: ENC[AES256_GCM,data:1vWolzvMIA==,iv:rcVgOz0+taEXUAYkoIn1jD0An4+8GsQAgUzcEk6WL1I=,tag:Hd0CHSUNYjMzKFR2FIBrtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NHNqckpGM2psT3lOUkFr
        WVRWWUl6cFJpZUlOVm9KVkllcTltUzloeDFBClFleWFkdEtmR0hROUw2RlFORWE1
        ZkwyQzVoVVF0RUZabkgyTTczaWd6WmcKLS0tIFJ5a3FGV05ncVNYbHNLb0o1UkdF
        eUVrYkltaDBIYWlDbXFuVnUydWhuTE0KPufH/BqR99/3oQ1SKSMDwLJVzogcr+4C
        dTLuSUL7I3/XISjHRDIFTi82vGe8SJCwBKw+simMrN1H/TS5xB+eXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T03:31:11Z"
  mac: ENC[AES256_GCM,data:CULTh4A/HvcILodqvFqHlyflrCTrLsfNllab3YWtnDulTTP+EWWDQmTpPfdBDak0xLjtSV/QkMfqvvR0SQ9sh69E2wR6dyE4GdW0v2kB+23+SVRjZX9WOM4o10VfrpX68TkkJV5TWU1yR3P3y4bfJ7ny66Ipm6CDtoc2odOoElw=,iv:xQsP9IC6LgMMZBNP48vvcApU9a3a3dSS+0dwaWcbIrA=,tag:Oxl796SBcD/mubRl8NMfow==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
