apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EmNxV2G8DpFYRAM=,iv:qd596VKwOa+tQ7Av0Ky0b5akp9dkSpki7fzcpe148Ts=,tag:lYiRDVmLaoukoibMz+ZSDg==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K25GMkdwVmpwblBxRDY3
        OCthTnpNaHZLdit4enpYU3VsU3c4ZmNlYWpNCm1mT05oSDJybEpBTXBEb2JDTVEx
        UDZpOC9kb2pVVFR2c1hZOTR6V3VMcjQKLS0tIGRQT01JdE9QMDk1R3oxY2RyekxN
        ejU2WXFGWGc2ZWwxbE5EaC8wMWpVTjAKPiQW2EsvNvdy63fAYV07iRzUEE/gAj2k
        n9CKz0/RtFcaZu66gPEvL+q3S/od8w7kDYm/sDFcG2HhBt9AUCazcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:18:06Z"
  mac: ENC[AES256_GCM,data:gBMTkzgPb+Sx0or3JOjs3tf5mXrew89GvBPZ9cTsRNOU4Mu+t0dUKLXlScwDqJKr8oJhQpwleelDLWEsIYjsWy4/BjfKk0S9M0RdfGoTvIdNckDHkAMzBm5zzknI6vnvjR5Aqzd7wTl3SfnYK5ziZSiO3tECqVHbSy/imq5fTvc=,iv:HgRT85JZShedNto93e+nmwMTwvL+sbIny5Brsvh8h1I=,tag:hpjtL5MJljWPsiTgitTfWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
