# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
type: Opaque
stringData:
    credentials.json: '{"AccountTag":"712001e692a3a0d43be3f0825e18bd78","TunnelSecret":"lzUXG89UZuuesxclQFy5YzfAKJLvS3I9SsM7ULV8ulM=","TunnelID":"84f6576a-3f0d-4f87-af75-27d9f04fd9cb"}'
    cert.pem: |-
        -----BEGIN PRIVATE KEY-----
        MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgNlQrcGmS3g7lJ9pr
        CCXiaasrEYYaq+Nj4InHFxeUYBGhRANCAASLyly8JAI4/zSbQHoetq6bXNaXkD4Z
        xj85kFEr/uaeSHwwjWOhXUSOJzAiS2eUkRvk1LZ83h1MJHdgtA7B8iCq
        -----END PRIVATE KEY-----
        -----BEGIN CERTIFICATE-----
        MIIDIzCCAsigAwIBAgIUDFt/s8r2ybJnD/ni1TcVxHeCZ1AwCgYIKoZIzj0EAwIw
        gY8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTgwNgYDVQQL
        Ey9DbG91ZEZsYXJlIE9yaWdpbiBTU0wgRUNDIENlcnRpZmljYXRlIEF1dGhvcml0
        eTAeFw0yMjEyMjYwNjU0MDBaFw0zNzEyMjIwNjU0MDBaMGIxGTAXBgNVBAoTEENs
        b3VkRmxhcmUsIEluYy4xHTAbBgNVBAsTFENsb3VkRmxhcmUgT3JpZ2luIENBMSYw
        JAYDVQQDEx1DbG91ZEZsYXJlIE9yaWdpbiBDZXJ0aWZpY2F0ZTBZMBMGByqGSM49
        AgEGCCqGSM49AwEHA0IABIvKXLwkAjj/NJtAeh62rptc1peQPhnGPzmQUSv+5p5I
        fDCNY6FdRI4nMCJLZ5SRG+TUtnzeHUwkd2C0DsHyIKqjggEsMIIBKDAOBgNVHQ8B
        Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMAwGA1UdEwEB
        /wQCMAAwHQYDVR0OBBYEFB2L1vWHCZzHk8C+TMHrBtYfVZqnMB8GA1UdIwQYMBaA
        FIUwXTsqcNTt1ZJnB/3rObQaDjinMEQGCCsGAQUFBwEBBDgwNjA0BggrBgEFBQcw
        AYYoaHR0cDovL29jc3AuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2VjY19jYTAlBgNV
        HREEHjAcgg0qLmJoYXJyaXMudmlwggtiaGFycmlzLnZpcDA8BgNVHR8ENTAzMDGg
        L6AthitodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9lY2NfY2EuY3Js
        MAoGCCqGSM49BAMCA0kAMEYCIQDUQ39YcZXQ4/kT27TmxhIa8T2G0JiCjPsV31JF
        bBtToAIhANFFn4WRXuUmO7tLld2g2SpOEe2tYqLnrntAPqnxPb5y
        -----END CERTIFICATE-----
        -----BEGIN ARGO TUNNEL TOKEN-----
        eyJ6b25lSUQiOiI5MmY0YWVhNDU1NDliYzQ5YzBmYTdjOTY4ZjcxY2U4ZSIsImFj
        Y291bnRJRCI6IjcxMjAwMWU2OTJhM2EwZDQzYmUzZjA4MjVlMThiZDc4Iiwic2Vy
        dmljZUtleSI6InYxLjAtMjc0YjU4MDQyYmRlYmI3MGQ4YjQ3ZWQ1LTZjNWRmOWU0
        YmJmMDRkZjU1ZjM1MzVkMzQ3N2Q3OWM2ZGFhMzFmNDc1NTYyZTA0MTkxNjcxMGQy
        ZWExYzBkMmU5YWMzZTAxYzA3NGRlZGYxZmZhNjUwYmE3NmM5NjQzZWM3YWJiMjQy
        ODIyNzdmMGQzNjIxOWViYzlkMDc2NmY4YmM5MWI4ZDc0M2MzOTViNjBkNWY1ZGRl
        Yzg1MTkyY2YiLCJhcGlUb2tlbiI6Im4tV0hwTDV5MG4zUkJxU1Q0ZTZZWF9ZaW9i
        ckdFYXJtYWlWems3c1IifQ==
        -----END ARGO TUNNEL TOKEN-----
    default.yaml: |
        # Name of the tunnel you want to run
        tunnel: home-ops
        credentials-file: /etc/cloudflared/credentials.json
        # Serves the metrics server under /metrics and the readiness server under /ready
        metrics: 0.0.0.0:2000
        # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
        # autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
        # recommend using autoupdate.
        originCertSecret: cloudflare-tunnel-origin-cert
        no-autoupdate: true
        # The `ingress` block tells cloudflared which local service to route incoming
        # requests to. For more about ingress rules, see
        # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
        #
        # Remember, these rules route traffic from cloudflared to a local service. To route traffic
        # from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
        # E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
        ingress:
        - hostname: sonarr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: radarr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: auth.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: lidarr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: abs.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: audio.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: desktop.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: grafana.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: hass.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: abs.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: komga.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: mylar.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: ombi.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: prowlarr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: readarr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: status.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: whisparr.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: theme-park.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: calibre.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: calibre-web.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: theme-park.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: stash.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: plex.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        - hostname: flux-receiver.${SECRET_DOMAIN}
          service: https://ingress-nginx-controller.nginx
          originRequest:
            noTLSVerify: true
        # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
        - service: http_status:404
