apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:BUoDMdOwV16qT2PXg0zQNfTFGJVxjKvTPgIxPw0iyes=,iv:+q43TxeCwnqJUdWJPunUYlqLbgk2U7QYyIdyUDGQ434=,tag:JjjsgYHU+rnN5pwhWgXtyA==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEejdOR2FRcklya0FvQXZS
        MThDUVVXcGNIWE4xcWJlNWtsdS9aTXc2K21rCmpJYjdsUlFENVpVRllZNm5xSnVU
        K1hQSmUvRHVodHFkVm5WWFhtT2xjSm8KLS0tIFJ6TGFSZk9RS1NNSEJqOHM2RGNY
        cVN4SFNkRlcrVHZQOVVvOVpNVkVjTWMKl3ranK8T9u2eV2ljkp0lQU6Za4vd/k8A
        sidAdVpzm1prPMkOuBuC4urfVqNNYFHdGbicjl16grfSGexmF5Tbyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:18:06Z"
  mac: ENC[AES256_GCM,data:B4rhtPq3bgzn5Ee6r9fnB5jJ9v/BE8HpccI23lJ2vwzLmTT5tDvDcZmju9e3gkHcT7eK+jOgbEbIinOsXuECmu//7H2hKmDSDvUwECXwYMnUHVl09sV+GgBrNFiX4rpfj+j26iHd+/sARZk5ygf/FCPAkqNObEEGuK5/9yIFCMM=,iv:/Q5BnAncw8ZKqGgwqbMQ8cOtpE7b7Ex4IMr4htQIldI=,tag:Iry/HEHckBek+UbVH7heyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
