---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: audiobookshelf
    app.kubernetes.io/instance: audiobookshelf

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

# storageClassName: longhorn
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: audiobookshelf
    app.kubernetes.io/instance: audiobookshelf

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

# storageClassName: longhorn
  storageClassName: ceph-block
