apiVersion: v1
kind: Secret
metadata:
    name: abs-config-restic-secret
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cLGWp7t+QDvDdaCgvZj1ecEiRqz5f2hEct0aWIV17QF9sG6JGRIR0fBWPA==,iv:HWwXWFd68PeCIhlVNMTMkCDo0xrFNBFzR1itRGqnQAE=,tag:T5cjdTLiCrrGIubiu8I5CQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:d68rhC83T1M=,iv:vNldJzxDjt372sMvcw3KzSSXLAYiInjLngeOR92A6Hw=,tag:xDmpXbUxxl1c3uWQX1GbjQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VwmEg2JS0g+2dYwYh9B6kg==,iv:poYUl/oBXec6Wz64RE4UsDZC7/yHUxPathk9ZJ1+KVs=,tag:cw7d/iNMoFyUmAzL+SHbLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+4Qoecu8HMnc/U0lPBx4r4LBrRA+M9HsibfD/0iz6HI=,iv:ahJf9gYXcW2ixFyWrNpciWhA0DYNL63bo9TptAxvztk=,tag:H8wGpnaSsdifI42EK25K8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc2tTSWJtZ0t4UWRydnFS
            bExtYTdIZzJ2OXBUOTg4MlNZRlliK1pKV0JrCmpFcVlQQTgzdzQ4WlRpbzk0dE9j
            dzAzNjFkc1VZUEtwQVFKSk1XdzlaOEUKLS0tIGlzbE0razk3bnBJb3VPSTNVRGZv
            dU1zZnVJdnd6OEhnWXFsT1pEQUFmSkkKew9eqYeV6LiAjUD9Rvi43g9SJkvPjFIA
            vOZx3PVRVz/R/mX4L/u5osbsvi47LiMXnHNl9cTFDVH4ps7p19qmoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T11:45:51Z"
    mac: ENC[AES256_GCM,data:D3pIJaRTLecB+yTaPf/VCuuy3JRQsAlg4iGCqhhqy2f10UQo4tQr40C7QsvC4CkS8KQ2w3Fl77hSnDCgEQNWxiiL+xPbFrfrvfrfU2fRbDVOfuj5cGh/sa8u0xAH8wJWuYnqyM1lWsuZAb3067wCWXsDbtBphQhsDXI9uOrAu1o=,iv:83vIWUUQBESIfWE1BqmrbXtjpp7LuOn3OxtJso5RLms=,tag:7e4Iv5Nf7C5AgL/7lsS61A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: abs-config-restic-secret
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5B19ILNi0i6XOGUGIiGuKLNyrmNx3YLTVrrIu8G1IptPykfAbm+UlApegPXh,iv:p6cnBkllaNiVXRYHEJpCo9fwigflaXlRPGor0rdAdwE=,tag:uZ9iUSjvZU3f4yJiheUx1g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qOvQ/q1SAjQ=,iv:x2zPc9FlTPucFfO4xVmNEhTHvsw2eyr1uCG9v2xVWGM=,tag:cZCuPA6zM3mwDgznMCxxQQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uDPRlad3aVqjY/LuY+43KA==,iv:AT6uCVKjKMfjzjFW3wyqlDh0Hnq+gYs4l/XZNphI/Yw=,tag:RN4y8iaX1AJhI9Y28mnJfg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9R6nnx9230s/vP1vMf+YLjQlnXutAgN3SGfzlS0oYlY=,iv:QyTLdx5OdKk9lsaUbu86vVM4Ou1aEBgI2SBN6AAn9sE=,tag:IHGVyP9165IFSBb6AXIH3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc2tTSWJtZ0t4UWRydnFS
            bExtYTdIZzJ2OXBUOTg4MlNZRlliK1pKV0JrCmpFcVlQQTgzdzQ4WlRpbzk0dE9j
            dzAzNjFkc1VZUEtwQVFKSk1XdzlaOEUKLS0tIGlzbE0razk3bnBJb3VPSTNVRGZv
            dU1zZnVJdnd6OEhnWXFsT1pEQUFmSkkKew9eqYeV6LiAjUD9Rvi43g9SJkvPjFIA
            vOZx3PVRVz/R/mX4L/u5osbsvi47LiMXnHNl9cTFDVH4ps7p19qmoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T11:45:51Z"
    mac: ENC[AES256_GCM,data:D3pIJaRTLecB+yTaPf/VCuuy3JRQsAlg4iGCqhhqy2f10UQo4tQr40C7QsvC4CkS8KQ2w3Fl77hSnDCgEQNWxiiL+xPbFrfrvfrfU2fRbDVOfuj5cGh/sa8u0xAH8wJWuYnqyM1lWsuZAb3067wCWXsDbtBphQhsDXI9uOrAu1o=,iv:83vIWUUQBESIfWE1BqmrbXtjpp7LuOn3OxtJso5RLms=,tag:7e4Iv5Nf7C5AgL/7lsS61A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
