apiVersion: v1
kind: Secret
metadata:
    name: abs-config-restic-secret
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ulfZswk2FwCnY7A+rHjBYaqf59yetaGUxzaL2/bQfuNR/xaaFwKJJXdprw==,iv:utr9oPHi1bMcEk4WN63h+3T1kvEF5ICurA6+FeXTAOI=,tag:7XZzcW1JX4dKT41Q1k9opg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:pM6r+5TX8U8=,iv:HDXaB7d9DT63ii6Ovd6zJal/9GxxCm49PusoVcKCw7U=,tag:uNE5vwmSLiwkEYW9KMkefQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sCK3NNLlE10mhgp0eIvvog==,iv:b1LAI7csKRxqahqDAFLbEySaxWNzFwUmURrbJGKMGQ0=,tag:kPsvCGoAksa97X8vtSEHkw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aeDZy4NoEnqySokgkCPFDIEcL0BrwYiD8L8bNnZG+M4=,iv:ZQSghqNF4WV/dhThBsjtR3V3pBGN8JBOnBS9GaABZ24=,tag:4Gko3ZRYC4fbsUZbejerwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2pyZE44SnB6dUxDbUZJ
            OTlUSmYzY2d2bGRvaWtHanVJdUFleG96d3c4ClhQVXk2QU1TRHZTamtIblNIWUxk
            M1p1OWQwLzY5WnlsQlBBR2s5YkU1NW8KLS0tIE5TQ0FaOUZSakY4a3YvS3VYZ2p2
            NzVRRVZFbHk5Q0svUUZrNVhOL2I3OE0KESEc8F6BzGMfrpMQxx3QClLjmqVN/Qrn
            SlxZS1MkWw8H+46SEJkUSoXoXNqg7QX6nlb8+61/UlfnVRqKnMIiQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T14:45:03Z"
    mac: ENC[AES256_GCM,data:LPfr0uGVI4yuVTN7vo9E/bJeZqNFW6DTHLOx54oRAa/idDeYketRvuk6GoDQ+0wJ8JJ/m5BL+3bMKi500Aycmzzx2yg1tI0Zz7FxN8zz3FO7WRCRnSxSorxTqHwzttYWkSljfLCPa12EqPsKFmrWVydTVtWscRol+LfP0UfCKS8=,iv:jWW04YytVmUOlg+yknbJasprY7CgmJ0RS3Jnapgh72M=,tag:zq017pKVyT3FJOIaE/bq2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: abs-metadata-restic-secret
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:AVOY+TujHFAooy++1iA83ulKXtfetvMfP89kTP2rsRvfFCkh9XLnkK1HJFSq,iv:jQHts+WwQikwNLQWa+cA2DCGpVpC/KdRoUp8CSUSNuA=,tag:U9t8iNG+o3ViOVQ9YKZS0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:e4HSAyGXwxA=,iv:+q+JqrQWjdh4gpZOu5Pw8QDAIPno5EFJo2U5Y8/q8YU=,tag:LKQm3KvE7zWhiz59pQ7BCw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zaNPWxSKwb3Tr033tOiGgA==,iv:y7ERqaFesWVKj85mZ1QOqiXleUw2OtIM5Gi3x69nDrQ=,tag:lyUIgLhwTxc5hhk0+c352Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Vi/KM1AJjcHvlhohm0VQQM0JRmSZT3ucmCMhIFd1Gro=,iv:rn6Vt4LA71hTBqjjpTZbee8KTbIo5qGs1aVpXT3i1z8=,tag:n32RgJ2igmLlSa+9gGoSKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2pyZE44SnB6dUxDbUZJ
            OTlUSmYzY2d2bGRvaWtHanVJdUFleG96d3c4ClhQVXk2QU1TRHZTamtIblNIWUxk
            M1p1OWQwLzY5WnlsQlBBR2s5YkU1NW8KLS0tIE5TQ0FaOUZSakY4a3YvS3VYZ2p2
            NzVRRVZFbHk5Q0svUUZrNVhOL2I3OE0KESEc8F6BzGMfrpMQxx3QClLjmqVN/Qrn
            SlxZS1MkWw8H+46SEJkUSoXoXNqg7QX6nlb8+61/UlfnVRqKnMIiQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T14:45:03Z"
    mac: ENC[AES256_GCM,data:LPfr0uGVI4yuVTN7vo9E/bJeZqNFW6DTHLOx54oRAa/idDeYketRvuk6GoDQ+0wJ8JJ/m5BL+3bMKi500Aycmzzx2yg1tI0Zz7FxN8zz3FO7WRCRnSxSorxTqHwzttYWkSljfLCPa12EqPsKFmrWVydTVtWscRol+LfP0UfCKS8=,iv:jWW04YytVmUOlg+yknbJasprY7CgmJ0RS3Jnapgh72M=,tag:zq017pKVyT3FJOIaE/bq2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
