---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namepace: databases
components:
  - ../../flux/components/common
resources:
  # Flux-Kustomizations
  - ./cloudnative-pg/ks.yaml
# - ./influxdb/ks.yaml
# - ./redis/ks.yaml
# - ./dragonfly/ks.yaml
# - ./crunchy-pg/ks.yaml
