---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-app
  namespace: databases
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg-app
  path: ./kubernetes/apps/databases/cloudnative-pg/app
  prune: true
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: databases
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg-cluster
  path: ./kubernetes/apps/databases/cloudnative-pg/cluster
  prune: true
  dependsOn:
    - name: cloudnative-pg-app
      namespace: databases
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5
