---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
  namespace: &namespace organizers
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-connect
    - name: pod-gateway
    - name: rook-ceph-cluster
    - name: volsync
  path: ./kubernetes/apps/organizers/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: fluxsystem
  targetNamespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
