# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yAq9lUMNtwUTZroua2crRYYU/pUjZE6opoS3GjC0Vzx5iebUAYbwjQ==,iv:lNUgs5bP4qfKKCOcWveNkWNLVoO3+q91m6o2Ou0SWl8=,tag:/NHMjac0mVTzSb0c+5sksA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWJnWnUyQWYyd1Z5Zk5S
        QlRNbVNCaHp2RXI1cUFiT0M4TDBqNE4yQUNzCmJLK2lXaXJpQUlxSHNGTlRDM3Qx
        d0F6VmVRNWpiZEhLR1NKRHlzaGFMemMKLS0tIDZ6YlJEd2ZoTm5yMENHMjBmdjJ3
        SU95VFk5d09heEFkdGtid2UzRGZzNUUKS8UotasBxba54PdXIYqI50IuUNm1QvSt
        dRgIIPU/XSv+Pxt+7/sk9dsTI0HTEjwSMTjp9OqtEyzUeJxqbI035g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:25:29Z"
  mac: ENC[AES256_GCM,data:6bp1HLITVilyTQ6nY6bZQ7FQf+ygVxizr6r4voE+ksmp3Ugnh+1HFyQMIcTrb7ka3b4V81CQWFGRGcMLwr9/WMGGJul4UL8itv54o69ssGun3HXRWPmhN8LMwATdpdE1tdiT3OfMV31aGnP/HhRKkvrfv2wHmMyYWDiwJ0VMEgw=,iv:zqFU0ZGMueOdCbSbSeES5Xqb66N+GWS21ghXjoMGuFY=,tag:ed8dlwe5iuEnBaGPHLnNSg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
