apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:OkxLVc2KKOkyoLz3Q/HkVGEIblrHMtskeQa6uqypBX0WiTbI6w==,iv:cfNjLhaf6O68lCzWuyj/CI68CLF3Pyp9wGsOcz5wmMk=,tag:ozXmxwJ9dNcF827Pav5qPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbXlqc0s4dlNuaTRjOXJQ
            QjdrQTZDbytBTUluRGIrSFI1SUU3azRmMjFnCjBnK1FIdW5oOE0xcGp6VTJ0T2Z4
            OW5NdGNXSDJPUDNScU9qOUhyckFTYjAKLS0tIFhoMFpxOXJQV2p1Uk5CaEtvTjJK
            OGN1UVdGeEo4cDNzNjNEbEhIeHd5NTgKv9z/PJkzUaW17HDYon2vw+ts3BwG9EO7
            4MZ0lwT1MTtsXsxs66GK7A+IDq/B8u9tkqnux2LBLStIQmEF1KEwmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:d5Y3M74CR2H/Q+BvMhYypAJL7vmZVUvEh9jzuurxrCd567vvJ0/SlY3CtMCusj3U/iqgb3AOuhGTkt8utR1Pa4uCuQKawev7mRVhVkBifKuOkKB5muPc+BK0NwA2a5T9nragBS9uD69ceGgM/XFI+3eOa6NAQjPdoRbSKG/cI/s=,iv:aDlQIvcPQcF6F2qlzU8v5SnTScXZW/tWuMNSjUmUclo=,tag:MsphSna9Pj2bn/jAO/Z1qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
