# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:brR70MoTlp774huDtMCD9u7HNnXq/ck6+oRDdW2kQg1ep76Z2BTL+A==,iv:iTPAQAWVGOXxzIM2+TN7gROVo0R40T3a1CDa3WvfcPs=,tag:QJjKyqyhsFHaIyI/sqb/PQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbWNQZkIyVG9lb2d1NWlt
        YTV0anYxR2NsQTgxcnE4Z3BNTEZGWWhBeVUwCjN4anQ5UmpIWExKYkg0VXc0WVdJ
        SVJ0N1FrTEQxQlFUNlc5aXp2VEN0NVkKLS0tIFlpcnRieDdOMXBHUW5RNkFzZXFr
        SDlHbDZxRXV6VGh0VU9HVzhRbkRQMUkKUFgl/mE8d9dlkkEppBPE3XTNJYs6btnN
        XDpVKJ4D7VR60wASK6m6qjhxstNFdxzKoxkQLEcLWp2KrpJJq3j2Uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:54:27Z"
  mac: ENC[AES256_GCM,data:MUptIcCZ4m0w2ZDdPM/UzBmpaD88sbkaTeP9muzhCJAxFw7QrekVRrCrfQibNV9ZCRrf3QeM2V8fjrkeZmqpz4bfONDrZHgfNcY+nzVrsZ1eQjoadPmXywmeEJkzSjEOPo9FilRtdq+yyjru/ZmH5T5acaG3qjw9VLExx0VZU3w=,iv:dVUTC2RuPUY445lxPH0WgivGmzD162Tw9QF+vZkJSz0=,tag:SjN0Jvx2LmjD9OIUGQdoCw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
