apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:LKK9DwkxX1EdPkUZnxMh19EcneqEfEAoFkudIx6XI4DI2PkKAA==,iv:N+IkB4sAZZVkysgn3rZH36Vd2eVXfkCMOF8N8Dse9UE=,tag:+aNFC2+iM6GyHnPLVgL+CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUmlkUUh3R2pWL0dyRVBp
            M1ZPU0tJK2RZTkFaMFNGSUtHb3hzbk1Ra1dZCk9VY2pqZHVpMHAveXBEa043cy9M
            YTlSbDd3V2JkVFNxUytrelBjOVpIZDAKLS0tIG5ZbHZBSkdRR3NXR29QMXZXclRX
            TEY3cmtmV3lxUU9JT3JZc1hVcGhSK28Kc8+wb2GeF8VkBWDqj7nYSgdNgkbO6QNF
            wRcJN3Xsb5fOzui0HgMQA23L6L/S3JjK52lyXIkZs74inu60YlFDrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:Vbo9YjWN6y68FIqvcnE2L0mDgsU2njRXfO4/X5lUHx4YbWD2DGNI+T3OWdUt2LSPtLhAkDNc6gPgWFsovt2Lilq/OOtlepG4iUket8aW4KtOGTBWJoorzJi9Re0lQXCROvuSp5HYn4secsoSmR+tZEud7aGPg0MaC3run94TvB4=,iv:YRTmWNnXYyCMsv1chh9WQSo2+kZUnCDyfnGz9RzridM=,tag:nsLF+33F7CvppqDih4H/rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
