---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prowlarr
  namespace: &namespace organizers
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
    - name: onepassword-connect
    - name: pod-gateway
#   - name: volsync
  path: ./kubernetes/apps/organizers/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
