apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rxjFwynYR9C8PC+abkr2kQ==,iv:1Te3p8QHUfmr+pQBMl2gAlWRXL5Rl8h3Q1N2pFHED6w=,tag:ubt0tZfhPdRpXEADDEbUNQ==,type:str]
    api-key: ENC[AES256_GCM,data:FvlRQaq2jmQFzteaOiROPBuvj5nBZlBxoSQ+PHjJPpRX9H4iLA==,iv:hd/7wpGI4Y1vqIfM6hGxtTaUSW2ZjqJGjPg4SdfqAY8=,tag:UY8yM3whDj2mihPiWqkGaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVjRFU0djdWpUanhGdkt4
            bVpPSHVkcHUwM3NISElERElzckRFNDcrZVdnCjd3QnN2RVpiTURqMmwxYUd3RWQy
            a3NmRDF1MkhlVFVOZEhrZjgyM0M5ZkEKLS0tIEZtSkUxT2IvdXNYV004RmQ0ZXA1
            VDgrSjZldjJ6dElqc3hQdzJKM214em8KlX2YzanPc+dyWQKRlmfB7DgHGJ4MeWEV
            Y9bY3Ljt7o+jlK9CeRC3oIhbxAhdKVuSgTurm62LibsOUnq9G0qx/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T00:39:20Z"
    mac: ENC[AES256_GCM,data:6FGWoJWczJQuqdK8XUywRhZcZcLAgNm4nqcokfqRmLmrpNTKNJRKqT1qxBejcNJKl2lrpzrP4PD/ZSymJVFSBVqctRTN3hkVLs5SszQJLR1TWOPAtfWnctfaQ5/W/GkxBlddFaOgseP4TLyV1QsEdPu6/JaWIzSSNccqUJDWNjQ=,iv:LMr/NXofA7DWUzyWFONIN37y0rcjV0MXvfahPjW67F8=,tag://vNKpt8g0Y2aRWev4ahpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
