apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:5FZHRsdMPy898s0FhPW5Fg==,iv:909lkLXcffvIuLSq2wY2f8mN30EakrLeEnbpeUCJ3xw=,tag:8Rux6+jLBLmiUDEnmjIVOw==,type:str]
    api-key: ENC[AES256_GCM,data:raAeFif+m5P8ijj9ADtxdFmKgUmQeIVkV2r4pVq8RDliVWRWFA==,iv:1ytDjaHhvxU2ePoP8QKM8a/kz34z3vE9MfNEwiSTrIc=,tag:vozDB79+gj+oZVmZt0Fttw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2h2RDdOaisrUWRmMnBN
            Qkh5dm9xZEgvT2hSaGVZOXlRL081UEtyMjBBCmtTNWFxNDV0Zy93NXlCQy9VM1Ez
            d1pTcVVyNTIzVGw2cDY5RnQ1TmZBZzAKLS0tIDg0VVFjYk9aTUZwNmRwUExQQzVG
            SEZ6Wm9zaDRaNkJyWHlvbXQvZXJaVUkKkv6y+qOvw9ikF7hJous7bWvTbK/1rCof
            agOyJgKq3m2hmA2+Q+2jNctMAmsNgb8Gby2zDicf+1j3NPG7aZ/Xqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:32Z"
    mac: ENC[AES256_GCM,data:wozUCGGqC3SB7VJoFFiv16dN4Acd5SAZRpfhD7ZuyPw6azja3mlu4+QPsDg44oaZESVPm+pbRgbshD06mzRhzYNgmghy9ZY0pfY9b9RBwYreUvom3vWuMoBvYdDTsggq7ShFLJINAgzFz+WnLxcK9Y9thkr1njcnr454wXq6l+o=,iv:1aMRH6AekNcgcqTrgBamZUADHvAGRFZzZeA5+rs7uS0=,tag:wadlWONfeyo0yH2nzDQ1FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
