apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: security
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:0bKqwLroa48=,iv:541EAIS9WrXV9YF0GkdN0cqjhkVMnN59xWSx4ia72bs=,tag:drEKL4VNQmGKQplEqRKjmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNFBWU0cwV3hZYytEZXJI
            VmRLMWJ6WDRIMWFCS1NjR3dLL3pRNTlTNjJrCmVmU1VPbnEwK2lLNVpuTTVURk92
            MU44VGZpMGcreExpblZhUzF0QjhZekkKLS0tIGpycGxqQURyWUREVk9NeTF4elh1
            RCtwM25JVUtpT2V2R3JWWnNPY2g3UTgKxYpfj8L0riBouqvTYccXwZKbpZowfRZ7
            dgw/PJ5D2rOhAmB385Y8fwJTzX8QTrUyOD5i6ZwJ3hvXm9bwUoeeug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T08:38:47Z"
    mac: ENC[AES256_GCM,data:cFWkRsja7roIlyONpGCgOlIOtKWfQrd9dY0E5oI8JiWIrVTUeygH9zjmZLAh/w0FDTVYs+gnwanF+NWAOJ7Uj7PdebIEUhXjSAPV1DFy4gcwQxojGF1VdDeiihkyiNn0qxTb53dyjQ2s88stE+U3HkVoDuWOV89tIQ2wyfZSfQA=,iv:nVf61Ichfmz98r7XUoWL4MkAq14B6iVp+2vJR94IF9o=,tag:Wz13PJBaT2+qDkuGPcWC9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
