apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: security
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:xAzSvLU7EiU=,iv:P4sStveXklpbNH0l5m71bXLjLpCM7hQAEe7yqkV5WzU=,tag:kQH/W4dqL2YOwAOvR4XemA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY1pPOFFvck5WRHlWZ2Z5
            bzlFcWo1ai9NQnlWVm5aT0gvQ08yMkptaEMwCkJXcUNWeEFHTWtiYkpDMThTb1Zj
            M09wM01Sd1JlUW5OcXVoQitTeVpkWEUKLS0tIE1SMkhDcGpjNTRvVE5mUXNhUnM5
            bm5maVJNb21wbVBiR1piVlA2dE5xbTQKqfPWPZ2AR9do83nNJMJISXY2gfPgA3Mc
            SB0i6AH6H7wTsjzSmYUEHh0MfC4tFSPbAjKUTku4y4wUqB/sIiQvSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T04:03:29Z"
    mac: ENC[AES256_GCM,data:S713HvmQ6nZt7+cObp/PdP5G5HlVqMDMxXYfl1k0gPX5r9toIpTVAx40aBA+x66fBZmJ0LlrszY9doyQpIRXXAas3I2+tkLpXsDiqJNSMfGNpQlXy07k3OD1lDRTS4uHkVVHNrR5wMWlDhGdDFZ6KAQuaBSEh6CqB5gIumvP/Ko=,iv:vT9R7FF/QTdgb+8Hk9oedoT+dGx9DhRva88+1Ws3WxY=,tag:LvwDRdkNxqO7BK9wRWq8Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
