---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
  namespace: automation
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: ceph-block
