apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: home-assistant
    namespace: home-automation
stringData:
    SECRET_INTERNAL_URL: ENC[AES256_GCM,data:BMI/3lHrbBc5X4WlOmd9wPkE0PJ6fx+a,iv:pC1gIWK7riuvNZCCCf55FAyCbZBaeaZ7XX21OLfE/+I=,tag:J7+0qeh/sTEG2SVLoSGB0w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:WZ1WjA==,iv:fLQWh1Jz0Q8sHsB7pcxDAXdGKdn6HGQsacWi2AoTUkM=,tag:k87aVhO3nCTxn6OiS+zMWQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:+aPGtLpdUs7uT5HUieda3KZentR2TFA1TaE=,iv:iRuYryUVCsTsdCVWaYsokaJH6Eis/c9/I3al0QXp7O0=,tag:Q/lzzSW5pDIGKkTHRkehQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdmJGSUIxeVB4MEJLUW5p
            UVo3V3lXVTV1dW5EdE1IVFVOTlZCRW9zd1RZCnBWbll2UXNmL0Z4L0dhV0p5ekQr
            RWtZa3Z4MjhIWFN5UGRZUlF3allINWcKLS0tIEtKRjJRZUR6Zmlnek9GMkdYeG94
            VHlNS2dGNHB2SFZJN1o3dWZvQjBoRGsKF9k++Q1te13j2gbAeTeCELwcf8PYT9Kn
            xktMzqSGyDX2LdFE8GdbRxcHVzWZY8f5X3Vncz6AmiTOEKsGF2iQiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T20:08:30Z"
    mac: ENC[AES256_GCM,data:tst/DB2Yvb0QEwmFuRfZg6n+Baigy9cG9PKfu23PkU9CV9xPG3mR+3Dgf16Q6chQH5Q3k9WHK3qNidZ5T5De5ZiQSgA87GM+VQSX5cApu/wNM5jzBD9JC5oLw7Fxw0rnUfkoytjoZ0aqSxxumLABFI9/Kz4KNN1OFcLGG8X28nU=,iv:5Xvn9kzAoOL1AlsSVrC8+c+tDbc93DJhMptNqhPL4vE=,tag:PaRRFcGLRNHvbeW58C9x4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
