apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rGxtXN9PTZTch8wFAh880rPbQRuh2IQGOtr9bSglswl3byYqFTTC55nXPb/TwA+0Lh1X9Q22g/WCnk5uQjA2CONZ6IW4yFg1UkW73vM3JfECSiYwH3FpCC1hlgza66j2P/gfsEKspQGcWSMgP2QOUtwoJUx1CIIIz2IYfZaWoszObDxEqux2e7XVZaQ0GVpNoPvkyafgT5POa7D+P5EHKFlA6eUPQmlliria7Ip3OCkMziAX,iv:6wiKagVxZ1cBWJyssl7M6GY5oWxn3v8sZvAKlQdaNss=,tag:oW/KWKZsatwisUg8OH/1YQ==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLanVMQlVEV1RYbm1yaW43
        RFBrTEd0bXZxcjRybm5Oc01oODRUM202b1hFCk5zTXdBUkJTalZTMWRKSElFcDJY
        TExWR2F2UEZpZDU5N3F5TERuNEhnOE0KLS0tIFVTUzhFbTJDeTd3aVJIRlBrRXRs
        MlRaUmRrVkZ6VUl5MmlSVUF6bTlrMlkKVlWi+3KUhCjqWPcwfz4MA429OfQQE4it
        imazPrRCA14+KK9B3jNp9zcTdA41WmAJwLs6HFRuREZVrqvrLqxKEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:18:06Z"
  mac: ENC[AES256_GCM,data:RxXC8WwEEmUmgAuO4V3/2iVk/x1FicNdpoeajt8N2sKua5qY86lvNsyRKBDtOhplgOrcPRIyEgTkz05jETknz4fcxgyqij0DEjOmjfECtwNSX3rByR0KKRxnqs59toIWdox5bpMN9j3jCY+zHr5oMpZJnEdpfTMbuYMiswtGcCs=,iv:KGW7vxyPcD3aRs7RzLgU+5jA3B8Mlut426ZfiZB8+FI=,tag:blVyu/xzOr2txfvmJkarjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
