# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: readarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:jpXqLGXNf/sj+3DKi19t7IA+Y3OGTth6H/zuurdx0IU=,iv:SsbsS7w1lklnk5fftLJ6y499ZGpJGOQMqUKeNsZ7+DQ=,tag:aOSkHaygUIqEIGGM17l4xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaVB6ODFCREtvaGdRd21u
            clgvdmdWb1pCRHo1SDZQS3cxSW82ZW9NeWxVCjY5QnhHWEpvQWRxTFN5NHluaUQ0
            WXg1WVNwYUlMMW9jV2FTZFMzY2hldU0KLS0tIGZlSTVYK2hGZ0RzT0ZHNld0SlVz
            czdGMGJhNCtIME54QkJ1OU1rdVY5UDAK3sS3qBXM+zQr8tCrdezZYKqGMYhaDSqr
            2zLWMhW0VEZXwavEcjZRHGi3Ur1rAdIgzIgoexczunfhX0BI3Ei88w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T07:16:20Z"
    mac: ENC[AES256_GCM,data:YUdv6/49wHjYAsda2/NDyzrso18QLWHJ8IBLfaLchi9NtF4czHZM0t2cYNaf6Kqc/fXqnppqCkA/YRBup+aoGXGHpE8Z8RdJH/g0fTdXaDn+1mI8B6T1mzMOtB3luvikztncL02PfpUFMjDl4Y1dgqNfqMPsU5HJ9sLSGRj23jk=,iv:KFntYl8Y5ou51qiPfNIHIMh/pxGUGmzEJQET/M4C4s4=,tag:NiEOPB5FXCWcGHCHGO7G5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
