# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: external-secrets
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:RdOwfcJ0wMicQmYzXfSd3OJm5eXpK/iewJCZohtf8POnMq9ZQyOsZxea4GlukqZHunP+l1G8E8pf6SPxdyi/fZ0IgobPaZF5V7CIYg2HO7laMn1m5LXjTTc4XBzTHGrQI6Ps/R0RjJB7PoOGD0UH/TRpGBQtAaCMfINDVQJM797etuqISr87SzvgW7wFdcl1OtudtdFUWPgR7NxBunTBK4+X0FNSb/haGd+GXooGPSNW2h6naVzMKoXOVtmB1T3twXTlGqf0iVwARwGOQbAiPOwrzwmxM7+apjNyGCGyNHCbM+6gONBs8iuseGZXY34W+m2luDtcOijpVhv0t/8QYPV6h1dV0ywjWL4aWLYpedpPgBhRekigyJOxuA42xCfGXYhFfUMCJ40RtkS/ry3KuWDh3dI4e1pWiXegVDh00/qz+SKl2fCeSqBpsKy9pCVjCM7YBwoBJHvHPkRyYc9P93CvoRAOcJZbsRqxl9mpuP4au7tIdySLaJiuGWZ+Cbpc+QpgOi+t69OXuGu8SIlftW6MTnr3uqR3w3HCKhlvPaUb210mH8E+byD+P5QzP+6aSyxYq9vE2EMsDDD+f65TZ+QOxlaeln6QzkkKkAK1Ncwx09w7VPYJpi7gKm0QGajokpPwpb80aP9+F/1MOe7EjvSqC3uYOOvgX0inxugu7J75SGODCSEwMYiBlousELrslgVsE1adGLwseskGO+PDHgIHys0alSW5P/ZeoDs6/CtD22tFTncPsrpW6IWTAAqloypUFp3nHKyPPwmv294hSvOW5aPlYBz9qsqBAtlnQJ220Y/pSBKYeFCietDvF4fIVcexifd9+5Rs6N9HoryzdQFa6mTnPvYoM0+bhy8nxVmsCScXyycMLiHLMR0MKZnhoZa3Fn78JMu2G3EKhI48oIKUD34VkAMixn7xG5UbV7+8xOmvLNc98dFDAyho8IwvfEanX8vNRtKntsYQLKMDk0mDGmn5r1as1Vn145SZT+pq84elK6pTfGS9K2ZmwJFojxcSzhuveE0oaMN06ScABMs5GTBv5jHcHMnvnGKtITf44TPhVC3qwVZZV/J6hqKaWOvgPiTiRAi+Hd30/9r7S6ano1Gl5uJkE1JfIYGB3QYtQG5MR1Y/14DI3L04gv/Fw+jVGrbxs1g62XG1gxyOy7m68xD2E/UzLANiZh0M10QhQeNsihDWq83Ta8+ZCsAFltOV0P8SBfy9N4iBB6dcwzGe0qav8v3DzzJY7EvBPQK6xOgF/mtbdYOUfvl026yhcnRx509CNuiAHvjC6/s8UKpN/CByxEFTL51HtVWbApN2V0eV1CxZM7Y50QvIGhERNZZkABWAI5Z4wcoDe9ocL2jDO1zwyhRbpPXHC79MmG2ApWPM3opjNt9bJ0bSv4mKmJlUVQUKKRGNGrym+kzyvCQWSfrp3XUd/aMWL2lgqkT+5JVJsXMOOb3l0qJQ+9NPkruDNA6ZAKhX9Qz6NbBeLz4NNrcGMe3CKQ4IE77+KVtYX6jEXW+Qcm3nyP+mHLXJnRIICRjwlpbYlkLjth1+eZqKqeuhDcP90LEb403e6iVtjjVocmPPf/BWHhci5NQkF8gHOFbSxqLjcVIDjcdy7+i9w7YsXv7mhSCeQQK8Tu/mTSAFgTaAB37Ay31le+LLnwx/c8uXGDHoGV5EXoLuL0/En7RJAxjXUnb4moHW2jNsF2R7IAE4EfGJ/rEHRIasl6vuTP7MORndqwNYB6XQ3hg8uy7fQhVNpEtrnYhkHLmO4oJxnIIWusz6TqcpFII+Fleh03gGILPnlS+J3oddgBR1JCfVoxEGBZoLk3WX5W76+4cMltQDSkyh9uxAGgSSmM48Vizu5Zzk1ckjSgTtkEpBEEiCBWW8ZIErcubv6EvtZzZEHODQwuF+w8XFyWw9/dheS5ykeXaFo9dg,iv:+BwKLxYR4Pk75oEU/w/xPhx0SinWPoW661LGYO4H9DI=,tag:7rlH16iBEtjYBDMPPz1oRg==,type:str]
sops:
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTktOZVNNSm9hR3ZpRXNL
        N0lxaGR5MzhVN2dLNERIVURHaFBFRitsYVdFClZpVTJpMlhHaXBRT0JjbklEbmMz
        aXppM0J4YmJWMlZyaEUwNWdlSHRKQnMKLS0tIExaMVNpckxJRmswdkZ5VTBTK3dO
        VktHRk1EREtkaFhmZ08reWR4RTh2L28KpeODf8S4rLiCvFNHI/hAmsvyHDuEQKSL
        B2zEIqB+ssLp2bumrI61VGcMZ0834OTNNgzkGU9YLhlzlWTnnN3Yig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T06:09:09Z"
  mac: ENC[AES256_GCM,data:rHJ/CdVCl5Bl8d2f189eiN56t4VlO/FDcRF1DkNL8AKWWzMf0rhJycjxTvodQ8VJo5pSOVkM+THUNaWMToise/0PdlUgUyN0onMjV2xCvRuP8Y+aab+DZEwdxmw4FONBykZmJJhXwidvueXLZHySBK4L0Dyjyp2lOxfKE2F7XXE=,iv:oXCw9DmhGWixdPRUkVeIXkfg7AF9H1a3TqGe81p3LWA=,tag:sLR4CB6B8E0SieJfuwqZlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:5WMSk5HSiJ/zIFk+xnpo4MjZNRb7XV0ql5VVMsECnA74SWmFjo7ki5u/Sb/VMP6E7tDsrq6HTgWRuHWarTXQBOk9e3q+74OdbCKtD9rFTJvXhoajbEiv4F1pBpququPtbpKw3BZl1M8gFUfI+Hwqbynx0w3ZDXUYG69wbLKUcjW0aqFASv7QnB2+c/yxm55v4DUmZpqe4+IHoQE2xDzaF9fBWSDRQUCBr4+nBBkA5KuuyTJMBAmDSouu0erjtO7kTTdyEjneuE35tchztduYBVoSep4O6aTQhjiHsnaMVkxjsZE8e/Z8A/8YNIG7BNOrdV56dXnFNtKL6y2tZul0W5f3CoVkFN7TlAtkA39Ez+9BTjfgN34JmkeIeD5H7cDM71LKYwBAJEp7fUg4oMDrMAL62Bu/i1+CoGpEz+VLKs8exhhr+721moaSMkVCTI/yiDFhxtf2V5jKfmEq+GCdGmtDsRETpy2t+JMWltIehHujMjsA2wob6GAISFeqNeVcUjgU9cl02rZp42MXNc+zcrp+B6UcARF7/WKVuedW425EYe/y3JzqOnlndCJDAnMH5FhvM5lITr82OZHbL58zE37oB+XAr3Hkkkd9o+33pa9mqcVfdBFdJJoXynFFiDZSRBnbF1V6qihqGBBxfbqd45Rs1FPFiv6CbxYtqv0NvX7/+oWVhQI/s0qRIGAbYbSuYAElC1WkBL+w5Z0LrKX6rSNpr/YBiHW2lJ7z4oHRRz4Esghbx9RcZtjPN37/jMyb2/XLrXJi0UM97BPKIb8jnBRZ7l3KeLLBr63XogKtRkqs/0mbanZMHNZjfF26PvSCzeoUA7w40EIvykCaYmIIbLIw,iv:h/GmKk9049VMEeAw875hQvZ4WkwtZa6G74SwaFLb0DU=,tag:kkdORyyWNgWELBO8dPWRLw==,type:str]
sops:
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTktOZVNNSm9hR3ZpRXNL
        N0lxaGR5MzhVN2dLNERIVURHaFBFRitsYVdFClZpVTJpMlhHaXBRT0JjbklEbmMz
        aXppM0J4YmJWMlZyaEUwNWdlSHRKQnMKLS0tIExaMVNpckxJRmswdkZ5VTBTK3dO
        VktHRk1EREtkaFhmZ08reWR4RTh2L28KpeODf8S4rLiCvFNHI/hAmsvyHDuEQKSL
        B2zEIqB+ssLp2bumrI61VGcMZ0834OTNNgzkGU9YLhlzlWTnnN3Yig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T06:09:09Z"
  mac: ENC[AES256_GCM,data:rHJ/CdVCl5Bl8d2f189eiN56t4VlO/FDcRF1DkNL8AKWWzMf0rhJycjxTvodQ8VJo5pSOVkM+THUNaWMToise/0PdlUgUyN0onMjV2xCvRuP8Y+aab+DZEwdxmw4FONBykZmJJhXwidvueXLZHySBK4L0Dyjyp2lOxfKE2F7XXE=,iv:oXCw9DmhGWixdPRUkVeIXkfg7AF9H1a3TqGe81p3LWA=,tag:sLR4CB6B8E0SieJfuwqZlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
