# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json:
        version: ENC[AES256_GCM,data:Ew==,iv:rB3Bfw6og6nlTOAY9Uccy2jo+9R3MHrskqduP+zbsS8=,tag:r+jDaInyPc0bdRGVAfI99Q==,type:str]
        verifier:
            salt: ENC[AES256_GCM,data:P0WAOIxdo0lqB/2mVR99Qpr4WNSnuQ==,iv:q5r74zEvmlUA2CRSRnw0wKEH2HJoDYA92Y0iVtGb3xY=,tag:+UWbdC2XGS19xVxSAFf8jg==,type:str]
            localHash: ENC[AES256_GCM,data:7kV+Hd0OT1WmB2ryuc75ATiF3igN67VlozU4EF80bxtUiBtTUJ7WsIsWtw==,iv:x6io/+lXFSEyrCiIHkMikl/HeUw/+NimpqGMTp2dVUI=,tag:agrhsn21QscZPwKONvwXpQ==,type:str]
        healthVerifier: null
        encCredentials:
            kid: ENC[AES256_GCM,data:sipB/WX57bls+0ND912mHNA=,iv:Kra+8fBH7cU7FvolefDTZzhdY4eCCZwPeU/It2b3Kfc=,tag:fw13vVeWvnLaDsGRzqm9Lw==,type:str]
            enc: ENC[AES256_GCM,data:MQglq2GyRQ==,iv:4PNMrYtNZgeI8fNw2liYkgIJnDH8qS8R06IGPVO67cs=,tag:A3nxJf5gNbfPx+obcsU/Kg==,type:str]
            cty: ENC[AES256_GCM,data:eOl/3Duwi7DJGlU=,iv:zHlPibheV9epkWp8DOgorrgNYFWU4Jo89NRJapJJwUY=,tag:CWwngr60dM51seCoCdaaiw==,type:str]
            iv: ENC[AES256_GCM,data:32fUc+xrlAv0+gu4x+IjCQ==,iv:DriYjx8iLlgVXSr5DxVh76X0cZNdGg1qLfPdXVr8ejo=,tag:Yv6h+zCs9tvYB+T7fWPvDQ==,type:str]
            data: ENC[AES256_GCM,data:jxRjq1uVC1tPbLMTEnzwQKwj+ZemZRUhnf0ZcETBBjkzsdbQNbqbkSATHNIY6V6S+YKu6yyIh8CD1QNIhxSpCcTI21TdeliW5qeQkB+KiNUPVAhQmO/gkTBvTc9/BZsJ5mLTlaVfDXOZ9nFwGoMmdGJ53BbQkW3IbEWMa93B84eW/0hMPzGcqTT/Jg0Jc4984gDKcqo0PEcq70RIpngoBgORnE1v272p2xlzv1bMqy/n3lSVnMhIrgv+tY0fWLn7i3F2bIm1gXHB4QiKrCWYg8PnhkFHQsyJ29OR7xemJWIdmOjikPCHQafEooR2uMADrLzaxwS22yGJ/ojLmUtoG9L59aowIVS760muQT778IhZqySbX1bM/upui6ibsjkIJbz7dEP2X8HE0/QrD8VfDnjQ2709tHcw5sOMwA6SBxJvjtQptVpBLWp4QaSXVKBfx5/h7uGDgBlxmyrPAFoAMxOUdc7NG0E5EhZI2FDwAFzSf635j/xeW0NFYmscMsh17lDJ26fydYBQQu1ooejhukhvTtQ3gIfMR2Z6mEkQ2QNB8BK+HPqwqImG4V41TOVLJ59jCijmsePizou1R9vVr0MmbXdxFUgaLtscXIOsVthI4pj/7dR7RF+WM5x+0920IzqZOstoxgqeNSr2ivkkgNxeRvQnLNGCubNImwis7ko/0PMr7zJ1f9qDJTeFuCzynQhkbWPl0/hO5FoQEkTdwukq0ZWMMPcMLrMm4q1w7SFPkZ8Cf0lFn6ykSfdJw68iVkeFRm+EanPTZuMRMbb73+WrK8fjQ5XIu1rpc9bxYQ==,iv:t0sP+KBmXi8vHCdOo6nT9wwuiLOvfk4BCS15hxW5cnc=,tag:9SI+7utErMGVFkEBq5gXhQ==,type:str]
        uniqueKey:
            alg: ENC[AES256_GCM,data:59fy1fLQTQ==,iv:OK/2K0e2vKpbGl5V1oFF8zxpJ0EXF2skD6Nqt8AgmvE=,tag:w99106knAOo3v2Z1WuC7KA==,type:str]
            kid: ENC[AES256_GCM,data:CvpBztONKJvqYahpRmA6dqa4WDcMxWV5zhY=,iv:2sD49nppa3b0X6sf7rmB8BhcNLCJ+qrcDVqFk64nOPw=,tag:rlrxReJSwIAQgsgmlsmHZQ==,type:str]
            k: ENC[AES256_GCM,data:gDUUIARNA0CFKd33l8jSlXFsZLMB+A5ZsN4GFMX97yM7E3Gs4EdFcDGQ5g==,iv:bWlGLW8lyiO9cmA5eJ8Li2rejvlTjXM4IidzpNgL8qk=,tag:etFbk/z7RueV91iRSLbKdQ==,type:str]
            key_ops:
                - ENC[AES256_GCM,data:cc4dgwBSXA==,iv:5+I3daXhzsOpE2Lf9gjjEd4aLUiex/NFAuy1E14b7Ck=,tag:fbrwAWgAtb3qVXeK9PuTiA==,type:str]
                - ENC[AES256_GCM,data:cwVoZSIQmw==,iv:N6qEqXHzGVmr2JVpSupxfyu58W2O3Wyjfidk9uiCEoI=,tag:VjJLw1sHpxgaL56qOr/5Qw==,type:str]
            ext: ENC[AES256_GCM,data:kPd/pQ==,iv:aZYPWr7ePNtEpoZoIuVJ/0jK4hGL+gEBN5hIcrNJNJU=,tag:d9g49eBmf3iz25PFnEtFhQ==,type:bool]
            kty: ENC[AES256_GCM,data:2xGV,iv:Yp8HxH2rBdZlox10huPAxkPeMsfhdLwewchqk3PslTw=,tag:wgwfTPUAyoCkGSSQN79xaA==,type:str]
        deviceUuid: ENC[AES256_GCM,data:cwJjR+ZforgivzSTm5PyvDVCDmZGZq06Jss=,iv:DzUvaDHgkf1oYb/FPzku31VVKnvUWb9GlGu9mMe/XpM=,tag:mxU3d89p2zoNwblF8OOumQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZlV2R05PdkxHYWIxR1ZD
            VEMwQ201anA5YWJUNFRBeDJnbzZlcWZNY3hjCnBUNkJIQXBFdnozVjkvUjU4dTlE
            WUk5YyswK2pJV1l6QXo3T1dWeW9PRDAKLS0tIHltNnFkQ1VrVjE1UGc2SE1rUWFI
            c0c5U1RyUGNxTWp5bHdKUUVCMkg5Y3cKfPnuwL0COd5kZNLicdOLLYyTfxobFjjV
            k969kIKsNTESNQyG2IIeLFwGnpACiuYG84GrOiPDX66m3TmgK9uluA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T04:58:37Z"
    mac: ENC[AES256_GCM,data:xnMWMBNQ7bNaitabtgcBqqmmINN0dZKsOvf29A++VY7Hr8P+cP+b+nRKnwlslSUB/TKgJAxTdl453ZKVq+KHRfDWGqhCEXoJFyz/iDYrvdHKg50Te0E5yvdWXLkV7EAH9NfqmdP2ywqljsnbYtD153UKfomQP1yR3Gb3WWTRzYE=,iv:gR7nPAtBCZFe+dmb0FqqG6A/Y2c5zDIYUlUlrkEGbFQ=,tag:ODYXPa48KXeSToMK+BozhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
