# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:G3t18pK32VbPqj5E4Um00ewIffBagSqgAd9Zn7M7N/MRZsHfL1EFeczdmPsLvO6A7bvTWEgk8Ww0WZ074dPmKcd5C3Bq7HJh3qnKcZwAO3xnR2Bg1U0nxJP/LCpFRCdBuRQM1ojNFsJ/0nWsd4ku1Osj8+7MjmMmlj32rQ5VFvY4t6U3iP1LLvHS0Gn/fokmutD/LhHrzqOZVvcG4mT6umlkQGcwSvQlHLBdvheyEHwJm79Cr5IMFv2zlYPSms30hUCqeW6mf2dE0791Nxd+Pam+eULPQyI2tryVDK3XzPFupYg2XZRc9otYQK5BmtvwVhfYXiK5Pogq7gihIORarLVQTXvr4S7ZWcfMYjmnmACjHjQL971q7X9oiuRTsmxKFkwIZJGeCnxSDwnfRDUtqC2aRpkI8NnxJw6AghBczcxgM97DxvSRWQrRFo+6qn34FulO4U5aukHZaGbZ2d45fTJxqzaD2tZ0CRSd74V8WiP0uwtNaPgJWZF6QaUuomEev5hVRHHwz4oOs+j8jO609Tmi4yJuFd2a4rLrlqd89vaBYC5Zmn84lqrKv+AC8l9NbaesBOoTVuRoEa/yBuxP5biwvAq0Ujq7mb72o8OBgA3GiNB3q6M5zr9Vb9JlYWZv4UkQxrMlydr8u1ctDAdvil+5+0GSCICmarlXXMnZKNlxShfR/fMn4VW6lxc0UjxIR8QzcdUejLPynasf7w1N3ot1f7b+P7JpCMfrfbG1RTc3nusehTsrlkGxxsWToTamcT2WLYtI+YajgA/lSn/7RRhYE8sfT8GprIlz7CMWWzEIn5dSax3AJKoRqNbP7I/Izsiix0rQGScUuJog2Ev0Liah5yhM3Tq8ftceduLQcTGdBJNaAjOvABpbPpegVBfQySUQYuSsGu/uq5RSLog/k2Km/ogkWaFDpCxcEpb8voe3DZAZPWMjsknTu1sAfJbxkkmhFrjFntSz6Lfy8PsAd/vGYyrGf192wD453iZYe6aBJUW+Dknyr4vXX0YhhjMMV3ZL1q1QD1rPyqJXg20dlXiL13Cf+RSrM6O84WCNyjrRw9khOJLGcz8vmoNb3l3LDFJpmz7l43GZkO6VSnCjrju/e4Caux3yJQBahqMCP+KM2g5fveWYX+xFR4SvjM9kVwYR/v7ypPrRpidS6Ft0JKIxd3gkZY/biT8FfyISSgKJs8RbgdzJN0+HXwMDw3u+PUw7VKSdHxJI/nRo4L3vl5FITdPZXK1I+UlSY3pd+jMJhDX2DGRNedRMpE+jMaEVVUDj7zp/lR1qRMvIwnnm07BqbesbgawslgacS5sWOCH+I5kmPL4WiTZzbn/ouCan0uu3Q9x5KOl3ifR9QJ7ZMDk0x5Bz43kAyUBidT7Ww3uV2J4R93izdofpjnilKdujL89QdjX+wrfBnYFOjodKMMRaUfqOWJ+Ec4uKDnHLs7D9EDKheArw03V46z3NI/QfOnlvv51RtV7bg4yHh2V9gMTqZ9yu+TA6k0i95hZqlBdEE4Mi+Ur12oc2CD6PIkcmtGpRbh+HoG04fzAIL/dIa9GHlRdeCsLep/I3tD6sGzgJ/afclhc+mY47ESl5gPku6wlX+Yhxw3vwde99DSwW6ucxROqmQjyqUfsFbdurJ5zjCTp6oVGIHUvX6ONEt3iJ36juCHmSpwf/lvzsjWamdLYgzyDGrfSGepU7D/25RkX07zDiwVG+YJF/8jNOCfweg3kb4qPYN8/UD1OqB6GPyaIL3NKcen1/uNbK+qMmZ3VDvL5LfhmNfHnXSdjheAfn1SmksRsIw2jDxQSIQl9BvPCfyMOOzbp8LpKCbHUE8Ws0Jh65C/tle7A6rcRFuwne1VhJDmZd9icwcWGHjtNm5wYd+wxbP/eQwLznWakI2kjXRYm5C39p7X2z8WGaRuUI/aJQbPYxG7hrc7U=,iv:3+knTf3vgOjR6nIugFnN0If3GN9YGLWG6YGRyDXhA34=,tag:2X0G+lF2vFfO5hU44MmVWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0FnZEhnRytBSWRNcDRz
            QmVubVc1dHVQbmYyaml3NW15blhMOWQyejBrCjRnMGd5NUR2eXBGUXRFeDNXUnpW
            WDRHRFh0eDQ2MkVLeC9FVkpVNURQVnMKLS0tIHo1Rm1QdjZoUmsyWWVrcHBDNUpP
            T09MRGNaTHdsNUtpcmg1TytPS0w5VjQKcg1G+LgFf2naRQ60yrQNOIeHF/mQjQxj
            bK10M9BlMOAIJJw9Sipi9EVCnWZG4YJFA3VBsour96InomJVluS7bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T00:29:41Z"
    mac: ENC[AES256_GCM,data:hixtdTStSU4F5OFOhgLJqts4Ufk7vWfgeuzdBHF6VGOK3TNvQBY24GLvxuBMiw597JzmWsb5ELJDcaiRtInNMb43T91nts+bWthGBURs88kplsW0yFWTSfZ0B1LmwJ9sKhXQtPDz/3nzr2terwqINP78gyMoBMvlfqxE3CdY2lY=,iv:RObFaSny5cyMmsYe+V6Kb291xCKy0qmNrBmpBybrtEE=,tag:3udyYUdmnNIxM78gcIxmMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:tPboCWZIdLd0IYj3ihGr7Pdw9QQTe9DERupG85MWU5tFUcwDo3HiVsMt4riaRMzkuniqCld6igWi7NewB7hFUHpH9VIuireAoniNVsraI7LqlpG6BuamoqPc15nvb6gMbe7GDq1Ut+wxrbMCcfkBrrcTMQFPrrmXDBtqE3E/a7XK/Ins8sp1uTSAMozXd5jQAsm8yEvMVAz0i4hvamSJIdG4QmmGfD4mdme+sX4TS0vtIUuKoZDNYB6XSnW0znFsFfw/kHfA3L+R0Wf1Ck+LU49N53jDV3MQXSh8GBM2XXljaaqR678p+ssXDtQpfli5cPj9szng3wjxG8uOnhH3GF5lbOeVLCFKxWAHpImQ+xEqJ2oj5sTgC2q7jbhIyC+GWEasGPyKJFJKoN8z4KrhonGP35a2kSUzTDSNZ0T198YxMlR9bd3ESgwtW0I//sucgSTWB/k8F3+Xep6NLYdpsz8qwlSucVjG3xlymFoRiGvZ6psbTYAy6S2UPAFextEBhB8CKEolu5i4LpIpqdWj17urDeSeRSGoSc60QvK1GM1OK6WXxbed7X6B7eHetCPfnYU7n+trMFK3igAeZS8BRpXZTZVUo5MCYf6C/01o8IVHXCRJNHvch4ABLa/oWenU9jHNYcNwmA7oRGdm5S+R98oIaRvSq4YDXbRvVrOQv4+YXBxVM/zpNQgIAccLs+qKQGacDfUEQ+y1Ee7HWeavYQy9PKgTJlU30FZ00SLRKHaIcyRQ1gVtbwLml58GpX8zO2fQiHnngK7VtT2kvR0NMJ9B1ph7XqA+GwPQ77nr8ngBju/rlWSduzrT1qLffanaQxZGx+L9DdBsHIHO4doI8iTE,iv:zjLFzWwjzd1vkcHi7Cxz5/teztUjy0okc7f0e1Q/MH0=,tag:yI85A4h7grOlVkP9RnWz2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0FnZEhnRytBSWRNcDRz
            QmVubVc1dHVQbmYyaml3NW15blhMOWQyejBrCjRnMGd5NUR2eXBGUXRFeDNXUnpW
            WDRHRFh0eDQ2MkVLeC9FVkpVNURQVnMKLS0tIHo1Rm1QdjZoUmsyWWVrcHBDNUpP
            T09MRGNaTHdsNUtpcmg1TytPS0w5VjQKcg1G+LgFf2naRQ60yrQNOIeHF/mQjQxj
            bK10M9BlMOAIJJw9Sipi9EVCnWZG4YJFA3VBsour96InomJVluS7bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T00:29:41Z"
    mac: ENC[AES256_GCM,data:hixtdTStSU4F5OFOhgLJqts4Ufk7vWfgeuzdBHF6VGOK3TNvQBY24GLvxuBMiw597JzmWsb5ELJDcaiRtInNMb43T91nts+bWthGBURs88kplsW0yFWTSfZ0B1LmwJ9sKhXQtPDz/3nzr2terwqINP78gyMoBMvlfqxE3CdY2lY=,iv:RObFaSny5cyMmsYe+V6Kb291xCKy0qmNrBmpBybrtEE=,tag:3udyYUdmnNIxM78gcIxmMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
