apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:9YSsjGe7ONw=,iv:3hxyypgNOvH4FNwZUmEAFHb1qccnwevC6GOUza7OUQs=,tag:DK4oVKAcsZFLPQxGmfd7sA==,type:str]
    password: ENC[AES256_GCM,data:kw5bZIWA/H4=,iv:UAkPC3yCR1OOcWxrIiCEllA0ghaXvaxg4UjRfXpShYw=,tag:YOIlXb6KnMNmNOsB75YfrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRlRhOWkyREVlRGhtNHI5
            NVJrcEY5VFpCbWVNc044SUFkMDNCMUZaUlhBCmN5OEhKU0dlZ3dTYzY3dXFMZGM0
            QkREL2tFZWdTcGRCdzk5UVFIazY1THMKLS0tIFZjN1NVd1FRUzZuMWgwdnE3T1Q0
            UTRVRTZoRGZoWDFEcGVBbnRsRitJejgKCRaB8+lKt9MX0tksDUmEDGuRc14rSs/i
            ra81F3QqR50K79/DZfWC8RYG4GDPRLBGsYPny3DvUAbTr8Qh5VD/Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T18:39:56Z"
    mac: ENC[AES256_GCM,data:b6qa48NBMdZcxwzeH1Q1My3j0eoDSvVd/4g4uQymCQ5U4e0DbLqDB7i0W+gtcT4a6+4n9Y72K4oo3IWmLcVRR9aF01TlhJyXVmkjHBj5ZOVnRvyacNoYGOrUSDcYVd8cNKi1caboJ9RjsHSHFzUtB9KGErO6P7FuxW55jhRY/2I=,iv:1jFtjImPheayV/w7ulfbwa3a4x/8oInwVN2DzTA0GRo=,tag:IfMOEL/mIMetsMTT6sSpXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:bvQiV5kf+cxWE3TaYXgU8g==,iv:1tIxfjtomPrr10/l0ycc/1xo3PzAco+4r19bzb3+jZg=,tag:0bq6jjbB2wbwpSE6r7i2AA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:SIN2Qnz0RopghUQkP2/fR6hGFmgVC088HVgGaIukhqA=,iv:L++U/qHePz5TW8RudALOoK7KQgzGMKVwplU39sqBJPQ=,tag:AywpoMVtxDhk9u9nPo5fgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRlRhOWkyREVlRGhtNHI5
            NVJrcEY5VFpCbWVNc044SUFkMDNCMUZaUlhBCmN5OEhKU0dlZ3dTYzY3dXFMZGM0
            QkREL2tFZWdTcGRCdzk5UVFIazY1THMKLS0tIFZjN1NVd1FRUzZuMWgwdnE3T1Q0
            UTRVRTZoRGZoWDFEcGVBbnRsRitJejgKCRaB8+lKt9MX0tksDUmEDGuRc14rSs/i
            ra81F3QqR50K79/DZfWC8RYG4GDPRLBGsYPny3DvUAbTr8Qh5VD/Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T18:39:56Z"
    mac: ENC[AES256_GCM,data:b6qa48NBMdZcxwzeH1Q1My3j0eoDSvVd/4g4uQymCQ5U4e0DbLqDB7i0W+gtcT4a6+4n9Y72K4oo3IWmLcVRR9aF01TlhJyXVmkjHBj5ZOVnRvyacNoYGOrUSDcYVd8cNKi1caboJ9RjsHSHFzUtB9KGErO6P7FuxW55jhRY/2I=,iv:1jFtjImPheayV/w7ulfbwa3a4x/8oInwVN2DzTA0GRo=,tag:IfMOEL/mIMetsMTT6sSpXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
