---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-config-v1
  namespace: monitoring
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

# storageClassName: longhorn
  storageClassName: ceph-block
