--- #
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
# - ./sabnzbd/ks.yaml
# - ./openbooks/ks.yaml
# - ./qbittorrent/ks.yaml
# - ./rdesktop/ks.yaml
# - ./vnc/ks.yaml
# - ./webtop/ks.yaml
  - ./speedtest/ks.yaml
