---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloaders
components:
  - ../../flux/components/common
resources:
  - ./sabnzbd/ks.yaml
patches:
  - patch: |-
#     - op: add
#       path: /metadata/labels/routed-gateway
#       value: true
      - op: add
        path: /metadata/annotations/volsync.backube/privileged-movers
        value: "true"
    target:
      kind: Namespace
