---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbooks
  namespace: downloaders
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: docker.io/evanbuss/openbooks
      tag: latest@sha256:3b3d34d8b77e8261df1f470e1ca8344c035e316a86667dc7c1ab2e768d6359f1
      pullPolicy: IfNotPresent

    podAnnotations:
      setGateway: "true"

    command:
      - ./openbooks

    args:
      - server
      - --dir
      - /books
      - --port
      - &port '8080'
      - --name
      - openbooks82937

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: 'mdi:book-search'
        hosts:
          - host: &host openbooks.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "openbooks-tls"

    persistence:
      books:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: ${NFS_BOOKS}
        mountPath: /books

    resources:
      requests:
        cpu: 10m
        memory: 53M
      limits:
        memory: 53M
