apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:VmcKLi6atlgVgHf5de0PSJh9a+TgGnMh09BxPCbb5gt3ETMjNLzynfwXMc8NurwlsWLAH0wM6laksP/3,iv:Ld1f2grgB86qJAsFWn++H9xCkgw6K6Vc8K5CZFJq1RQ=,tag:I6oOeuhYM+kMPiQf5MSH7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S01mblEzeUI2bWFLVk92
            M1pZbGVhcHgrNWhURS9nOGsvTjZZaXdNbGtRCm5GdXNVMHFMbG9EQmpWSk9WWGJp
            SCtMSjZiUzB3S0Q0Ti91Q2R6bTF2a2cKLS0tIFNFbno5aFFraVNha0FuNzNnaDhF
            dVhzT09WRmR1bnNQeTlQUTlkcUFidWsKdx+4B4L6vZIKk5SMrtjWvcufnLT6m+kI
            HxjuBZsHF/e0D4b2XGs4LBEDDSbA2Tmn/BM8u/S2VHufCFF789oUYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:52:33Z"
    mac: ENC[AES256_GCM,data:fzicj14El5mK/C85skAhrYno8scGpz27uCw+KViSBPxE4CLTuz87WJ1h7Uir+b9CpMXEbGmL72HivLomIn0AfSAnhszjc5955nt17IlA6ddkBfsUquUfg8YgewzCaIj2JIihGPi09pKj47t55rp3rMTEDWNCzv9szUbH59lrp4g=,iv:lpTf7KT8V2Clw0m/DKJURQW5OSDDZRiVEZHYtqeTbW0=,tag:Ujfhd+tL4N8JtceJPHa4SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
