apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:mk0n54j7s/JLZlXTUYlwaAxHw7ndtnAnaLfNEJ2tJmn7q+TbXNYSwB3KJxynbINmMaGbLIGqlnQ1L8R6,iv:zfhKoY7jaQLDSblM/FxM+x28/GdQhx6qYsA3nypSap8=,tag:tweSmRJmK/pLlV0cTnYsVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZUE5ZHFtOVpwYU1XYm1h
            UGFjWlFJaENtN3kzbjd6ejN2UG16OVE5WEFvCkxtK0Rjemo4b2ZKbFNDcDZMVTF5
            Vk5TbDJUV0Z5RGdhem5zcDJRRklLdEEKLS0tIC8zWHVjeE1yNHJXRW90SmJ4dVRa
            ejIrMkE4TVNyWWVhT0xkV0JodzBWZ2MK3vHgR0jqVb+7wIPezJHUtv5NnCRycJRn
            Pufyba9bi52Xo/9B/H/ngistW4l74Qapf8ysd1bZEFtJOKfz0vzKqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T05:02:11Z"
    mac: ENC[AES256_GCM,data:JW3N6HLq72TwrhNa6+FMoloVORcwfhTzPTfImI30xI7u6bRjCzyMc4Ai+z+qNHei5t9s9VYwiAttUMgQE2UHNfv8Vo4584DrO8Kf5cQyy7EL8jRERHDtaPvLfHVvzS8VnwrZx5frkAjdIC7tqc7Qy7X/Kcd7weFJFoV2BSffyGg=,iv:1JUbrmZq+yaoPQ3FA8gZ7FKxBkyKiUn9vTC37Ky3sfA=,tag:jMAjpG4rFmN5cf5SlnFGzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
