apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:4EcBx3n7keK75eMIwyZ/7J4Tr3LkY1yamuiOr7YZOHT0VabR463H6Uy9f1STV6/b+uuDYdpHFKND4EOW,iv:HoaxpY1mTB6kqn3Cfv5w2+Y9WBdZteNa6F2R6K4BmQU=,tag:XIDWsEN6/0RiVoSrXud+Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOXhEQzR3TEhnV0JsUFNS
            QmN3cFl4YUk1cXRsSXlLZEI1S1A4QndnTjBrCkN4SlN1VU1iY29seDNONFF0M1R0
            TGZ1NU0xYUlKZHdLRTJwRmJRS2doTzgKLS0tIG8zNGNkNE9xQThwY3p5QXMrYWRq
            SEJocWo4eklGS0V2WWVhWTlxOGlwQTQKZb6+kh6ipKJf22udRiLMXOrQjZdWoqOp
            afH7+knYkpRFyNiwu4LdGuv98SyR2AnBghrIZBNC8V56PbtuCltwcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T04:40:54Z"
    mac: ENC[AES256_GCM,data:fvIn3IMzXKNJGaaPMzyywKuEbSkQacY6PIw37U2w1aYNcyohfRA9aLNh3Fzu6wQ6/aXKF9/HJXWGSRRniKLZKXZKnuQm8TKxi5gfgKXyLCq1viHTwgSXjjJB6nT5/3NmtQ3uP0rSTLJgrLLn8X5XhSC04uSAWwa1E7ptaTpetRk=,iv:fJPoyR+Xr39maPi9oNhuYJY+8lBHOQZefgvWqBpaQr8=,tag:/He5V0BAf5ioJVD8RqvKqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
