apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:P0lH4Se1xzOOsQUXAWaZVan1cWI+LLbdyBA3+7bPMhIdN192Hpqpgg==,iv:kHyIjv1Wn1VcLoBRxK+IGfloLUJxHVMY7y6UgyzLa+A=,tag:uTCaRQsTVxJAC9AsEkOMnA==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ1g5TzRUQnB3YkZSNndj
        K3AzdjQyaEVCdFB6VWhoOUljcGpwSWV1UFFnCkgzTTBCQnpWMS9BeDlJNUIzQ0Qz
        OWdzRTJBcHo5azlwOHNPRTRSRVNUYjAKLS0tIGdJcnh0aExHUnBrcVpOV2hRelpp
        VW5FYjAyTDNIWnFjV0FHQjZpcWRFNDQKQr9xMfSaksd/NJ1rUnA1DGZPNxSi/k4y
        RBD1yen0IlHYw98H/zwFHHAXyCswPIGh50pyrMCBwDKco0UuQmHlpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:18:06Z"
  mac: ENC[AES256_GCM,data:3siEzWnHTsjuNamheDcsp/mqyLmcfqv3ESNdav8dqNy4OgqmS+BEacLWz7pXcFSPHNyjjWJxDg8zS8lId/8vyZ11knKxOxFelXa4kMj9PQ49eQDn5iOjzawpAsFG6lzh/5Oj0vWnt3VjffGIxf71hdaJKXBQEnr2219fcXBOECI=,iv:0vOCDIbPkFRMFl7qKvH7E+0o73+w5dxgsAZ5L+w2qyI=,tag:XCIaCaOCHQoxp/IxQ4FWVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
