# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: whisparr
    namespace: organizers
type: Opaque
stringData:
    WHISPARR__API_KEY: ENC[AES256_GCM,data:SK1IoJQ7LrfMkBMdrkQEF+6Cqsl6dkYSjN26aRuO3Sw=,iv:AwWt3Xf0seFZ7kEk4QWwcf02PSd1BP6wFbNQ9V9QfoE=,tag:w58eHQuauImtZodLzygPqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadHRJVG05UklkL2lCZTc4
            Q3lUTmpSNko5N3lGYUt6MGhXdENRdSsrKzFBCmdhdGlpSS81RlorZTJZZFllSTlT
            TGdIc09BazhpYzRHN1F6NGticUFaaHMKLS0tIDJzT3NrdTdwVFF6RG01aDJybDFT
            RHFLeE52UTdkR3h1eEs4SVB5QjRoNm8KOTz4WtGLCuSGl830/vDVAq79KnKZAUpp
            0vhigAtWkvN3vT5jpeFOQf2M3t71oc1x5dJKgPu75a8Po0Txwko8WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T23:09:21Z"
    mac: ENC[AES256_GCM,data:DEsBS8oYWcfrm1KwQagihjNzwT6jElpzkjUpxZKnl8qbeiyUMKfIA6GSoBj7x3u7RQO50w4T1yftV//a7T6+YoMR1e5Dwh/CsuJxSezVP2j8rmfak+ZF/Zv7cB9psKVXpLzWranjT3NfL9AmTJCZia7+DI3JhgmCo4pL2MzH/Wc=,iv:0kcC02uTjIxFMs3uV62//8yOT0ZmwQuRCjot64ud26M=,tag:t+i6JqF6uNErzQJmtpk+7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
