# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
stringData:
    ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:YnduVNjGcI4GpZa+UDnqcrI0r3xaAuiS9YZqnLJeHxWFobXIeSrwgZrp+SJjYAotoSzp1VDJscDaOUkMDXq/UZ0LGDzF6bTHiWB7WvdBotb4zMDaQeqc9d28Phwo9POe9BEZhPYkTljONI/7kWqq+2qHJWS4IxpI5J0cYDbGUQ==,iv:UB+0Jq16X5e4Ng/9IUooebabGoQY2pW8Y7Mmik88FlE=,tag:gat6N6FAmQOBp8cHpwpl3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK0xTbEJYOXBnd0pkWHd0
            QjkyOXp4c2hsVnJXMzV5cm9WY213RmRBT3prCnRnVWFmQmkxaTFJUlNxN28wMUhK
            c3pWck9BK2p5WXBoOUdsUDFMREVoZmMKLS0tIGp1eUpzbEE2QzN3b3FQWXJUUDdq
            R1RUMzZEUzJYN2JDcU1LSEMyMSthbnMKxE8XFk5Q2rB1LS+1atrMB/tmqT92GXv0
            zdtzQ2ijQs0qts0U4R7NXIVm7B+RAwpBb+UGWMjstDZinXf7ttuvWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T07:08:04Z"
    mac: ENC[AES256_GCM,data:ApP/+jBLxrKtHBt8lLasmXLXfIi1h+273gMzXKaV03XsVwG8hF8EX8Fhl3cKZTihY+OGjVFhXwIQIOfhrur7vS2xlOvhoF+tGzYOKMHrx1z1QKNaTv4lbCU/arRlTmAIiJN59XY+0oFs2XBMq9/OFzShOkk5SC/pICndSwjAcTk=,iv:VanId/BdChgSVdwoF7lPKee+dBr2z+9SIVP72WSVsuc=,tag:ppwuFVJA27PjepbERb/+Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
