# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:LcorVZyY7LzuB4M1nd3AKEG0dkcn0Y/3AWUEBCiiwrs=,iv:z4bsDiiaSAHrrFTu9sLXd1FTBx+oasfnTHGdbF3yXR0=,tag:e4VH/tKfswG4nPjXSl2Bng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjFIaWVpRW9SYXAxeWFR
            NFNLN3lWZUM5di9YclhWd3ZGN0I1dFJMZkRnCnUrZS9XN0Y2Zjl0ejJ6ZnNVWk1F
            OGhTOGwzRnpZbGJlcXpvcVN6Q0Ivd1kKLS0tIHlDbmZhVDA3SHg5UFNwYjFIdEM0
            dWFqcnNDLzRncXZMUFNmV3k2aHNXRDQKztNxofnup5tUMUFzcJEZGVGjN1YjMvKC
            zjGMsyotOmrw5LLGhp8qHM3z1T3o5S0IexqRi51z2+HNcn/Jrhj0AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T07:09:42Z"
    mac: ENC[AES256_GCM,data:5rjbfTfcjjvMyiAn0zUZcVT8/ThT87Wq+p9Nz0YnuIyVFxzeTYnNiK4EJoqE+HRrBku3C8SaOpWkf99btWbaNWL6dgn4vlr8RLQFr77LxoACUvK1rpan1KgSpps94KlAE9divpd04dZoeqm8txRhYFyA534eq0D6BTZ6Hr93Ij8=,iv:Mu68eIA6jkc7mFrQeHmIEzbCMi789T91Zn267o3D5lY=,tag:PvlGgGwm4Vu8qXRNsvZHkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
