apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:f/wtBguNW1kMKo4=,iv:VZugDpzPpuuClwPiqzsb1s7HoGj86gF2PAaFO1B5DQg=,tag:r8cqbiiTziYhPmv2ahFUwQ==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:eWzAokyhxpK7jg==,iv:Yggx9Qk57s7rslxpXZoh5i9OP4v4MZ9VKnutsCai20g=,tag:n6f7F+ano7IYLSp4/vmtVQ==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:p0/X3q3wwoZ1lA==,iv:l1KstoDh+sytEhjk+8XCm8pjiezQvkxyJNkqGl+uAs0=,tag:Y6LX1SYJYzBQhm82MJGT2Q==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:f9Y3NFZi3TUNjQ==,iv:Bm5mk0dRHFCu/xCM6bbd4afNrMeeL/MzW4b86tc2YaE=,tag:GIkE561W5XM1f6qnp2HSuQ==,type:str]
    SECRET_DOMAIN_XYZ: ENC[AES256_GCM,data:rEgoE7FaMze24rE=,iv:ewL0TswfPLPqeSnd9CzVDpcduU5e0Zmp9dSpmuT2Cuc=,tag:Ap7S1tksojiZMcQEamBDpw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2mFpwvxC06DZgF1TIwxdGg==,iv:a7jXqf2ArnxTpdjjMI07rLD4BMlzlmsUrGG7jVxDpCM=,tag:PB+Ru2aoWmuazj2+whXwBw==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:qC7tdZq1L3HdsqVT3cVexdsS2wn7cIi7mVOhrsCoqLnOXHI=,iv:yx2vgo10jWl/IBCvj11dLUo2ey73AJ3V69emCSHx1cE=,tag:sNZLq1RjMjPt7I8pW4OP2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:7VzBS9qBsGW0Y8yhNODU/Ww2rqSagcGWIPUDQxipFqfhp00/AZlMmZl5z1bqdwOmTPPeNiU=,iv:phCgBYAPN4w5vn0AgiUyvS0GRwGPSzGeXkcz/GxZVco=,tag:x3rlVkBk13XgSdd7L4tkRw==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:X5JgfkBDFPU+VZulmWzT8A==,iv:3dAEB4rmES1PKC5EyTixG4THL+147oEKUwLjsa7efV8=,tag:ROieO55aWbaL4R1Ursw7Ag==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:MbwHeJ5IHuKXn0M=,iv:MNs4JtZlQNBfI/TlVitG+899CPe9GGsUBKxU8YDNfi0=,tag:0UF403WBH6wVkivyzq8UWw==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:E0hQh6je1BekVQ9ujv1XXjgnioW9/boGNIQf8IQWKgU=,iv:mxIylbgkJZ/qpBDOl+2HScJXdRSIQ8oApaCrKsyNc4w=,tag:h+YNEVA+o7D4QNmrFXQuwQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:FLfKQFnq4cw=,iv:0BtRPk338lK9zwXI+VBGLjOdXPlriR77QlPqGSvOv20=,tag:IXZydMBAvzg1ivWv6jqZlw==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:WuPrftmuoUixh3uh,iv:Ewlvr3zRt5tDn9k0A76YSmeiRxgltPUOzm2LQCJpzYk=,tag:XuWcqjOQIHHdsIR8MLk7Ng==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:P3yiTPAwdvEkIkax,iv:n+EsnEdw1gN8ESY6pC3fLZvxefiLdGGPDGwUhe6fis8=,tag:/e0YVZik072gg38zT9FJvA==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:4yUbrK8=,iv:w/X9xQk1DoNEo0fpUpSdHJiAg57QxJjekPax2lFftWM=,tag:V/RmLTDOlv8Xydz7gPiLIg==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:qQOrkd70EBRmWQ==,iv:E1epaADeUCWToTz2A7laYRTlmOGNUqi3XTVpfDRB5fg=,tag:gJ/hnaLXSWS1clOIaKYpvw==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:usInHHnfUhFx4WZRtA4=,iv:CnEQOhjJRPRe/L9yzB2kXKtSV4VXGQEU20OP6yS4y+Q=,tag:77oU5AeuEbJvWBXQVgQxxA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:c+vULnxReWg=,iv:syPVluTXpEqn5SBtzQg1Qt1Bb/cBHd74g28OiSAcnhQ=,tag:2ZUSiCsHzSREmkhyunACMA==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:p8r1a4k=,iv:XnUa20ci5wzaHn0amtEkNGwr+CqdOUvvOKQmOslqbNw=,tag:EmZ/9btqjGsLPpOc71hngA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:E5Xklw1BlIw=,iv:abgTdyA/RcRRHxITieKpcHRIepRIX20OgKHNfAM/JSQ=,tag:oXbO/qJ2gwnC9A6MDVsI0w==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:YxsgGKCyGqW0eDf9X9A=,iv:YRcCxt0DMNzs8D16YCWMo0IC3EqcMMXzuQ1fOOKbmGA=,tag:PY1bn/0OffzZU0Nt03zc9g==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:Jie+YR7zdCM=,iv:4IFk0KWj2vksSyMMwEK3j4TJCSW2yrJCFIZkZjqM8XI=,tag:Qb/mXcXCNXOjrvtWEdEN4A==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:iE8m9cybM8c=,iv:DGqOTHoK7gbcJqOeKBug93pJnZfojtLw/upg4SLkyuA=,tag:XkQb+1F/duU6J921on1gMw==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:DYgdNao=,iv:WqdquZQVNC9WHsowmqvRgFS5dhEd7HjPQtfw54KZe4M=,tag:QXz2w84WAprA0SY7ktkLiQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:XB4QN1vkqik=,iv:MSp/tQqOHk+zlCCVfkg9PqlgukYlbwk/9o8LrxMm9Z8=,tag:7nIqoM8prJzkZZ5JwS6Png==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:3L8tHCQ7X9z6lw==,iv:eJ+D6Rt/pFwhxttBDzImCrf9rfiBO0jMCx57bgBF618=,tag:qC23THgQfce9LUxAnLfjGg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:YA+AFw6bVE+SazaM2Y4wkg==,iv:eXO4kO2PMUnGSQyss73UahQdsT1LTnJPflHx8Fwt0/k=,tag:m/TODRwsOI2wLyonh+Phyg==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:Cok1B6rLLNg=,iv:9w7wRB9K9xUullg+tS002JQLJOB1t1Oam9a6CvLg2jc=,tag:DumlcB01Gr6pDuZCtflDPw==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:zDGKv6gWdgHR//o=,iv:CJA3ObZdhsJKnWqMRcQBf+D1PKLugIMelASv9IlXWD0=,tag:ooxjKBYeEcMsQQRK9J9+9Q==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:mNxwonu5lS31bGjfEtThRAw=,iv:2E2sq3WqLV9MFWITyXeTu/WpWgmy3XxtTA4MwyvBLuQ=,tag:eIZrq4J7ioONsB5gjOJ4Fg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:G5/xMP8ahU/hwj/3lOY=,iv:+cBjPB3OXMrh8xaCHgBuyz2fSq2Tl12BAczfYvYd1E4=,tag:uK73bzYrJnUJpr6Ri1P+Wg==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:OXKlcTiPaz47iQ7Q3v0=,iv:WDs37sO8m9HkfTIlndNiDN8oQR4aschdn5DC2k1iK9Y=,tag:yrjVJbJHIkTV+DJPJN/1BQ==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:8CHB6C+nIgz2XVGoQ/Q=,iv:iKi0aaKvYv98SELpHbLBHMtw3lm2UI8WECSc4ezxBV4=,tag:J3js9V2DBIJncjCl4ouKjg==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:VCGahTXw1WxXG5OHVaGs0ho1Jw==,iv:TkSNP8T0bVSrwRg0PZPCzdkEhkpJ96H2S1LUtZU/BKA=,tag:LlS4lASEoajMqMSVCDpnFA==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:HYCLeD1zXy1ca7ZePbX7PXNX7A==,iv:/k45STZf5IfHouDBzA+w4d8rw74GbTdYEgThGxbNJ2U=,tag:BqGVpAFz4g5yC1G7N+ddqw==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:Ze/wmhjc+v/YqsPdaUi4uiRsCtfWyeE=,iv:g2cxcqZZnLMBsmhZvQAwLT+nGcaYg/U7ftinIiexWoo=,tag:CICtYDmOhKwF6Ivd5Xmn7A==,type:str]
    EMAIL: ENC[AES256_GCM,data:A1qOtDXOSM0RMwofTeoMVA==,iv:aRo8f2RBf4u/DahqEnog+vwJyc05QI7jyORZdmTTzhQ=,tag:h/lrmaQm0PDAUrMWyLRRKw==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:KrpRNN7CjpnoEzyGEHhxQ5xxg/eV27I/+K56,iv:IZOx59RHw+xEbzPXtFwbmfn2XqRtyZz5nXqy1cR8CuQ=,tag:QWMMaoW45kzDH16bWEPuPQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:/tE26opznEAkKdX9huMA8Q==,iv:xHnBZg09gxXDTT8zFLvlDxv52RD7Lwbd8QKaQTLdQ1Q=,tag:ONpaC3oyDvg8xEjQ5WundA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3hQr91dT+ZVuf65cfVmTSs+WUWup2fD5kdw=,iv:k5CVg3zofBhrDUlGCbwYnkJ6+DrB5+tHYjeW2LHUGhA=,tag:bEYFAc7naThH78F87lAOiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL3ExcEJZbmNCMnNWQ0Nh
            ck5hajdCaW5xTDdRSFlwNVF2T0FOamE3bDBvCkNUMEI4NzR3Z0p3cVpqcUxDZy9s
            UUVtVGxIYmdCQU1PbmhSSHhtN3JNSkkKLS0tIEdhWmVUWUtpcVp5TjE1TkR2ZDVO
            eXRWTjg4R2VPQlkxdy9ZWEZwWnhsM00KhUIBaEimnkhx07giLrFZFWG/wcmRuGS1
            TRY20sC3WIRGTInM3u1E21+PNS0SxzhDs2usSi9eCS9LkM/vNDDesg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T01:06:03Z"
    mac: ENC[AES256_GCM,data:pU1EqjcR31K79zL5bQviu+v5/ZrwvubWMy8LhwzuO4ARCr0mQdSJM5ACTOEVD6HIOwPvAkwxXM1niuIpBERF/Fkk1H7GM/xM1QzRYBp1Adl3/iVY+QbcU/C1cKv69KyuhhD2/NZYeqdvJOjWbzdffS2oEDNDen9eojnFTxUb8RU=,iv:jL2oQxnwlAEzPtsFemPRQSCpUcpAhOvvXvtPFGCuB+I=,tag:z2kETZgfG0wSP72lh+9xFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
