apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RDDA4pOAUBmYdPM=,iv:wr4pOQbS5LET6qUZqHWFbml6tECCiE+zDAUK6Crb1+o=,tag:lcEX+KWUUVNuCpxgfJ/4Lg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YwSjeeW6kQWQzGRw2alI3A==,iv:o0yX/9NZ6If9k3SyGIUHUr+f6zxJJzO3gpaj2rrF6y0=,tag:Dcpo1YqKrP1pituzAArw5g==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:ZkdXYW9HlM7pQmT1,iv:gjWT4vSmLumXlKoTB1xNOEseqYEHZtsydLPfvksdtfQ=,tag:Zfs9zFlQuH44/5b4kluN6w==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:XViB3PvY+Ennag==,iv:v/9H1cIUVpeP0ZW/KBOF2UDRRrwRwmw+Vk5XafQ/vEY=,tag:O5UBgB5s0wcUUggczIOrRg==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:uQ6U8reu5+kw/g==,iv:5Invfwu8h2paX6kCu3xJXNL3HOHqJC+JmtDmVdGz5fg=,tag:ykXw8AtE/CQaKMvJFU5xFw==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:PyrJZPHb5AlB/Q==,iv:lQQaxuVqeZiHIjM2BdofvLrJx1wkbmRw7gxDc3gi6Pg=,tag:1++8FExOUrnlBzhy1BUDLw==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:ZtmV1QH40A+a4/ts5Q0XeEE8UFM/FfEa9yOl,iv:FrIfcmvx8QbTNIlV8ypd6dys/GvfkJct6q1R1BF7Umg=,tag:4cTHcW9WhLtLUu3w1lvNSA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:3WFe/TxWUZCVIqFhReGpVw==,iv:gsOBW7cfNFXYTkcseWWzmvPDQCoO9iAuv1AoKx3H+6s=,tag:4tGmunxuepWPqBVxBF0PjA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:zMZLA8fwgvdjdBo=,iv:roSZwfeXXYFApBkdyZvDfmsiFp4b+6D72gJeZxARoZ8=,tag:HyEjiAK22B0NiQY70EYAHg==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:mG2JsFaP2Vf/KnpM1qT6IiI=,iv:hzJW2Nw7JZ2CyZCAfs4w/+Yg76lTC6u624/azAbVle8=,tag:Wo+tHpNoPbPkaqRk2TBsMg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:Mh+6TAmTu/GAOPZP3rQ=,iv:IesjNKS5BVHgqO3sQqql/btqSc3e1zIkcunVwjet4MM=,tag:9qirW/Oh7tfAJvDl1ML7Yw==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:R18fcQIVnUBYWuucYWs=,iv:vaRehskHu4b6QKHSf3KLeA1LGPxlRPCPcfBHcpUgLY8=,tag:rCVA2Ryi0IaFj5PEonLigw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:AP6K52s7KBdrKCsWuXE=,iv:ynSJANGM4cI5dzGD+b29arXoV7u0/TyLiXhBpPueA6c=,tag:75osqHuNq+iUzTcpUUSzUA==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:xxuwqHSsmCjWMPFJm0McratUpg==,iv:HO61D4Qkm3Dyy40r43wmzuPY6XRfLI3+Gkft8MXtv28=,tag:IAhTFTxC0/LDmXjj6ZA8oA==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:Ff3V/VDTaarzAuBw9Frp/6AgfQ==,iv:fl2dy4OWuh5g+/VS/oZYPfnwmNdbC3xAfLQiRA8Mygg=,tag:BNUVePu5pDtMoHRhxabtfQ==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:mVZZ4zfjpKeo4aXS8N9roWig3H/YPOY=,iv:7ij7sSwYq9W3Lu+Tj2Rgj3FH3RAqWF14SXVnjrk21ao=,tag:DRSZS+CTNNqcYMNMhUw+yQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:1UdIMdseFk0w5bL6zZ8nzQ==,iv:JX1LTGmHaA1SN4bwQaCANuEdgotYe79GLTNaUEX8WPU=,tag:wV4RxXNWHWk+QJOnupjRDw==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:5biaZsPlL5qmfXOcoNueMAfCiCQ4cROX+09X+3qX12WsBr4=,iv:l0fZhlcEhJvNUHQouQ9wz0LiwIx0juqjGLO7fO6PoBU=,tag:J81tgSqwBLe6/IkV2e4N8g==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:S+A1VmZFcxf/NaWZ,iv:JVeAGCnJgg5CfMk9S0ctFtRQSnPqJw5ghhiHC0pARKc=,tag:yxMo2Mlh57dF9WNONJHUGA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:f4suuJO78tLAYibr,iv:/+/96nr+Q73CXqFAfw11+Hi/rjeV3YlJu9yML+QJPnM=,tag:sjfr/2SfhSzvVF3iQpZYfw==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:80dYu68=,iv:Q9u2azSTR0C3OX1m+B50ZtH4B8KcVgn+sfNAYR5xWQA=,tag:rpnIdujFb9pPekhQlivA2A==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:0MPifIYIXnYCYw==,iv:hUi62CRmHeRxHkPust6/54vY+zJmluNo6lHXzoftLY0=,tag:J87YAMxH1Kp9ub0xAfSWvA==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:yes8UAqWUdH4cBOJUmg=,iv:UIEfM9Zj6B8+r/BIliajcuOc02BHfs4Lmneel7IfoY4=,tag:WfyC/CyRCD/AOOs9J8E2VA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:+aZfX0kwWAk=,iv:UF1faoNBNCSkgF+ZvICdnVNz3okeul7fYeXkLfX1ZrM=,tag:sbbQ0kPkTqVbQs25sJ5f7Q==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:b12Rd6I=,iv:dEed0yEzbcSbAhZRpJKx/nxz4Z+7589RqPovCKqEvYM=,tag:/DhChEDNg66AMJsqx1aYIg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:q7zDtALO0ck=,iv:G2gsTzo0tXgh5/cUjIlqcHRPvhKRN4PlS33IDuD32cE=,tag:fociDweKOaqTRjVp4/GtUg==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:Dn+v7eQOzdLq+ydiDcE=,iv:c7uqwScXpflJlqyCcPmUF9uIAVe12h2GLUaa//+0v/4=,tag:LuseOraB2uQOud/XHfHH+g==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:x4hCF9ixidU=,iv:tCaXvi5O+kQB7EBUMdHcIXdURnG0jRRD/gqgHkSRKEM=,tag:QukJ5R1oSoefne7ysFN8eQ==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:nYyw9qplUiU=,iv:53WrItCQ8DLTeyirBvXJApwXI3FiWIeAgfYNHPg/rrI=,tag:RcW+xb347SoHpSMJFDHSow==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:52OTWKrkAKQ=,iv:f4uZ0gGATnjuiAOyV1CPM6NZPe7fNqRUnmXPADt6RWE=,tag:CYUvvouhbdminmS3r7Qlgg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ktEIyVbBmKJk7oXLlpkONzd7P+QpuWDuNAk=,iv:cJTLEpm5GUfq3s81QgHu6fOZyevQJZtX9DEXojidYeA=,tag:rLZFomZWkcVJjliCUSU2UA==,type:str]
    TZ: ENC[AES256_GCM,data:4YuunDbN3CabgWM/Gj2+PxdfeNY=,iv:WumySiitV2zfxOBfLaYi707URdhAwQIDE6sWuuEFxos=,tag:HeAU96RFCasKSOdQuVN0fA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:A4Q4uA88H7b2t637d2NDbcab9gPY1c848cmDuMRQGUG6z5D+9USg2XccIg1ar7bhzuNiY20=,iv:jEVpOgBr8XcDWbaGTM62EcSv80FsfnGqIKxK2TBjxjc=,tag:IgaIR7fPWoDPHOXZsZkB5w==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:NPFx5CX2k/AIxw==,iv:pRQDao/x1Ut4VgdhriYBkrIYeNbBCb2zOGU9YZG9//8=,tag:MSWKoBBrPqtKmiWYrt8nVA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:NBUWaJKCfg==,iv:+TYgGxkZjrkcXR3nQowo9cyi8b763SOv54AgIh7F5qM=,tag:UyyGkiLMkPb7IHHGQ73y5Q==,type:str]
    VNC_USER: ENC[AES256_GCM,data:iIFAzeg=,iv:7Xxlu2lhKFGfegMeoIEu+2jFuU6t1lUOjER59kIj/jk=,tag:VXmnG1lmrvqS+eybg9UvXA==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:pqKrxtiFwTY=,iv:vpNo4zjPPi4uSnlDnDBeUm3CS30OCuwtK3Op9IX+ekA=,tag:9C4GGgEgj1IJLHv3k8XXTQ==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:0c3IW+ncaX0=,iv:H863EUR+SOxNdAjl3ievFE1ByVvZ6b6PI3EJsLIVbE4=,tag:AA++WEa/7ilD8k9ZLyX6BQ==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:r7JkIxwRXBs=,iv:hzBQEJIdBq8AQ8TZOE2N6YPJxCAfDBAaI5K0rDsry1c=,tag:6IFe3QYtsPzWMK+Cz/3SXQ==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:pD83+/0=,iv:T8dOuLwvMLcw64yMPHdOcKDYH1mjBY6eUIvXpQdBBeM=,tag:vphiPcXY72/4knCfT42ZxA==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:LE8K/ooYT+Y=,iv:I8GXEhBv1nMIyKGV3u2SB5j02GRKgGLxrZXbRJ5fDAI=,tag:fMNkrX6iI63W7zJCCUWeXA==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:p7FOUHPICSXRXg==,iv:7wIm9EepQ52pT5v0eEVxVDw5qNj8G5O0hmZm/TbaMWY=,tag:TN4Juq/9ZFQuWogqCrN/Vg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:V2pLcsr7wNZrHhJUtI/weQ==,iv:lYneNQ4L8BJcaUcFlKZsVx05G71eFtVTEnPgZt1sfNo=,tag:Zp6M17O68Lk1hJIbexjlrQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:xTMQHOPzfEE=,iv:QXXu1RgE7Acrg03hp8u0ArM7Ib6PK+fHdcsWlXbABzs=,tag:q2/JUhB6ZUzwUnkSM5pXiQ==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:UMaOamHORCoTteRbj6V2mw==,iv:X3qSGvYKi9FJQyNLiFNfIveiwGBNjUAsejfEWedLInM=,tag:UcT/vVciNGOzx/HHlWvbTQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:tjjmaxV6b0PcAEU=,iv:Btbo6nIH1T638GXRNYglrPP9gnaqifvh/PntjqoGBmk=,tag:26gEZuM4O6QX/DLBfS+Gtg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:zHEZT0i0JNd6e33POOVQN+8Hbtl9Zon4bFE=,iv:ri828tAAAVCo34m/U7fIO2uqccvth9EI18MPoA6Nxeo=,tag:oDnpR6lLIXe/kiIQ62ewag==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:rSnioyyt3sbtrTT97laTg1C+7+io12ogCgk=,iv:NumkUYYeAvqRSPCLPRUKtY1R7vGhTPlaLODWaFFlNWw=,tag:/ogy+abugu1RkOF0FvsunA==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:3nwgvY9iiQ==,iv:Zlx5CuFFeAh3Tx1z5en4rKT/b/K++ppiqBhNqtJf+Yw=,tag:peXCQMXVPXPUxO6O4xY8DQ==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:muh43y9qxbfNvkjpUWYl+KhpVzz87wfk3DI=,iv:OxfT0cskgRBarZmiuOHsu1s8tr3sNxYV3XRMnIDMBfo=,tag:gkN+j0AHHSpcSHNqi/ckLQ==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:D0MT0lo9XddT6+Ryb10ptx0x5+Oq81Y3PRu53H8C80E=,iv:Nnwb61VEAX0FC948GC2VQ2wqd5ros2oEpw8aRaBBX6g=,tag:vvEVQGR7iYJKWfgjr5KaCA==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:WIq5ozm84LU=,iv:ARu3/4tDVMgvNFOeWQzs8S8bHtzW1judHkrQ8kxBkjk=,tag:EbR/t7WwbJyBT3+Ts4+8/w==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:aUcuRa/I5OU=,iv:vqyI4hp/kQfxnlROH/FxaFTAWGb63h0UzTOq8cnPs38=,tag:TZEJSFS3V+UDAyz+Es/rcw==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:hG/f7eShL8u3xsw=,iv:Sk9NdK8HRUkWO69N6/2erg1Y7DzaHP6nFLwQC7LqwDg=,tag:OG2KmEI7dZBFaUrI0VMDVQ==,type:str]
    QNAP: ENC[AES256_GCM,data:w2MSCaq71+tRk+4=,iv:ZMyXkijIY+7zn1PLzhSLmsFl0jy+J0kWJ8h6WM9AuZU=,tag:sSI89zWmctIBCMpPCIuGBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eUhmTEc0aHNzWk9vUmpL
            OXdnVnE2RDdOTW8rVG9sYnFoUmtOUFc2RGxJCkJpTlRCZnJKZndzSUc1UUhqZEdy
            UzMvYmRrcm9VTWhPWDFjeXBJWThWc1kKLS0tIHFQalZpZkl0bFJvRXRGN1YxMHY3
            MDE5WEg4UHB3czArS0dSMTMzWUREQTQKj6Vx06V0nLd8FI038F+e94XCZbU3cWWH
            OE/YTfKoz3uEY949/rQe6uxI2GrMVnZRLNkKNImfuMRfwbwjGgi9/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T00:33:39Z"
    mac: ENC[AES256_GCM,data:Re2L/E5/WsPjmbaY71UMymZPT3LGT8PRX01mWbXdTvwdAHgSRwYTMz2BRJxQ985Rx62K7+cyArze3EeBLMCUKH0IbaeWvEw2ijHXyw39z/IHCMNa9W+HAfnar4YnqfIY5t5u43WRjAShHymz+SmXTG0H65UAKGxBopdZ6LiiYrI=,iv:9cw/6KJ7guTlg08jihGW7M1U92Kqr2kOANUPR9lO2Xw=,tag:49r/L8ZAhLNgD6LIDiEVjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
