apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:b7rVaDujVgn0nug=,iv:aSZs21vLGoVC+gi6oIoVXf93GlOue+bmCmp9ecsZaFw=,tag:4I8kwfrDWQWMzfrF/SzYXA==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:bMsvBBAB6jSJXg==,iv:h1hRoigoUYgI4cQrKZ4g9OrpZyq5B1CEkwKL+92wOfU=,tag:3sdRWhhmdK53pvPfLrHRDQ==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:2vjRkN6DBCGBeQ==,iv:/PRJfDsbkGlwU6afYncKTEq9oDNmeRgkMDMB8/zSztI=,tag:wQWIUIxCzx5qvlems3qzhA==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:dwT0rTAxsb6bNg==,iv:sCMLRiMOA9AdhFcbcqYwbeAK6tyWRMwHNKuKh3OlC7U=,tag:ZSj2QfeCknaikXJyOqjYsw==,type:str]
    SECRET_DOMAIN_XYZ: ENC[AES256_GCM,data:+jxFaNgL81tw2NA=,iv:eH7zkFSS2eB8eygf+ygVU5d6Mwt4uIKVPb46e7SSbXg=,tag:CkPvco0PXra+fKv27oD9JQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QiazA0ACNpPnIpdlxzYb9Q==,iv:JD4NzOj0aBhAsakYnn4qx5flj2Gk5/KJoQj3P/ihrbE=,tag:03vHGe6zHJ76bRm20nUHCA==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:+z+Jf/4HRCN2QdSNHCXmv+IZnleKFO2A/cGciJH71JII7EM=,iv:rn/N76x39w7mQ5l4CqnWj1bKVO3vGJ6xJZ5o+EbfRFk=,tag:7TtyPMm7HF/Rpwb+y2+TJA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:dJTj9VnAueR2y5V1CB1F/ODDd7G2R7o55jDi+cmsFsyBB4lBn5DbCTII6uJEaFGL4ffUzhI=,iv:fnQG9UXj6Lh6yqMnQpW1VYbHFna+5GskAU2nt1zeVBQ=,tag:nI5HnFHO9+RBLkGdc4tPwg==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:XvHw4J+5V1hEO+xo+e0usA==,iv:I7LbexzyxSi/TUg4IOcMvmP5DIw/oTYWeaQ9YvNjx+4=,tag:4zaSWY3X/XiBy8WxH+Cn4A==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:NpT30OCiYPtqKxs=,iv:YuYlAnQZ5gc7Hsno63QkB3vNo7nUCg5HByOU48J74v8=,tag:BEWqmNh5VnQbJw7AKXMblw==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:+3v0L3nnT7cfIYJ5gv9j7NbQPoAlz87bzAtO8kxaxEQ=,iv:3m/I6yjtLIcHPUu/JCvfkl8LfII+RFm28aSwhe6VrCc=,tag:8OZkvxWoAHhKlGP4oGJbTg==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:r9I0B/mr5ls=,iv:RyCebtMEA6M+PIaN1ClrU/+p/XId/90Iv1rDz/ItWM4=,tag:FzoHmJAp1WvhETHCB0ynbQ==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:5iKr17ylQnwgGjou,iv:9uFmwUIWlj4J1UyAICxwNfn/M/9TNSfHRHzMM7fWMLk=,tag:QY4Tbc833I7bbilslEZyUA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:nyn/vQtupevdiVqr,iv:4ZTdj5+AgHyEQAVo+Mma7gongr8g5USYBZXOrbDFtXA=,tag:UC/83maM/MLpWYJCRJi43g==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:QckXIgc=,iv:mHzvMNFxYm0AWO7OXgb7g0sByJbcJKDltxIYDlnFrlg=,tag:ZIR33zKZcc83pGT8bc2XIA==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:PUqHx/tNqUGbpQ==,iv:XlTOPEUsU8maGPfJVyA/3Lt88xrx4f4zC9d6P9fa9lQ=,tag:aTbC9L+dOkGMS9PXh09MOg==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:h8miFXcmA92YzTKqCCk=,iv:DDaqAR3S+hGcfJReB0ZJnUD6FGspOSKT/0ATczS5w0c=,tag:fRiaZcTRee1t84aHIbkBoQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:I13ooOLPLUA=,iv:PE2+i5BGrwx5dXBQXEilfS+S4/LJ5AKU41od3ypvGbU=,tag:q81FRH0ntCxxHHXtUDwSXg==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:RcXF3mw=,iv:qMCT3cLpaoQKiDhpI1aVe50MnUn5m34qdaRWPxBsY/0=,tag:DrHSTOhKym5A2NNFP3q1ew==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:BETWAqJApS0=,iv:vEdnDgT6ZThe+1BxcNONJ87p1ZTX2rQWfVmjnr9NOHQ=,tag:PHfo97QzOui61gqCvNQzug==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:l6+06/V0d8IXbheS5JY=,iv:qfifzsiyYFHEnxNhzvXe5tiY3HWSxEDhPaN3xsT7Xw0=,tag:VdDYv11TZ+91ay3TpUSF7g==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ICGsFu8GriU=,iv:/LBeHVF6SY2L/v0pt373Udz2SBzcHMe9/j+hSlh3wW8=,tag:Pag1ilw7nG0Yjmw4R74Maw==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:37YnPE4mpNY=,iv:3XRjYoFbqxImxk2MI6aCvOQNFU318Kfa/5LoPHpmBYk=,tag:4uV2t3laxpRaru5EHKwL4Q==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:LYTR+gk=,iv:QvBinHNWeafhRKCuvNmHwkLQ7L6+WzHgmsalu2LgGl0=,tag:W/0rkSNawaFb6JMqe0GPSA==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:e8JA+y92Rqs=,iv:fWEKhuvvMCB7Qx4CFvq5dDZ8qMa56dYKVFe0oWpde5M=,tag:l5ncR62QTkXxpUqGq5AiTQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:T5qhYJ/7OWHZ9Q==,iv:MP377x4qN/NJWVeFa3k3cyR9ZSoCt3//uR89axCDCxA=,tag:rLd8/lanKkfJ0WO1nlNemA==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:gCRgC/vjTeM3ZuaQUHbRww==,iv:Eu425xIA9JQriKn7B+Uh/Jyp2wAHU36vEfvqsiTvjuM=,tag:/OyVF6dB3wJ9vpgCJoQ/OA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:genZy8jB/2w=,iv:7IJMMYPdAYFusoaMiABga7tCzzC/bcMQl8M1bT8r8eg=,tag:ppEyzwBUt/DZdn5cdDCBHQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:O8u+7yIHnDAWfxk=,iv:ZDVrTUrgmlJMrj1ldHYrtF9REzk539YStYwpDzon/dY=,tag:+ZE6DHVXmVeZecBFaKwORA==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:ay2f09x0VGxmTP+Fw81jvS4=,iv:Xsa59wT15QY44Fr/GFwiFuWDd5XOM1MY7XosT/YxDHo=,tag:+MezchtHI4/tGyP7VqEUBg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:MYo9bN4DZhLTvb/4bNs=,iv:q4lwEgykptCM/q6zRtdZfrAfYu8JONQS4Hq0KN62dk8=,tag:mDY2jOeV4go+wV1I9593Dw==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:jraf+DsgKbg5GXedWOw=,iv:8fWQKacviQFwkHzp1AbT78QMtQ4DewfHA+DJG+052S4=,tag:Y5lslIKNDD8Sws5hkZ2l1Q==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:mqhmO7dIYROMzSs5OaM=,iv:qX53Ftfsal0GSCWI/ItmGIpbQKkU1HzATEciUiXD9HY=,tag:6KWFcgRTYTYinVdGmTgkQw==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:VIjmQVO9hmMeHPBXFCUdMoRDgA==,iv:+siBZzESbyhdNrXPHKR0hLrmcuqXQFC56Jje8DglSPQ=,tag:SxFIP/nWJNEN9IsG3fLF3g==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:eE7dVnKAMM5WV0rTWUF0otnAEA==,iv:2yLimQl86roj8hLOlbE3+PZD1HX1gSEL5yURH6Z5dxk=,tag:tUhNA2R0G7PdeQzxGiDFug==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:1/+kSWsVzP9UbXNoUSHyKOwhGriaxUA=,iv:Bq7KwzyVyw5Di1uLKbF4Iy8GfRHOQ4bUg7QC6Nfzs84=,tag:ZP73uILEHjBi5DWWEr2XPg==,type:str]
    EMAIL: ENC[AES256_GCM,data:9xPXGVyFRQgp2VOawwMPlQ==,iv:BbOec8i7g7/swzrstovehQaFobsixaJ9iUPz12Lu430=,tag:QsqSl1EBoaB0iuyt+Y9lNw==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:BI5ijujhAT1BAVjYXckNC+47dM3zt9+NuYID,iv:1BmzgyDEBYFy9xBzIP3u1+Pcj5xjZ+b6X4Il4oYFt78=,tag:9zxJ0VpelpSyIiEZ53kiWg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:7Sb9VuKHXrAvEGNhmvKd8w==,iv:CJyta+rskwZNtG/N/uFZIvOQJ2ErjPZ99H9BPpSZVfc=,tag:26hESs3pA4USs/ez69a4Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcGc4cTZENlVLYXIxWFZV
            bzhIbUJTUjkxVzl1Rm92U1JqU3A4ZGMvNTFjCk85VW1FOGpja1BNWXl6SmZFSHh1
            b2c5K2FUQWxLUVJySXNWWFo5S2x3R0EKLS0tIG1jWEsyZjVpVElUNTJ4TGVIOCtZ
            RGlFLzVDUVFiQ2lwczV6MVlDbU9aeEUKUt7Sse98mLYfTkPRIeHTB4WZL6NwzMeM
            nmF6+Bke6nWTbqPJ8OrLdijOfz6RFGnD3ORTBH2+GKOgLoEco0zxiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T08:45:37Z"
    mac: ENC[AES256_GCM,data:rpiVB3RF+6aRtNXvtv35qprQlteNTZTVdpUqPREo7Fu6TwfT1wfHsXStXj4pojLBdch9is9MY6cuqPa2gNujWmAW97xITinup93zxWKIVZ9eYgS6FZGt9sWynmo7EwkwHWvMlQZEksBXCTI3TCMNJ686Q+0uHKtBZQWCtZaTSmA=,iv:DqHV/AyE2wBoUSMIIQ/+P/HmK5Pqtlhj6YoVt0yQM1M=,tag:jA9StlCXy3F5/NOjNt6F7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
