---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# storageClassName: longhorn
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-generated-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# storageClassName: longhorn
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-metadata-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# storageClassName: longhorn
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-cache-v1
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# storageClassName: longhorn
  storageClassName: ceph-block
