apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HODjgS3dl0OC7/s=,iv:5goiQtBTNi+ry0kufi4WyuhppD/8t6mjJZR6uoDIaeQ=,tag:SCbSZaZU9VhupCXtNx7RhQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vey/p1brS4n+Vhl126z3HH7H0pIjJDNxRhabLyzJatWUB7L3,iv:QjyRzVt7W8jrVMcaV0an9VIYoLYrmTZBwvy8inS4Iqg=,tag:rXu4sEoNDRVD0umgVJ2Lrg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdWF0c1VUZUpDNUxVcHJV
        a1d6YTdWaWZsSDRjcnJFZ2NKUVdtdnRLeG5zClNxQkFiSFNJbjRYZUduMUhmVlk1
        cFh4Ukxndkg5VENMTTBGUVozd3VOVGsKLS0tIFFSR1Q3eENQdXBBOS9GTnlMaXFC
        TmJSVkQ2NiswSy92bVJEblJwUzBrd2sKAJaSm28j0JdlK5rfsalCxa6XHwa7M0Z/
        MgJWBLy5DoO0PEkhrLffNQbIlhVBESEz5HsNll+K7+NLK6Hj7W4acQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T02:25:29Z"
  mac: ENC[AES256_GCM,data:ISrjYUdVQ30McwL8w24jdKdEgtpvrxGOohdUVE6vqNIc0e2q48VKFWzo2jzkgtGE+pIFvb63vYgNHZ70raEuedlz+vOqDumnPePbr9Uy2f/tdT2K8ndzVG2ZBLwlaVG9ouL9LNzi3PE5j/h1hc22Nfd5+p8UDU0kShgqvVP6DdU=,iv:fe3ckr/XrOiwEq7u6pP9sXnkRVP2yObjxaORyeJIf2E=,tag:5ddHG/vtad33meg909cOcw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
