apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:w38VTkVoykCQqZXP63j6qYdZw6uyFYHot+eDP+jGGU2FZlrQzOMDaErN4xoGUzsxHCkDfnw+EImkawsDbSLc3xgIVKMTtQ85ZWNx,iv:x5WiKtcm13P/pIdquuNvKtJ6/H1fU9LI8y4uQa5+oBQ=,tag:KWuPKCKUqeWxMuLYZJMndw==,type:str]
sops:
  age:
    - recipient: age1tkxcg67ket4j4rm3kce9zv0wmf7j4pf74cjw005f84sm7yhw94gs2axea8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZTE0d05CVStRbFRHdC9t
        VEtVNEhSNC9HcGJEdTBxRGh4MlRiWlhVbVZVCml0aWtSTFJ6RjVhVDIrd05xNU5M
        NnIyTG9qSjBJVjJMOXp4K2lIOTBpVkUKLS0tIHYweWg5Wjg0OUNQUHJuME9SN3pV
        Y1BuZTh2bG04UHJBM2pYZkNZc3ZraWcKXlQiCNJfDbGHH34Muf5FA65tRFNaNqze
        TATnPDIj3fY1Kw7krQNRtht4/HjhmX/kg+koMIpLvG47DrT/RvtUhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T16:57:18Z"
  mac: ENC[AES256_GCM,data:UYDTRocV/vJBV74T3ahhpNCZ1IWmn+s3ZY57NjaVohw/4XdVRvOJSeF65rEZWAGnEvPc0PJrVamsog1ntRxlOK28AnQZ+nyMw3PY/uWgAxZHcbf9CK51Hew2EbKaIpRO/dx9/40uSskp836C2QGssg45fLqqW1hr39adEd5i+D4=,iv:jdi9HWS7xir+UC0i53aolPwtxm837tf32rG2FF8rb1I=,tag:hl4fEfi/TfwU/Cj03/gt0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
