---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redis
  namespace: flux
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: redis
  path: ./kubernetes/apps/databases/redis/app
  prune: true
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 5m
