# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: readarr-audio
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:qMfmxtqkaME88u6PepqKtxycDrp3BqXcpmsrMhnVxpw=,iv:seu58TQXX/lnHg/ulVf5ahVgt6JNx2VEJdRAwiNVHO0=,tag:a1b3KKkbEDGnmQGXwFWeqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSkwwdGpkNncwcEV4YUdG
            dWp1M1BUL21uR0tRb1E3S20zOVJKUXFtMmhJCjFMS2pZUHN2S0VHaGVnbHdxN0Ri
            Ums5K0UxT3BLTGxkM0IvSmxOYWgreVUKLS0tIGhjQ3loN3JRT3hlNWp4YXk1ZFNN
            UGZNMWl3cGdZb3MwOS9uZXRiSm56Rk0Kfc6VhCsKjcOfeIrpVonrQbza7FSis+9C
            guUf/zu5FY+GiY1gKeaWwCgbkx7ECd2r9RmBdfcgfKAGxI6qBZYx5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T08:12:37Z"
    mac: ENC[AES256_GCM,data:Yle5Dg4Nuy6WNDPsYPWf9CS/JfoHjy3SdvmSrGr4AD0Anjoz2ouIo3rxEegP7NuLakN0nvf/FPxe/3A4KAQX0/6E7cCXBgAyfblIkqXELq67EtP2hHcoZUv5+n60m9ekhWpK+z++hNF28SMzi+3RDp+jO0c8n5i28FK9j08U030=,iv:cFiBPiHCG7Ya8aMD4rL632Umc8WATuKbZqRQVvidLeU=,tag:GrGMIB5gB5eXnsNsR3fbig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
