# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: organizers
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:nkFEtiA7YDpg5DK89HoFg04i3177ZX9UTVpD9Vjs7rw=,iv:2HbVLH9mPcSVDuCWf3FOQxp0K+IaEDodhYNaKuj5CiA=,tag:qRpRofiM2u/pjKmiliI/bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWFFTUGJYT2JYaVNIN2xQ
            aWEwY3VNWnZuUWpySlAvUmtDSUlZN05kb2xFCjdSUWh5MTc0SzRDSlNCd0tZTEJS
            Ry9nb0tuaUd0TGJrOW9iRE5ET0ljWGMKLS0tIHFKdHN6NjRIQ0IwRjBISEJOZHdM
            Q3o0YllKQ0haNmVWVGJNRWc3TnRIVE0KcWVCJriHICT3/yiP6xJj3PPiMv+KqldK
            7pLhX5JeAZdPGcANVwbnhzlqIKxMUXlZx1wKEyqdvW4hkMF2EloyMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T06:54:45Z"
    mac: ENC[AES256_GCM,data:LUPgl9wzJgWOP5wziREO/tajWFvrUZXUmoQU/Q0ERhlok0zsL6B82qYUjOPorvWvBSMz7bM0NwyofjukFfZk4wW1t2YF2+H6RkjKPI1kqterNFuEVplmx8S+u2q2JaBgMYY8yrGyyj/5CIUc5fCe8qt6wFkKBRqqUepzwrWhb5o=,iv:tw22kh99YD/OnIyptJZxZ18bNt7an06anzrn6Rj8HwM=,tag:mnKOjDF1g1M1Mx8wDPqcAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-restic-secret
    namespace: organizers
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Vqe/esUEaxPl7aiA3zxXrw8HmRyAz3y7vn3dZYat5X7ATl4/ASO1DINUx70D,iv:ff2+TLbZQTD9ZDnVjlffHUaNf94Z7yGIVIQmbCHyrSM=,tag:DeqbWPWk0Lq1NmkRXJM9Lw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:yDJDsbdDzIs=,iv:dBKnNW2fmolhk3yN76fXwFkuFwEZNFloEHOhMvkV8Mk=,tag:AwGXbHxjRLy/7PztVO7b2Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nosz454s+E9Py41czVxX3Q==,iv:yTrAmvdJSJZHrI60BeP4KEKmUzbKhVRymJodECeoTS8=,tag:fxpOfcRltVet8vapelmW1w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hoym8oPtgtqaDxas6qz/kBZPQkGZ30si+xxYbiICKWE=,iv:lxxElhfOzA7tjVK6QUkXyIZzN+u1AnaAnweQvkc7o/s=,tag:3oYLUH+Cna6vF2d7ox687A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWFFTUGJYT2JYaVNIN2xQ
            aWEwY3VNWnZuUWpySlAvUmtDSUlZN05kb2xFCjdSUWh5MTc0SzRDSlNCd0tZTEJS
            Ry9nb0tuaUd0TGJrOW9iRE5ET0ljWGMKLS0tIHFKdHN6NjRIQ0IwRjBISEJOZHdM
            Q3o0YllKQ0haNmVWVGJNRWc3TnRIVE0KcWVCJriHICT3/yiP6xJj3PPiMv+KqldK
            7pLhX5JeAZdPGcANVwbnhzlqIKxMUXlZx1wKEyqdvW4hkMF2EloyMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T06:54:45Z"
    mac: ENC[AES256_GCM,data:LUPgl9wzJgWOP5wziREO/tajWFvrUZXUmoQU/Q0ERhlok0zsL6B82qYUjOPorvWvBSMz7bM0NwyofjukFfZk4wW1t2YF2+H6RkjKPI1kqterNFuEVplmx8S+u2q2JaBgMYY8yrGyyj/5CIUc5fCe8qt6wFkKBRqqUepzwrWhb5o=,iv:tw22kh99YD/OnIyptJZxZ18bNt7an06anzrn6Rj8HwM=,tag:mnKOjDF1g1M1Mx8wDPqcAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
