# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: organizers
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:R4sbMza6A8OK+iwTX8IV7fS8fd7HlXzLwKDRN0g/Yv4=,iv:S52rOkNEp226it1xeHPxmBxtps10Kad2S74iRN3q//w=,tag:rVyO65HXRraoftTQixLW3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueUhQWXlnbVNZUzdScGlF
            WnVJWlpuUmFuam5TR0dyVlNIdGU2TFprU25rClFDLzFjVklOckUwL2JkdUh4NU13
            dXZ2RGthdFZLYTI0c2p5b2NlWkxPMG8KLS0tIEZ3NzYrZ3dObjdzUklvQTQ5eW9K
            NS9vNjQ0QWZLdTdSanEybk1NeTN5N2MKFsMCjWZZT360arncoxC3gb/kQ0wtVpks
            d7uDI2Zah55mqDr6eThHtOUqbNkm5GaWhlL8hZb8OhK/5kCniEY+RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T11:36:51Z"
    mac: ENC[AES256_GCM,data:LOFyvhUpqCAyhbg+E4ZrKIQKspqgcd924utea0+RP2If6uWj+wo//GffC+tlTBD30xZehJ+nAMXp+kyqONv0kFI6sEMQgM5e9iipF7v0XWq0Zi4DMcRedoZfOR1x/3eS9Gy+Nv5q9CuislN1Nn2d84lakHH0IT9SYhjm0WStLwU=,iv:euPDprPTtToE/9U79mcH20ksLHNFYwFDU8PMCPCa7RQ=,tag:kaMbgcr7b69D76oNGpRrqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-restic-secret
    namespace: organizers
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:x9Fr7LpUm+IZryhRGMB7YDHiOik4K+kiBd9XEaglHahBDc4raAY=,iv:G/ZW7nB2jQqROXD2o7HhPkhYnObIHTW9iVvTaVA0M6s=,tag:zNnjuXX5KP1sprdiM70Obg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:f/2sA/B6acg=,iv:yTts+a2MreLJjsWND+BHQvAvQVQj8dNoO+w3I++5JDM=,tag:v1KdUjg9MHRNUq7ck1b+uQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tFTno4cMxQXp/nwruNxDYw==,iv:CiA6T8VAffB1fRq+y3+bKlILu2q2Y9dUg/7If/wv8y0=,tag:Nx0379r9uAbEati/ZAfXQw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TnP3plGcMewGOTDjRJCYsLJEFBPAyXhVZ23XCbfSWSo=,iv:LG4XlC72jM2cel4Wt38cZAknU3vb6aJiKD/P4uBme4Y=,tag:VX9H/sqNEloNcZm0l/f5Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueUhQWXlnbVNZUzdScGlF
            WnVJWlpuUmFuam5TR0dyVlNIdGU2TFprU25rClFDLzFjVklOckUwL2JkdUh4NU13
            dXZ2RGthdFZLYTI0c2p5b2NlWkxPMG8KLS0tIEZ3NzYrZ3dObjdzUklvQTQ5eW9K
            NS9vNjQ0QWZLdTdSanEybk1NeTN5N2MKFsMCjWZZT360arncoxC3gb/kQ0wtVpks
            d7uDI2Zah55mqDr6eThHtOUqbNkm5GaWhlL8hZb8OhK/5kCniEY+RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T11:36:51Z"
    mac: ENC[AES256_GCM,data:LOFyvhUpqCAyhbg+E4ZrKIQKspqgcd924utea0+RP2If6uWj+wo//GffC+tlTBD30xZehJ+nAMXp+kyqONv0kFI6sEMQgM5e9iipF7v0XWq0Zi4DMcRedoZfOR1x/3eS9Gy+Nv5q9CuislN1Nn2d84lakHH0IT9SYhjm0WStLwU=,iv:euPDprPTtToE/9U79mcH20ksLHNFYwFDU8PMCPCa7RQ=,tag:kaMbgcr7b69D76oNGpRrqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
