# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: organizers
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:tCHsWc43u7USjpSUx5fCbNts/mydo2wYtt7NYNMGbYw=,iv:wMvB1L7sUwXiyv8KGyPZcckSNPvhy9Ix9lt35lS4xWc=,tag:uhuHScw/x9odQ1QFCYmELQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINFZwb0pkaitydU95Z1ZJ
            M3pxS0NjcWo4VkdaSmVjb0tZcGV0RkVVekJVCks2UnZNbXpic3FtZGpyUW5mcGNH
            RVl4eFVTK2RzdFdwVDVhSXREMUJxd3MKLS0tIEtoV3pRQURZMEVBVktXeVFLaHBz
            emJXcFYzVG1YUXM1M1c4bkwxMXlleFkKvVOIpkjxwFkiWB+XTGP6CBc2oGbXvcMr
            RSGvtFDKHDKOO5KZhPijIOYpkOh4kZgg2Zon22QV0Ob6X2Tr+516Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T10:21:46Z"
    mac: ENC[AES256_GCM,data:HOdahBNdzlk/s8//h3xXoIwAZ1Ja5JSX5TWbKbFO2JdyBCZflDI8hnVhFNFERsiujSW9gnIFoKfi2deSsHHdaYjBXVYlgr8QwU7dZ3hUHdNG6HdJNfq+xQwh8Rrf+8sYzGdlcxtjqNdl/bXXhE5BueJbGas0nSBUMv/3opxI0tw=,iv:MNfdJkbMeNTq8jLlkgzfjARnO98QuAQLW3TpESJHMZs=,tag:apC7/IgM7ryMPlPH52a8GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-restic-secret
    namespace: organizers
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:q0ROKTog2A2YblsRwgFsW06B2YptDO8uc12MY/7ZZYRRHeQ=,iv:emySf2gEyciJ44D05+MtzXj6N5S8igeO95npV7g8Rnw=,tag:ltKsZQ5D3aVpVMkGJ4cZ3A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:pxeyRx/Pumo=,iv:Zm2hbt7KwI/7k5+wDdIdl8HyttrOSBtj54bMxM+vjPw=,tag:gqeSKbq3Nu6Eu51F83jUcA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4jGUaZNPFbZVDozXXNOjDA==,iv:+7GjXAJYM9Z5EQZiu/95EpYU+iNQN96wvAc1ADfW1y4=,tag:pGx6LCYW/rzutlYYT1jKfw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/zSmZr55M5kH/1B9L/bRy9iHoNgRNnSS040e4FbewP0=,iv:iqvw3ZUukzwVeucbRikkzaKSMOatuPjyVp68PkZ7uEc=,tag:B2l6MAQrnchnEQg0474ihw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINFZwb0pkaitydU95Z1ZJ
            M3pxS0NjcWo4VkdaSmVjb0tZcGV0RkVVekJVCks2UnZNbXpic3FtZGpyUW5mcGNH
            RVl4eFVTK2RzdFdwVDVhSXREMUJxd3MKLS0tIEtoV3pRQURZMEVBVktXeVFLaHBz
            emJXcFYzVG1YUXM1M1c4bkwxMXlleFkKvVOIpkjxwFkiWB+XTGP6CBc2oGbXvcMr
            RSGvtFDKHDKOO5KZhPijIOYpkOh4kZgg2Zon22QV0Ob6X2Tr+516Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T10:21:46Z"
    mac: ENC[AES256_GCM,data:HOdahBNdzlk/s8//h3xXoIwAZ1Ja5JSX5TWbKbFO2JdyBCZflDI8hnVhFNFERsiujSW9gnIFoKfi2deSsHHdaYjBXVYlgr8QwU7dZ3hUHdNG6HdJNfq+xQwh8Rrf+8sYzGdlcxtjqNdl/bXXhE5BueJbGas0nSBUMv/3opxI0tw=,iv:MNfdJkbMeNTq8jLlkgzfjARnO98QuAQLW3TpESJHMZs=,tag:apC7/IgM7ryMPlPH52a8GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
