apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:VBk21hUTjds=,iv:eUSYMI0r0Js6LG95XlRQv7CcaSuZJfOLnCgoN2QoOUg=,tag:Av0DrIdfIkJLWrFyXiimOQ==,type:str]
    password: ENC[AES256_GCM,data:5J3lAKXHTFU=,iv:bIqSYYk3ywfse1PMzN48JPIlS+ItS3DTc2eA1isZQE0=,tag:T7jmwJk7U9+XUG+O9DHPkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2JqU1hBTUpnYWFYN0FP
            RXlUMUJpSUpqQjNmSVdVa0g0RXV3aGRYNVVJCm51MnpvTStYN2VITk9tbnZEdkYv
            UnFNc3YydEQ5a1JNVnY3N0M2QjlNVW8KLS0tIHM1dXpKUEt4RUlobGt5djhkZWxK
            RzVOWWZOU0IrR0RtNFhNQThqeDZhWncKLuQtrlm9TSj3On8E+UUgVDEq/5TekuSk
            m2/2yzHEJ3AZgQq8jcg+ax8WF454TVrOaRqQ/6hPsR0djGEUQgaDqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T03:49:13Z"
    mac: ENC[AES256_GCM,data:fAXwvQLUHQUXhMIO4KX5g4OP59eGiAB5H/D84d44Z3JLiqQ1Wr79vlJl6J3JUGemDRfQUnmwgLdwa38HwnVctAWN5LkmK1pvpl+EkcwE6n2S1i28LbjRkkrUGEzi7RnWvcgdZ/pxlyiKlEtdMtU/OAklCnJ3ex86icpnMigZnLg=,iv:LPbYZ6/cxRGezoUH22w8EssoKBd0SLy6vSE0g7hvzo0=,tag:RMbzQ8kYdtW/zWSAqS0H0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:PkqSBHBLhM0kSHODjpzW9Q==,iv:i/b5pi5u0fXMVIvOIpwBofHi9rSA3fhHrG/XGrgxv7s=,tag:9FO60/bu14cpInx5olFPbQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:5mKDb6VWC/176LBoEYaxykajkPuQnsRoT/FFt2++a64=,iv:7be1Vb+zGuqivuPxh6PfjzmyKnBF0vGHju5s3L7QxBo=,tag:+dzei4aPCTM8qCr3KibMVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2JqU1hBTUpnYWFYN0FP
            RXlUMUJpSUpqQjNmSVdVa0g0RXV3aGRYNVVJCm51MnpvTStYN2VITk9tbnZEdkYv
            UnFNc3YydEQ5a1JNVnY3N0M2QjlNVW8KLS0tIHM1dXpKUEt4RUlobGt5djhkZWxK
            RzVOWWZOU0IrR0RtNFhNQThqeDZhWncKLuQtrlm9TSj3On8E+UUgVDEq/5TekuSk
            m2/2yzHEJ3AZgQq8jcg+ax8WF454TVrOaRqQ/6hPsR0djGEUQgaDqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T03:49:13Z"
    mac: ENC[AES256_GCM,data:fAXwvQLUHQUXhMIO4KX5g4OP59eGiAB5H/D84d44Z3JLiqQ1Wr79vlJl6J3JUGemDRfQUnmwgLdwa38HwnVctAWN5LkmK1pvpl+EkcwE6n2S1i28LbjRkkrUGEzi7RnWvcgdZ/pxlyiKlEtdMtU/OAklCnJ3ex86icpnMigZnLg=,iv:LPbYZ6/cxRGezoUH22w8EssoKBd0SLy6vSE0g7hvzo0=,tag:RMbzQ8kYdtW/zWSAqS0H0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
