apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:Gmdg6rQ8GNI=,iv:e5c0uSg53GWhG3oUatMXWAVCgCiUQN0vMCY7nEMo/Ro=,tag:06/6n8ub1IGlllZEClwF8A==,type:str]
    password: ENC[AES256_GCM,data:yHnqNqc1EV0=,iv:wj9DjNknQ2Lpe9FZnU3Zq798KZx/GOs2bmZ2ivy4TJs=,tag:g7eYRUwfKO4ZjluR261t4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WVdIcEJrd0pFVjRod0dB
            c3RPOFh3QVZEREtWODJDOFUwTjBMU2JHanpNCkozZ0RUSWlRRGVpVlR3ZHhDc2Vm
            MUxRTVlseHJ5dnM2bWc4RG1wZEp0T1EKLS0tIFVKMVdITVEzejhNTzVjWmZaUVBs
            azdXOVpyOWd2eXo5SXY5KzN6OWFQUzgKeZAMI2bnOQbEfwfcYOOp5wza+alJzNUG
            YOuAhaM0jXaO614T2WMMTcvSm+UYTvPDzBpMp32PuIbrjNwfrqtyzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T20:16:09Z"
    mac: ENC[AES256_GCM,data:uvRWNru7keV8+OcuyOttlpuhj0V625NZeUEwTD+5p06udvNg4aHHYdKA1NATNrgJu7jH7nAFeh7TqaYzHAwCDN+SJYcWooYAXMMx1zzAduM8aoDKoJpDFEHiC65qHt+OD2awgmaQ4EEZkD48QOGPXCXBWaQMG7F0BZdSdo5CJb8=,iv:MS54fV0HJi7TEulT26B0njdAykEJRr1Xm6vzR3uYkeA=,tag:yEKJgGN6SEWhE05Nu2p7Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lRPpJ/U7+L3yvXjkOb3Z5Q==,iv:X2QA/VZM/9jrjqJHTvZOHLyG4rKolhAF/1cRny3bDv4=,tag:BW04bEN2EEiLRdTpzA+GEg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:XXO4quL7MxXs79woQuz1y/m3OC1w5Sh2pBLnRWaYPuI=,iv:dF8AzbhGS7VU5llqKYFKU4Vf4WpxaWmFED+72Tw2FL0=,tag:o2w/C34wHz8175vACjD6dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WVdIcEJrd0pFVjRod0dB
            c3RPOFh3QVZEREtWODJDOFUwTjBMU2JHanpNCkozZ0RUSWlRRGVpVlR3ZHhDc2Vm
            MUxRTVlseHJ5dnM2bWc4RG1wZEp0T1EKLS0tIFVKMVdITVEzejhNTzVjWmZaUVBs
            azdXOVpyOWd2eXo5SXY5KzN6OWFQUzgKeZAMI2bnOQbEfwfcYOOp5wza+alJzNUG
            YOuAhaM0jXaO614T2WMMTcvSm+UYTvPDzBpMp32PuIbrjNwfrqtyzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T20:16:09Z"
    mac: ENC[AES256_GCM,data:uvRWNru7keV8+OcuyOttlpuhj0V625NZeUEwTD+5p06udvNg4aHHYdKA1NATNrgJu7jH7nAFeh7TqaYzHAwCDN+SJYcWooYAXMMx1zzAduM8aoDKoJpDFEHiC65qHt+OD2awgmaQ4EEZkD48QOGPXCXBWaQMG7F0BZdSdo5CJb8=,iv:MS54fV0HJi7TEulT26B0njdAykEJRr1Xm6vzR3uYkeA=,tag:yEKJgGN6SEWhE05Nu2p7Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
