# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lidarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    LIDARR__API_KEY: ENC[AES256_GCM,data:RlURQx9BSr426Qys9mNgDAS1RS+z1f8q86N7GfxX+8U=,iv:C9Ih/ecsFsoMqqdAhOVMmBA5H1K3GBhqHCKgq7sGK1k=,tag:wO2ex9HBeYp7Mc0L/ulA1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTU5JWnZJdk9nNUVWL1pZ
            a0RGeXplZFVKYU5RKzZEeVp0encvTDVyd3hjCmVMakZzWlZvUGY1N0tXV2xPdXJI
            eUJOcXg4RnRhem5UNVp6RWtUUjJrd0EKLS0tIFpQcndhNnYxRTNqdm5tWkdMdGM4
            a1pvVVdrdG94dkJVM3JzcmpjWWRoR00KivE6biIKtHPHtrNT1BQThehCvLOKGUm3
            CDgtoQJgpxX3obt4gbLW+kPc2dwk7hz4OnzMTW8pKDYDFR//3gFTJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T05:05:14Z"
    mac: ENC[AES256_GCM,data:kvEoJZIeSv259ofZ1nEUBsYfu5r8cgrW6ze1mgAXXCTwFwPchusRrKaMWX1dSOI32AyspUCAVFfyyOlC8Dsk/0R3l8VOB4uXPz2yCbl7MBDoiL8bBloBP4PM54sPKMY2A3L95/kqhUAiJFeA8DU+wjh/z2e3/wX8hiA00cMUfuA=,iv:4W2cODKqhRDSZSJiGdprugqQZvniDLLeA6S6jos6idk=,tag:jAfPwO2MaFlJt5I4G+ySUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
