---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-v1
  namespace: downloaders
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

# storageClassName: longhorn
  storageClassName: ceph-block
