---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
  namespace: downloaders
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SABNZBD__API_KEY: "{{ .SABNZBD__API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__NZB_KEY }}"
  dataFrom:
    - extract:
        key: sabnzbd
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-vpn-secret
  namespace: downloaders
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-vpn-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # WIREGUARD_PRIVATE_KEY, WIREGUARD_ADDRESSES
        key: mullvad
