# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: downloaders
type: Opaque
stringData:
    SABNZBD__API_KEY: yooyaru6ociok8vfdzmeh06f38l7khyy
    SABNZBD__NZB_KEY: ocdktmngzi9nspn1f9fgziq3526z4axh
