# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: downloaders
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:XULsIKWPcKjasQhn1V3MYuVQTxdvgcde0X3gisjnSR8=,iv:U4wBfziswMPAGlYmadBnXsSzzitSkel7BpqyPiYkTso=,tag:ItIcofZQlnbSgmbeh+HnHw==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:tWWQ1WPJALokvqZeTjlpiftgEKjZHMP1ynJ2Qf8FNVU=,iv:+YR12f1nH7ArRwNK8Ep0vpUzXFc3I8sfP3zCPYp62C0=,tag:O1xH0huyxTC025eekpUgPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb1B6N1hweSt6b0lESXph
            MkN3anU5SjgyOStTSzBEQzBXU0pTSFo5U0dzCjJwZ0RjWFV2R1NrT09tUXhZN21s
            RFNuaml5azBpeUlyVysxWG94UHhlZkUKLS0tIEx3VU0wK256WXRqc0tmY3hpY3BT
            czFuWjFRVEFDMTFZN1JQNWhKdjlSQkkKzfgxvStZKQnEuOlK6UIrngurrTstl+Ys
            a/ktYfbERjnEcXXB+o/K+MxxAkSAQLcfx/x7iWXyicMLIJBPCST/zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T09:04:52Z"
    mac: ENC[AES256_GCM,data:wyJ7P6qFDuPcySbnLHxU52QqcSsOvOlUWSC8E2H+jE0DIhEwdnxurC2XEblrZcmJAujmhAkyVh3ZZLsmAs1tayE4eWwDTC8NEl5tgdy7aEid86lGAU3iDKLkOU9ZVv3O+H3PGqaMkye2Ekp16Axwn2q6U+5nL1ToXZEsM2zqopQ=,iv:bGInbqJj99YhqU6lft3fxL0uceQWj3vVaAXUGL0F0bw=,tag:zrPeEVa/2t9ZknxmW7EEog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
