---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-csi
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: synology
  labels:
    goldilocks.fairwinds.com/enabled: "true"
